### ISSUE TITLE
 ✔ Container tutor_local-mysql-1  Running                                                                                                                                                             0.0s  Initialising MySQL... mysql: [Warning] Using a password on the command line interface can be insecure. ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)     [1/10] Waiting for MySQL service (this may take a while)... mysql: [Warning] Using a password on the command line interface can be insecure. ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql:3306' (111)     [2/10] Waiting for MySQL service (this may take a while)...

### ISSUE THREAD

**Issue by balkishaniaastha** [overhangio/tutor#1002]
I am using ubuntu 20.04 and python 3.10

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
