### ISSUE TITLE
Python 3.11/3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor#1004]
Open edX Redwood release planned for June this year will be [upgrading  from Python 3.8](https://discuss.openedx.org/t/python-3-12-upgrade-for-tutor-and-its-plugins/12323) to Python 3.11 (for edx-platform) and Python 3.12 (for other services). That means the tutor core and its plugins need to be upgraded to support the new Python version. The Python upgrade is focused on two areas:

1. Ensuring the plugin uses 3.11/3.12 to run the underlying service.
2. Ensuring the tutor and tutor plugins code is compatible with 3.12.

The service upgrade is under progress (https://github.com/openedx/public-engineering/issues/228). In the meantime, the upgrade can be done for tutor core itself. This task/issue will act as an epic for the underlying upgrade tasks. 

### General Guidelines

- Ensure any issue encountered in the tutor, be it due to tutor or the upstream service, is documented on this main issue. If needed, create a separate task/issue to fix it.
- **Prioritize dockerfile changes for 3.11/3.12 compatibility.** This is needed for the Redwood cut in late April.
- Once done, you can add appropriate CI checks for 3.12
- Start with existing test suites upgrade/compatibility i.e. ensure the test suites in the repo are passing on Python 3.12. Document any test failure and the fix done for remediate the failure
- To make sure that changes are working as expected, ensure the following where needed
   - verify that the images are built correctly
   - verify the service is up and running after `tutor local launch`
- The aim is to merge the Py3.12 changes directly in `master` (similar to https://github.com/overhangio/tutor/issues/966).
- Do not hesitate to ask for help, guidance, and/or clarity where needed. 

 This means the set of changes would need to be compatible with Py 3.8 as well (atleast until the redwood is not released). **However, Dockerfile changes would go into nightly**.

### Action Items
- Ensure the build is working as expected (core or plugins) with Py311/Py312 (via Dockerfile updates)
- Add Python 3.12 CI pipeline alongside 3.8. This would remain in place until redwood release
- Ensure the fixups for failures are done and the code is compatible with Py38

#### Depend on Upstream changes
- [x] Tutor - https://github.com/overhangio/tutor/issues/1006
- [x] tutor-discovery - https://github.com/overhangio/tutor-discovery/issues/62
- [x] tutor-ecommerce - https://github.com/overhangio/tutor-ecommerce/issues/68
- [x] tutor-credentials - https://github.com/overhangio/tutor-credentials/issues/34
- [x] tutor-forum - https://github.com/overhangio/tutor-forum/issues/31
- [x] tutor-notes - https://github.com/overhangio/tutor-notes/issues/33
- [x] tutor-xqueue - https://github.com/overhangio/tutor-xqueue/issues/29

#### Independent of An Upstream

- [ ] ~~tutor-android - https://github.com/overhangio/tutor-android/issues/19~~
- [x] tutor-cairn - https://github.com/overhangio/tutor-cairn/issues/31
- [x] tutor-indigo - https://github.com/overhangio/tutor-indigo/issues/72
- [x] tutor-jupyter - https://github.com/overhangio/tutor-jupyter/issues/6
- [x] tutor-mfe - https://github.com/overhangio/tutor-mfe/issues/192
- [x] tutor-minio - https://github.com/overhangio/tutor-minio/issues/36
- [x] tutor-webui - https://github.com/overhangio/tutor-webui/issues/12
- [x] cookiecutter-tutor-plugin - https://github.com/overhangio/cookiecutter-tutor-plugin/issues/30
- [x] openedx-scorm-xblock - https://github.com/overhangio/openedx-scorm-xblock/issues/67

**Comment by kdmccormick** [comment]
@DawoudSheraz We discussed in Lahore that upgrading Python to 3.12 in the Dockerfiles is top priority for Redwood, whereas testing the actual plugin code with 3.12 is not important for Redwood. Could you update the ticket description with that?

**Comment by DawoudSheraz** [comment]
> @DawoudSheraz We discussed in Lahore that upgrading Python to 3.12 in the Dockerfiles is top priority for Redwood, whereas testing the actual plugin code with 3.12 is not important for Redwood. Could you update the ticket description with that?

Updated. We have CI checks PRs up for most of the repos, so that is sort-of already done. For dockerfile changes, the changes have been categorized into "Dependent on Upstream" and "Independent of Upstream". For dependents, the issues/failures are being added to the related issues. We are opening PRs in upstreams where needed for 3.12 compatibilties. But for most parts, we are also monitoring 3.12 upgrades in upstream using https://github.com/openedx/public-engineering/issues/234

**Comment by DawoudSheraz** [comment]
All the tasks have been completed, closing this issue.
