### ISSUE TITLE
django-require miss URL 

### ISSUE THREAD

**Issue by rsuigh** [overhangio/tutor#1013]
**Bug description**
the repository https://github.com/edx/django-require.git changed to https://github.com/openedx/django-require, then `tutor image build openedx` are broken

**How to reproduce**
Just run `tutor image build openedx`

**Environment**
im using ubuntu bullseye/sid and tutor v13.3.2

**Comment by rsuigh** [comment]
Hi, i figure it out.
just added this snipet in a plugin:

```
name: django-require-edx-org-fix
version: 0.2.0
patches:
  openedx-dockerfile-minimal: |
    #----------------------------------------------------DJANGO-REQUIRE-EDX-ORG-FIX----------------------------------------------------#
    RUN git config --global url."https://github.com/openedx/django-require.git".insteadOf "https://github.com/edx/django-require.git"
    #--------------------------------------------------END DJANGO-REQUIRE-EDX-ORG-FIX--------------------------------------------------#
```

thanks!

**Comment by regisb** [comment]
FYI this issue was triggered by this change documented here: https://discuss.openedx.org/t/please-update-your-git-urls-for-edx-platform-and-several-other-repos/12387
