### ISSUE TITLE
K8s deployment fails when there's no persistent volume claims to apply

### ISSUE THREAD

**Issue by snglth** [overhangio/tutor#1030]
**Bug description**

I have following options in my `config.yml`:
```yaml
RUN_ELASTICSEARCH: false
RUN_MONGODB: false
RUN_MYSQL: false
RUN_REDIS: false
RUN_SMTP: false
```
It blocks k8s deployment since there's no persistent volume claims to apply:
```
-x tutor k8s start
kubectl get namespaces openedx
NAME      STATUS   AGE
openedx   Active   2d21h
Namespace already exists: skipping creation.
kubectl apply --kustomize /Users/snglth/Development/Abstract/fc-tutor/env --wait --selector app.kubernetes.io/component=volume
error: no objects passed to apply
Error: Command failed with status 1: kubectl apply --kustomize /Users/snglth/Development/Abstract/fc-tutor/env --wait --selector app.kubernetes.io/component=volume
```
I think that it should not be like that.

**How to reproduce**

Described above

**Environment**

macOS 14.4.1, tutor 17.0.3
**Additional context**

**Comment by DawoudSheraz** [comment]
Hi. Under what circumstances would we not want any volumes for k8s (by disabling all the configs)? In all the cases, are you relying on externally hosted services?

**Comment by yagouam** [comment]
Hello @DawoudSheraz, that's exactly our use case. We have all the services externallized in another machine, out of our Cluster.

**Comment by snglth** [comment]
This is also our case. We keep all the stateful services outsite of K8s cluster.

**Comment by angellareo** [comment]
Same case here. Fix works nicely. Thanks @snglth.
