### ISSUE TITLE
Supply MySQL 8.2 or 8.3 by default

### ISSUE THREAD

**Issue by snglth** [overhangio/tutor#1051]
**Is your feature request related to a problem? Please describe.**
MySQL 8.1 reached [EOL around 6 months ago](https://endoflife.date/mysql)

**Describe the solution you'd like**
Provide MySQL 8.2 or 8.3 by default. Both are still supported.

**Describe alternatives you've considered**

**Additional context**

**Comment by snglth** [comment]
MySQL 8.4 LTS [released recently](https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html). I think it would be better to stick to it until the next LTS release.

**Comment by rohan-saeed** [comment]
#1071

**Comment by DawoudSheraz** [comment]
@rohan-saeed Please update the issue. Thank you.
