### ISSUE TITLE
I just want to install this with Docker-compose I don't need a special magical configurator.

### ISSUE THREAD

**Issue by Leopere** [overhangio/tutor#1053]
**Is your feature request related to a problem? Please describe.**

I can recognize why someone might want to not have to teach someone how to use Docker to be able to use this application but I already know how to use Docker and it feels very opaque as to how to just get a docker compose that defines how this needs to be run without giving it docker socket control.

**Describe the solution you'd like**

Just some idea where a config might want to live or what envvars a container might want so I can just do the rest.
**Describe alternatives you've considered**

Sekai or something but Sekai is pretty convoluted it seems.
**Additional context**

Just would like this to behave as a normal docker container so that I can deploy it with the rest of my dockerized stuff without strange non standard deployment magic.  I know this is probably magic for everyone who loves it I just would love to find just a dockerfile or two with a number of envvars or something even the pip install tutor basically just wants to intervene in how docker works.

**Comment by kdmccormick** [comment]
@Leopere I won't bore you with a detailed history of the architecture, but the gist is that Open edX has way too many knobs and levers, and Tutor kinda exists as this big master control panel that turns all the knobs and levers for you. It's helped a lot of people, but I can sympathize that it's made everything more magical than it needs to be and isn't as good as simplifying Open edX itself (we're working on that too, I promise).

A couple things that might help you right now:
* If you install Tutor and run `tutor config save`, then all the files that Tutor uses to run Open edX will be rendered to your config root (`cd $(tutor config printroot)/env`). You can copy those somewhere else and use them directly with docker and docker compose if you'd like. 
* Most Tutor commands print out the underlying docker/docker-compose command which you can run directly, eg
  ```
  $ tutor images build all
  Adding /home/kyle/openedx/edx-platform to the build context 'edx-platform' of image 'all'
  Building image docker.io/overhangio/openedx:17.0.4-nightly
  docker buildx build --tag=docker.io/overhangio/openedx:17.0.4-nightly --output=type=docker --cache-from=type=registry,ref=docker.io/overhangio/openedx:17.0.4-nightly-cache --build-context=edx-platform=/home/kyle/openedx/edx-platform /home/kyle/tutor-root/env/build/openedx
  ..
  ```

**Comment by Leopere** [comment]
> @Leopere I won't bore you with a detailed history of the architecture, but the gist is that Open edX has way too many knobs and levers, and Tutor kinda exists as this big master control panel that turns all the knobs and levers for you. It's helped a lot of people, but I can sympathize that it's made everything more magical than it needs to be and isn't as good as simplifying Open edX itself (we're working on that too, I promise).
> 
> A couple things that might help you right now:
> 
>     * If you install Tutor and run `tutor config save`, then all the files that Tutor uses to run Open edX will be rendered to your config root (`cd $(tutor config printroot)/env`). You can copy those somewhere else and use them directly with docker and docker compose if you'd like.
> 
>     * Most Tutor commands print out the underlying docker/docker-compose command which you can run directly, eg
>       ```
>       $ tutor images build all
>       Adding /home/kyle/openedx/edx-platform to the build context 'edx-platform' of image 'all'
>       Building image docker.io/overhangio/openedx:17.0.4-nightly
>       docker buildx build --tag=docker.io/overhangio/openedx:17.0.4-nightly --output=type=docker --cache-from=type=registry,ref=docker.io/overhangio/openedx:17.0.4-nightly-cache --build-context=edx-platform=/home/kyle/openedx/edx-platform /home/kyle/tutor-root/env/build/openedx
>       ..
>       ```

I love history <3 okay thats fine I don't really need a history lesson but it sounds like I'll need to prepare EdX in a VM then I can port it over to Swarm via the compose if I understand correctly.
