### ISSUE TITLE
Security patching for Quince

### ISSUE THREAD

**Issue by cmltaWt0** [overhangio/tutor#1067]
This is a Quince security patching request.

@ormsbee  published a [security advisory](https://github.com/openedx/edx-platform/security/advisories/GHSA-99vw-2wrq-xh9x) last week (forums post [here](https://discuss.openedx.org/t/upcoming-security-fix-for-edx-platform-on-2024-05-17/13004/2?u=dave)).

The fix was merged to master and backported to redwood and quince master branches.
open-release/quince.master: [fix: prevent setting user attributes from JWT in Studio · openedx/edx-platform@3ff69fd · GitHub 2](https://github.com/openedx/edx-platform/commit/3ff69fd5813256f935f19c237ea0c42d4c16edbf)

As discussed during BTR WG meeting - we want to patch the edx-platform via the build process in Tutor and publish a 
patch release (17.0.5?).

@regisb

**Comment by regisb** [comment]
Just to clarify: you mentioned v16.1.9, but I think you really meant 17.0.5? We want to patch Quince, not Palm, right?

**Comment by DawoudSheraz** [comment]
Yeah, we are going for 17.0.5. The security patch upstream has been merged to master, redwood.master, and quince.master. We don't need any action for palm.

**Comment by cmltaWt0** [comment]
@regisb @DawoudSheraz Ma bad. 17.0.5 👍

**Comment by DawoudSheraz** [comment]
PR for changes in dockerfile https://github.com/overhangio/tutor/pull/1068. 
Once merged, a followup PR will be created for v17.0.5 release.

**Comment by DawoudSheraz** [comment]
PR https://github.com/overhangio/tutor/pull/1069 for v17.0.5 release

**Comment by regisb** [comment]
Solved by #1068
