### ISSUE TITLE
In Tutor core & plugins, the minimum Python version should be bumped from 3.8 to 3.9

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#1129]
**Is your feature request related to a problem? Please describe.**

Python 3.8 is reaching end-of-life on Oct. 31st: https://endoflife.date/python This means that the minimum supported version of Tutor should bump to 3.9.

**Describe the solution you'd like**

1. we should bump the minimum required version of Tutor and all plugins to 3.9.
2. CI must be upgraded to build binaries with 3.9.
3. We must get rid of documentation warnings triggered by python 3.8
4. Basically, all references to 3.8 must be removed.

**Comment by DawoudSheraz** [comment]
PRs for Tutor core and plugins (some plugins might be removed from list if the action is not needed)
- [ ] Tutor https://github.com/overhangio/tutor/pull/1150
- [ ] tutor-indigo 
- [ ] tutor-mfe
- [ ] tutor-ecommerce
- [ ] tutor-discovery
- [ ] tutor-credentials
- [ ] tutor-minio
- [ ] tutor-forums
- [ ] tutor-notes
- [ ] tutor-xqueue
- [ ] tutor-jupyter
- [ ] tutor-webui
- [ ] tutor-android
- [ ] tutor-cairn
- [ ] cookie-cutter

**Comment by regisb** [comment]
Let me know once you are ready and I can either open PRs or push straight to the repos.

**Comment by DawoudSheraz** [comment]
All PRs have been merged, closing this issue.
