### ISSUE TITLE
Dry Run feature for k8s

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#1138]
The proposed dry run command for tutor would significantly enhance the deployment process by allowing users to preview the changes to the Open edX configuration before actually applying them to the Kubernetes cluster. This would help identify potential issues and avoid unintended disruptions in the live environment, ensuring a smoother deployment experience.
A subcommand of k8s, like :
```bash
tutor k8s dry  # I'm not sure about the naming
```
If there are no objections, I'll be happy to implement this.

**Comment by DawoudSheraz** [comment]
@CodeWithEmad Hi. Can you give some examples and context on what this would achieve or help with? Thanks

**Comment by DawoudSheraz** [comment]
> Hey @DawoudSheraz. It can:
> 
> * Preview configuration changes before applying them.
> * Identify potential conflicts or errors in advance.
> * Reduce the risk of unexpected issues in the live environment.
> * Save time by catching problems early in the deployment process.
> 
> This feature would be especially valuable for complex setups or when making significant changes to the Open edX configuration.

Right. Will it be a wrapper to k8s dry run commands? Anyway, I get the potential use cases for this. Thanks for suggesting this.
@regisb What are your thoughts?

**Comment by CodeWithEmad** [comment]
> Will it be a wrapper to k8s dry run commands? 

Yes, it will be a wrapper around [kubectl apply](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_apply/) --dry-run.

**Comment by regisb** [comment]
You mean, like [`make test-k8s`](https://github.com/overhangio/tutor/blob/9e5a87bea7a445b4c993fd11a13d03a6670700be/Makefile#L48) or `tutor k8s apply --dry-run=client --validate=true`? Tutor already provides an API for `kubectl apply`. Maybe all we need is better documentation on this feature?

**Comment by DawoudSheraz** [comment]
> You mean, like [`make test-k8s`](https://github.com/overhangio/tutor/blob/9e5a87bea7a445b4c993fd11a13d03a6670700be/Makefile#L48) or `tutor k8s apply --dry-run=client --validate=true`? Tutor already provides an API for `kubectl apply`. Maybe all we need is better documentation on this feature?

Ah, nice. `make test-*` inherently implies we are running some sort of tests (at least in Open edX ecosystem). I agree that documenting it differently can make it more visible.

**Comment by CodeWithEmad** [comment]
And now I feel dumb :D 
I didn't know about the `tutor k8s apply` command. I'll close this one and will come up with some changes in the docs.
