### ISSUE TITLE
Setting CADDY_HTTP_PORT to a nonstandard port breaks the LMS sing in

### ISSUE THREAD

**Issue by sanyaade-teachings** [overhangio/tutor#1183]
Yes I did

**Bug description**

Tutor

**How to reproduce**

Yes! I disable web proxy since I already have one and port 80 already in use, so I ran the command and configured as shown below
    **tutor config save --set ENABLE_WEB_PROXY=false --set CADDY_HTTP_PORT=81**

**Environment**

**Additional context**

The studio.sanyaade.com works as expected:
![image](https://github.com/user-attachments/assets/9d74694a-2c35-4177-a840-6f345072496c)

But sign in button does not work(same as sign up):
![image](https://github.com/user-attachments/assets/5d62f236-e7c7-4f87-9bc9-925a30da37dd)

How can I set the port for the LMS, which config file should I look into? Many thanks!

Hear from you soon.

God blesses!!!

Regards

**Comment by regisb** [comment]
Error 502 means that your proxy is not able to reach your caddy instance. This could be due either to proxy misconfiguration or some other issue with Caddy.

Since this does not appear to be a bug in Tutor, please open a topic in the Open edX forum: https://discuss.openedx.org/
