### ISSUE TITLE
Implement platform testing

### ISSUE THREAD

**Issue by frob** [overhangio/tutor#129]
Discuss testing and possible travisci/github actions autobuild/push to docker hub.

**Comment by regisb** [comment]
Note that there is already some kind of "testing" in place, done by travis-ci:
- https://github.com/regisb/tutor/blob/master/.travis.yml
- https://github.com/regisb/tutor/blob/master/Makefile#L37
- https://travis-ci.org/regisb/tutor
In particular, travis-ci is already in charge of pushing updated images to docker hub.

**Comment by regisb** [comment]
> It might time out

Yes it does :)

**Comment by regisb** [comment]
> I have taken a look, we should be able to run the tests provided by edx

I have tried this, once, and it's not trivial. For instance, we need to create new test settings. My first road block was that the openedx docker image does not contain the mongo binary, which is required to run some of the tests.

**Comment by frob** [comment]
We could add a test specific docker compose and dockerfile that imports the
openedx image to add the things the test needs to run. Also looks like an
upstream change should happen on 5he edx-platform tests to make the tests
more granular.

**Comment by regisb** [comment]
This is work in progress: https://github.com/overhangio/openedx-e2e
