### ISSUE TITLE
Make tutor better for micro frontend development 

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#190]
With the evolution of Open edX towards micro frontends, tutor needs to become a better tool at the service of frontend developers. I have little experience on this topic, so it would be great to collect feedback directly from Open edX frontend developers, such as @willingc. Then we can implement the required features, in a readme-driven development kind of way.

**Comment by regisb** [comment]
@willingc any chance you can contribute to this issue? If not, I'm going to have to close it. I'd be happy with a "not now but later!" answer :)

**Comment by willingc** [comment]
Let's do this... Let's start by adding a documentation section under open edx development. I think the features are already there but just need a small paragraph or two about the React front end builds. Assign it to me and I will try to get to it in the next couple of weeks. :smile:

**Comment by regisb** [comment]
oh yeah! #217

**Comment by regisb** [comment]
Work has now moved to https://github.com/overhangio/openedx-micromanager/
