### ISSUE TITLE
devstack of lms and cms together?

### ISSUE THREAD

**Issue by carlos-wong** [overhangio/tutor#239]
**Is your feature request related to a problem? Please describe.**

in the dev env, I am only can test one platform. But sometimes I need create course in the studio page and then test in the student page. In this situation I am need stop old container then start the new one.

**Describe the solution you'd like**

can we make a dev command let the lms and cms work together?

**Describe alternatives you've considered**

**Additional context**

**Comment by regisb** [comment]
Hi @carlos-wong! You can simply run the two commands separately, in two different terminals:

```
tutor dev runserver lms
tutor dev runserver cms
```

The lms and the cms will then be available at http://0.0.0.0:8000/ and http://0.0.0.0:8001/ and they will share the same databases :sunglasses:

**Comment by carlos-wong** [comment]
ok @regisb 

thanks
