### ISSUE TITLE
open edx installation problem in make dev.provision

### ISSUE THREAD

**Issue by nattyfeleke** [overhangio/tutor#248]
![Screenshot from 2019-09-07 04-27-13](https://user-images.githubusercontent.com/48653873/64472140-cd4fce80-d127-11e9-889d-a0fd5f6341d0.png)

I don't understand the problem, how can i fix this

**Comment by regisb** [comment]
Hi @nattyfeleke! Are you trying to run the Open edX devstack? The Tutor distribution is totally unrelated and does not use the devstack deployment scripts. I suggest you ask your question on the [Open edX discussion forums](https://discuss.openedx.org/) (don't forget to read the ["how to get help"](https://discuss.openedx.org/t/how-to-get-help/200) message first).
