### ISSUE TITLE
tutor local quickstart, pulling images fails with: Error: unauthorized: authentication required

### ISSUE THREAD

**Issue by chpanag** [overhangio/tutor#251]
**Bug description**
Started a new deployment of a tutor instance. This time I chose to build tutor myself (latest source:3.7.0) instead of downloading the binaries.  While running the `tutor local quickstart` in order to install tutor/openedx the pulling of images at sometimes exits and reports"
`ERROR: unauthorized: authentication required`.

**Environment**
CentOS7 running in a VM hosted by Virtualbox on my laptop. Networking configured with NAT, with just the ssh port forwarded for the moment.

**Comment by regisb** [comment]
This seems to be an issue with your docker environment. Please try to pull the failing images manually, with `docker pull ...` and reports the result here. I'll close this now and re-open if I realise that this is in fact an issue with tutor.
