### ISSUE TITLE
Error after importing sample course

### ISSUE THREAD

**Issue by adrian-marcelo-gallardo** [overhangio/tutor#256]
**Bug description**

I've followed the steps to import the demo-course through the CMS (following the steps enumerated here: https://github.com/edx/edx-demo-course)

The course is created and I can see it in the LMS, but the CMS crashes when I enter to edit the course (I'm running the dev CMS version):

![Screen Shot 2019-10-08 at 10 57 50 AM](https://user-images.githubusercontent.com/33430733/66412188-ab619a00-e9ba-11e9-8feb-ee160148fcba.png)

**How to reproduce**

Download the gzip course from here: https://github.com/edx/edx-demo-course
Run CMS using `tutor dev runserver cms`
Open the CMS, go to import, and select the gzip course to start importing
The import utility fail before finishing, but the course is still created and accessible from the LMS.
If you want to enter to edit the course, the error shown above is displayed.

**Environment**

MacOS High Sierra

**Additional context**

Not sure if `tutor local importdemocourse` fixes this issue; the problem is I can't use it because it doesn't work for the development CMS server.

**Comment by regisb** [comment]
Hi @adrian-marcelo-gallardo! I see that the README recommends that the 1.0 gzipped tarball be downloaded (https://github.com/edx/edx-demo-course/releases/download/1.0/edx_demo_course_1_0.tar.gz), but this release is 6 year old. Did you try downloading the ironwood.2 release? https://github.com/edx/edx-demo-course/archive/open-release/ironwood.2.tar.gz

Also, did you know there is a `tutor local importdemocourse` command in tutor?

**Comment by adrian-marcelo-gallardo** [comment]
Hello @regisb, thanks for the quick reply!

You were right, using the version on the home README didn't work, but the last version you shared in your comment worked great! Thanks for helping me with this issue 👏 👏 👏 

On a side note, I was not able to run `tutor local importdemocourse`. I believe it is because I'm running the CMS locally with `tutor dev runserver cms`, and when I run `importdemocourse` it is complaining `cms_1` container doesn't exists.

**Comment by regisb** [comment]
> You were right, using the version on the home README didn't work, but the last version you shared in your comment worked great! Thanks for helping me with this issue

Awesome! For the record, I opened a pull request to solve this issue upstream: You were right, using the version on the home README didn't work, but the last version you shared in your comment worked great! Thanks for helping me with this issue

> On a side note, I was not able to run tutor local importdemocourse. I believe it is because I'm running the CMS locally with tutor dev runserver cms, and when I run importdemocourse it is complaining cms_1 container doesn't exists.

That's right. In order to import the demo course, you should actually run:

```
tutor local quickstart
tutor local importdemocourse
```
