### ISSUE TITLE
Initialising cms...Error: Command failed with status 137

### ISSUE THREAD

**Issue by haharay** [overhangio/tutor#259]
**Bug description**

When installing tutor on MacOS
seeing this issue

.....
Initialising cms...
docker-compose -f /Users/rayhe/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local exec cms sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s && ./manage.py cms migrate

\# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating CMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
2019/10/11 10:23:25 Waiting for: tcp://mysql:3306
2019/10/11 10:23:25 Connected to tcp://mysql:3306
Error: Command failed with status 137: docker-compose -f /Users/rayhe/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local exec cms sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s && ./manage.py cms migrate

\# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating CMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
**How to reproduce**
tutor local quictstart

**Environment**
MacOs 10.15

**Additional context**
tutor is installed by pip,  the version is 3.7.2

**Comment by regisb** [comment]
Hi @haharay ! Please see https://discuss.overhang.io/t/error-command-failed-with-status-137/151.
