### ISSUE TITLE
3.7.3 version not available for MacOSX

### ISSUE THREAD

**Issue by natea** [overhangio/tutor#261]
Any ideas why I'm getting this error after updating my local `tutor` binary? (i'm on MacOSX).

```
$ sudo curl -L "https://github.com/overhangio/tutor/releases/download/v3.7.3/tutor-$(uname -s)_$(uname -m)" -o /usr/local/bin/tutor
$ sudo chmod 0755 /usr/local/bin/tutor
$ tutor local quickstart
/usr/local/bin/tutor: line 1: Not: command not found
```

This is the output of the `$(uname -s)_$(uname -m)` command:

```
$ echo $(uname -s)_$(uname -m)
Darwin_x86_64
```

So then I went to the releases page and discovered that the MacOSX version of v3.7.3 doesn't exist yet.

https://github.com/overhangio/tutor/releases

So I reverted to 3.7.2, and now it's working.

**Comment by regisb** [comment]
Yes, the Mac OS build failed on Travis and I haven't had time to investigate yet. For the moment you should install tutor with pip to run the latest version.

**Comment by regisb** [comment]
This is due to a missing requirement file in the pypi package. It's currently impossible to install tutor v3.7.4 with pypi :fearful:
