### ISSUE TITLE
3.7.4 tutor local quickstart lms migration oauth2 failure

### ISSUE THREAD

**Issue by fre-db** [overhangio/tutor#262]
**Bug description**
After succesfully setting up Tutor on a remote server, I wanted to get started on developing locally. I installed Tutor 3.7.4 but upon trying `tutor local quickstart` the process fails on migrations for LMS.

More specifically:

```
Running migrations:
  Applying oauth2.0001_initial...Traceback (most recent call last):
  ...
   django.db.utils.OperationalError: (1050, "Table 'oauth2_accesstoken' already exists")
```

The full ouput can be found here: [https://pastebin.com/mmmciuJu](https://pastebin.com/mmmciuJu)

I have tried deleting all containers and volumes but I get this same error.

**Environment**
OSX, Docker Desktop CE 2.1.0.4 , Docker 19.03.4, Compose 1.24.1

**Comment by fre-db** [comment]
*** Update***
I have entered the MySQL container itself using `docker exec -it tutor_local_mysql_1` , and manually dropped the tables `oauth2_provider_trustedclient` and `oauth2_accesstoken` from the MySQL DB. 

Running migrations/quickstart after this worked.

I have no idea how the database gets corrupted like that consistently, as deleting the docker containers/volumes and trying again gave the same issue.

**Comment by regisb** [comment]
Hi @fre-db! How exactly did you delete the volumes? Are you aware that the containers use local bind mount?

**Comment by regisb** [comment]
> I am relatively new to Docker so apologies if I'm missing something basic :)

No worries! `docker system prune --volumes` will only delete mounted volumes. But the data is mounted in docker containers via bind mounts. That means that the volumes are accessible in regular folder from the host. In the case of tutor, these bind mounts are located in `$(tutor config printroot)/data`.

What probably happened to you is that mysql migrations crashed or were stopped halfway. To address this issue, you should have stopped the containers and deleted the mysql data:

     tutor local stop
     sudo rm -rf "$(tutor config printroot)/data/mysql"
