### ISSUE TITLE
Watchthemes not working on master

### ISSUE THREAD

**Issue by adrian-marcelo-gallardo** [overhangio/tutor#263]
**Bug description**

Running the new `watchthemes` command (as stated on the README file on master branch) is not working.

I'm running: `tutor dev run lms watchthemes` and got the following output:
https://pastebin.com/ASWnLw3N

**How to reproduce**

Run tutor on master branch.
Run the command `tutor dev run lms watchthemes`

**Environment**

MacOS Mojave

**Additional context**

--

**Comment by regisb** [comment]
You should run `tutor dev run watchthemes` as per https://github.com/overhangio/tutor/blob/master/docs/dev.rst#customised-themes
