### ISSUE TITLE
Services fail to start

### ISSUE THREAD

**Issue by luisc09** [overhangio/tutor#266]
**Bug description**
You can not start the services if `ACTIVATE_ELASTICSEARCH` and `ACTIVATE_MONGODB` are set as false, and `ACTIVATE_FORUM`, docker-compose command will throw an error on forum service. 

```ERROR: The Compose file '/home/xxx/.local/share/tutor/env/local/docker-compose.yml' is invalid because:
services.forum.depends_on contains an invalid type, it should be an array
Error: Command failed with status 1: docker-compose -f /home/xxx/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local rm --stop --force
```
[depends_on](https://github.com/overhangio/tutor/blob/master/tutor/templates/local/docker-compose.yml#L101) of Forum service is empty when the aforementioned variables are both set to false. 

**How to reproduce**
In config.yml set:
ACTIVATE_ELASTICSEARCH to false
ACTIVATE_MONGODB to false 
ACTIVATE_FORUM to true

**Environment**
- Amazon Linux
- tutor, version 3.7.4

**Additional context**
We have set a ElasticSearch and MongoDB running in different instances.

**Comment by regisb** [comment]
Thanks again for investigating and reporting this bug @luisc09, good catch! I'll work on a fix.
