### ISSUE TITLE
MONGODB_HOST is not replaced in MONGOHQ_URL

### ISSUE THREAD

**Issue by luisc09** [overhangio/tutor#267]
**Bug description**
In Forum container, `MONGOHQ_URL` is not set properly set if you have overridden `MONGODB_HOST`. 

**How to reproduce**
Set a `MONGODB_HOST` in your `config.yml` and run services, run the following command to display all the environment variables, you will see that `MONGOHQ_URL` contains the values that as if `MONGODB_HOST` was set to `mongodb`

```
tutor local run forum env 
docker-compose -f /home/XXXX/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm forum env
Starting tutor_local_elasticsearch_1 ... done
Waiting for mongodb/elasticsearch...
2019/11/22 01:28:26 Waiting for: tcp://XXXX:27017
2019/11/22 01:28:26 Waiting for: http://XXXX/content
2019/11/22 01:28:26 Connected to tcp://XXXX:27017
2019/11/22 01:28:26 Received 200 from http://XXXX/content
MONGOHQ_URL=mongodb://mongodb:27017/cs_comments_service
BUNDLER_VERSION=1.11.2
HOSTNAME=8785a846cdaf
NEW_RELIC_ENABLE=false
MONGODB_AUTH=
HOME=/root
RUBY_VERSION=2.4.1
TERM=xterm
MONGODB_HOST=XXXX
RACK_ENV=staging
PATH=/openedx/bin:/openedx/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MONGODB_PORT=27017
RAKE_VERSION=10.4.2
API_KEY=forumapikey
SEARCH_SERVER=XXXX
PWD=/openedx/cs_comments_service
```

I believe that `MONGOHQ_URL` should be placed below this [line](https://github.com/overhangio/tutor/blob/master/tutor/templates/local/docker-compose.yml#L99) 

**Environment**
-Amazon Linux
-tutor, version 3.7.4

**Additional context**

**Comment by regisb** [comment]
Hi @luisc09! Thanks for reporting this bug and investigating it. This will be fixed in the next release (v3.8.0) which I hope to finalize today.
