### ISSUE TITLE
Remove indexcourses as tutor command

### ISSUE THREAD

**Issue by cacciaresi** [overhangio/tutor#269]
**Is your feature request related to a problem? Please describe.**
Its confusing to have _indexcourses_ as a specific management command for tutor, because users can think that t other management command should also exists (like refresh_course_metadata)

**Describe the solution you'd like**
Remove the command and add documentation on how to execute the same command using other tutor commands.

**Comment by cacciaresi** [comment]
We have a dependency on _import_demo_course_:

```
@click.command(help="Import the demo course")
@opts.root
def importdemocourse(root):
    config = tutor_config.load(root)
    runner = ScriptRunner(root, config)
    fmt.echo_info("Importing demo course")
    scripts.import_demo_course(runner)
    fmt.echo_info("Re-indexing courses")
    indexcourses.callback(root)
```

I was thinking that it was just removing the command and adding documentation on how to execute it like this:

`tutor local run cms ./manage.py cms reindex_course --all --setup`

but now that I see that is being used from _import_demo_course_ maybe we can keep it... what you you think @regisb?

**Comment by regisb** [comment]
> but now that I see that is being used from importdemocourse maybe we can keep it... what you you think @regisb?

We can remove it all.

**Comment by cacciaresi** [comment]
My initial though about this issue was that [indexcourses](https://github.com/overhangio/tutor/blob/master/tutor/templates/hooks/cms/indexcourses) could be replace with one line from the commandline and it was confusing to have this tutor command and not the rest.  But for [importdemocourse](https://github.com/overhangio/tutor/blob/master/tutor/templates/hooks/cms/importdemocourse) the template is actually executing more than one command, so it makes sense to have it.

Maybe by just adding some examples on how to execute different commands is enough.
