### ISSUE TITLE
tutor_local_cms_1 exited with code 3

### ISSUE THREAD

**Issue by OrionBytes** [overhangio/tutor#270]
**Bug description**

During different tutor local commands (after initial tutor local init) I've got -  
```
cms_worker_1      | SyntaxError: Non-ASCII character '\xd0' in file /openedx/edx-platform/cms/envs/tutor/production.py on line 53, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
tutor_local_cms_worker_1 exited with code 1
forum_1           | 2019/11/27 14:49:58 Received 404 from http://elasticsearch:9200/content. Sleeping 5s
forum_1           | 2019/11/27 14:50:03 Received 404 from http://elasticsearch:9200/content. Sleeping 5s
forum_1           | 2019/11/27 14:50:08 Received 404 from http://elasticsearch:9200/content. Sleeping 5s
tutor_local_cms_1 exited with code 3
```
How can I solve this issue? 
LMS seems to be working (at least I can access web, login, etc.) preview. works too, studio. gives Error 502
No changes from my side - just 

```
sudo curl -L "https://github.com/overhangio/tutor/releases/download/v3.8.0/tutor-$(uname -s)_$(uname -m)" -o /usr/local/bin/tutor
sudo chmod 0755 /usr/local/bin/tutor
tutor local init
```

on a fresh Ubuntu 18.04 VPS

**Environment**

tutor, version 3.8.0
Ubuntu 18.04, 
CPU: 2 Cores
Memory: 4 GB
Disk: 50 GB

**Comment by regisb** [comment]
Hi @OrionBytes! Can you tell me what's at line 53 of your production settings? You can get it in one command with:

    tail -n +53 $(tutor config printroot)/env/apps/openedx/settings/cms/production.py | head -1

**Comment by OrionBytes** [comment]
@regisb ah,
STUDIO_NAME = "Курсы - Studio"

You are right, probably russian here is an issue. My goal was to have localized name. Thanks!

**Comment by regisb** [comment]
It should be possible to support a localized studio name. Please keep this issue open and I'll try to figure out a solution.

**Comment by regisb** [comment]
This is reproduced by running:

    tutor config save --set=PLATFORM_NAME="Курсы - Studio
    tutor local start
