### ISSUE TITLE
The docs should point to the discuss forums for troubleshooting

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#274]
Currently, the [troubleshooting docs](https://docs.tutor.overhang.io/troubleshooting.html) suggest to create Github issues, when in fact users should probably discuss the issue first in the official Tutor forums.

We need to do a better job at pointing users in the right direction. Also, maybewe should have better signposts for the "troubleshooting" section.

**Comment by rmaunder** [comment]
Where are the 'the official Tutor forums' you mention above?

I have an minor issue / question which I'll drop here in case it's easy. I've just installed tutor v3.9.0 - which was a pretty smooth process (thanks). How can I tell what version of Open Ed X this is giving me? Is this something that can be configured or is Tutor tied to a specific Open Ed X release?

Thanks

**Comment by rmaunder** [comment]
Ok I can answer my first question at least: https://discuss.overhang.io/
