### ISSUE TITLE
Pulling access denied for Overhangio/openedx:3.8.0

### ISSUE THREAD

**Issue by kush11** [overhangio/tutor#279]
I am getting error when I run tutor dev runserver lms this was not there in the version 0f 3.7.4 when I updated to 3.8.0 I am getting the bellow error:
root@kali:~/Documents/tutor# tutor dev runserver lms
The lms service will be available at http://localhost:8000
docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml -f /root/.local/share/tutor/env/dev/docker-compose.yml --project-name tutor_dev run --rm -e SETTINGS=tutor.development -p 8000:8000 lms ./manage.py lms runserver 0.0.0.0:8000
Starting tutor_dev_mysql_1_9861b3493488         ... done
Starting tutor_dev_smtp_1_8b787838e455          ... done
Starting tutor_dev_elasticsearch_1_c4baabddd291 ... done
Starting tutor_dev_rabbitmq_1_2e1bf458482d      ... done
Starting tutor_dev_memcached_1_61725df5a77e     ... done
Starting tutor_dev_mongodb_1_bff19da243d2       ... done
Starting tutor_dev_forum_1_91d2d47af9a9         ... done
Pulling lms (overhangio/openedx-dev:3.8.0)...
ERROR: pull access denied for overhangio/openedx-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: Command failed with status 1: docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml -f /root/.local/share/tutor/env/dev/docker-compose.yml --project-name tutor_dev run --rm -e SETTINGS=tutor.development -p 8000:8000 lms ./manage.py lms runserver 0.0.0.0:8000

**Comment by ak00001** [comment]
Try posting help requests in this forum: https://discuss.overhang.io/

And for your problem, you probably need to rebuild the dev image. Run 
`tutor images build openedx-dev`

**Comment by shashikiranraifox** [comment]
Regis,
     I run the above command but the process seems to be stuck(for nearly  4 hrs) at creating the user. 

Below is my build log:


```
Building image docker.io/overhangio/openedx-dev:3.12.3
docker build -t docker.io/overhangio/openedx-dev:3.12.3 Sending build context to Docker daemon  5.632kB
Step 1/11 : FROM docker.io/overhangio/openedx:3.12.3
 ---> 4e83d402b431
Step 2/11 : MAINTAINER Overhang.io <contact@overhang.io>
 ---> Using cache
 ---> ab86cbe8487e
Step 3/11 : RUN apt update &&     apt install -y vim telnet     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 6cdbaa38645e
Step 4/11 : RUN pip install -r requirements/edx/development.txt
 ---> Using cache
 ---> 39e71c2bff12
Step 5/11 : RUN pip install ipdb==0.12.2 ipython==5.8.0
 ---> Using cache
 ---> 014cec4bd517
Step 6/11 : RUN rm -r /openedx/staticfiles &&     mkdir /openedx/staticfiles &&     openedx-assets webpack --env=dev
 ---> Using cache
 ---> 752e39197dfd
Step 7/11 : COPY ./bin /openedx/bin
 ---> Using cache
 ---> ccb0d4bf5d2a
Step 8/11 : RUN chmod a+x /openedx/bin/*
 ---> Using cache
 ---> 8fd152d4cbca
Step 9/11 : ARG USERID=1000
 ---> Using cache
 ---> dc04a982062b
Step 10/11 : RUN create-user.sh $USERID




 ---> Running in e6215f4a433c
Creating 'openedx' user with id 1000


```
> Try posting help requests in this forum: https://discuss.overhang.io/
> 
> And for your problem, you probably need to rebuild the dev image. Run
> `tutor images build openedx-dev`
