### ISSUE TITLE
Missing information in docs/dev.rst

### ISSUE THREAD

**Issue by ak00001** [overhangio/tutor#280]
It's my understanding that after the first time you add a theme folder, you'll have to rebuild the openedx image by running `tutor images build openedx`. The documentation on theming doesn't mention this.

**Comment by cacciaresi** [comment]
Hi! I think that the documentation mention that here: https://docs.tutor.overhang.io/configuration.html?highlight=themes#adding-custom-themes.

**Comment by ak00001** [comment]
I know. But it's missing in the dev section. Just thinking it would be good
to cross-reference these.

tor. 16. jan. 2020 kl. 14:05 skrev Claudio Acciaresi <
notifications@github.com>:

**Comment by regisb** [comment]
Hi @ak00001! In development mode the `themes` folder is mounted inside the docker container, so it should not be required to re-build the image. However, you might have to update the assets:

    tutor dev run lms paver update_assets --settings=tutor.development
    tutor dev run cms paver update_assets --settings=tutor.development

Is that what's missing from the docs?
