### ISSUE TITLE
SSL/TLS certificate renewal should not require a restart of nginx.

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#282]
I don't know exactly how to implement that, but it's a problem that nginx needs to be restarted in order for the https certificate renewal to take place. This simple operation should not create any downtime.

**Comment by cacciaresi** [comment]
@regisb I think that for the let's encrypt case we may be able to use this (or something like that): https://certbot.eff.org/docs/using.html#webroot here https://github.com/overhangio/tutor/blob/6716668ff9c75c2cf8c07f24eb5df33c3e744677/tutor/commands/local.py#L136

**Comment by regisb** [comment]
This is now resolved thanks to Caddy which generates SSL/TLS certificates on-the-fly at runtime.
