### ISSUE TITLE
400 error during sign in on Android app

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#289]
**Bug description**

See https://discuss.overhang.io/t/sign-in-error-in-android-app/294/2

During sign in, the Android app is making a GET request to /oauth2/access_token which is not supported: `{“error_description”: “Only POST requests allowed.”, “error”: “invalid_request”}`

What is probably happening is that the master branch of the Android app is no longer compatible with the Ironwood release. We should pin the Android app repo during checkout.

**Comment by mindrunner** [comment]
Would like to see this fixed soon. I am happy to prepare the PR. However, it is unclear which part of the Android app is ironwood compatible. There is a lot of branches and tags, but I could not find any documentation about those. Do you have any idea? Or shall we cross post another ticket in the Android Repo?

**Comment by regisb** [comment]
> Would like to see this fixed soon. 

I understand.

> I am happy to prepare the PR. However, it is unclear which part of the Android app is ironwood compatible.

That's precisely the problem (and the reason why we were building on top of master). The Android app was supposed to be backward-compatible, but apparently it isn't. The Android app used to work a couple months ago, so I suggest you try out the latest tags, in decreasing order, and stop at the tag which works for you. As soon as you tell me which tag works, I can fix the issue or merge your PR.

**Comment by mindrunner** [comment]
Hi,
what is the best workflow for me to test this?

- Change branch in ~/.local/share/tutor/env/build/android/Dockerfile
- Build new image from that file (`docker build -t openedx-android-ironwood .`)
- run `docker run --rm -it --volume=~/.local/share/tutor/env/android:/openedx/config/ --volume=~/.local/share/tutor/data/android:/openedx/data/ openedx-android-ironwood`

**Comment by regisb** [comment]
Almost!

Building the image should be done with: `tutor images build android`. Then, you can build the image with `tutor android build`.

**Comment by regisb** [comment]
@mindrunner The android app is now built from the openrelease/ironwood.1 tag.

**Comment by mindrunner** [comment]
Cool, can I just rebuild the android app or do I need to update tutor itself before?

**Comment by mindrunner** [comment]
Hi @regisb 
Can you please follow this thread: https://github.com/edx/edx-app-android/issues/1372
The tag you are using is supposed to be outdated. Please use `open-release/ironwood.master` branch, as mentioned there.

Also in `~/.local/share/tutor/env/android/tutor.yaml` my `API_HOST_URL` variable is set to `http://....` I think this should use `https` by default, right?

**Comment by mindrunner** [comment]
One more update. I can confirm that `master` branch indeed works. The problem was/is the `API_HOST_URL` set to `http`. I am not sure if it is the fault of my custom reverse proxy setup or a general issue. However, using `https` directly AND using `master` branch works fine here.

**Comment by regisb** [comment]
> The tag you are using is supposed to be outdated. Please use open-release/ironwood.master branch, as mentioned there.

I'd rather not follow a branch, but a fixed tag.

> The problem was/is the API_HOST_URL set to http

This is supposed to be set to "https" when ACTIVATE_HTTPS=true. 

> However, using https directly AND using master branch works fine here.

Do you mean the ironwood.master or the master branch?

**Comment by mindrunner** [comment]
Ok, thank you. 

> Do you mean the ironwood.master or the master branch?

using master branch works fine here
