### ISSUE TITLE
Setting course structure timeout in Site Configuration not working

### ISSUE THREAD

**Issue by shashikiranraifox** [overhangio/tutor#297]
In the Admin Console, I am using Site Configuration Model to ensure the Course Structure API Cache is  0 . However the Course structure API is not returning course content that is published.

If i restart memcached as mentioned in #64 , the new content is visible.  It's a similar issue to previously opened bug however  I wanted to know if my JSON is correct. Apologize in Advance if this issue did not suffice opening a new bug

Below are my Site Configuration JSON

```
{
  "SITE_NAME": "something.edx.com",
  "BOOK_URL": "",
  "LOG_DIR": "/openedx/data/logs",
  "LOGGING_ENV": "sandbox",
  "OAUTH_OIDC_ISSUER": "http://localhost:8000/oauth2",
  "PLATFORM_NAME": "Example",
  "FEATURES": {
    "PREVIEW_LMS_BASE": "preview.www.myopenedx.com"
  },
  "LMS_ROOT_URL": "http://www.myopenedx.com",
  "CMS_ROOT_URL": "http://something.edx.com",
  "CMS_BASE": "something.edx.com",
  "LMS_BASE": "www.myopenedx.com",
  "CELERY_BROKER_HOSTNAME": "rabbitmq",
  "CELERY_BROKER_TRANSPORT": "amqp",
  "MEDIA_ROOT": "/openedx/data/uploads/",
  "STATIC_ROOT_BASE": "/openedx/data/staticfiles",
  "ELASTIC_SEARCH_CONFIG": [{
    "host": "elasticsearch",
    "port": 9200
  }],
  "EMAIL_BACKEND": "django.core.mail.backends.smtp.EmailBackend",
  "EMAIL_HOST": "smtp",
  "CACHES": {
    "default": {
      "KEY_PREFIX": "default",
      "VERSION": "1",
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    },
    "general": {
      "KEY_PREFIX":  "general",
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    },
    "mongo_metadata_inheritance": {
      "KEY_PREFIX": "mongo_metadata_inheritance",
      "TIMEOUT": 300,
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    },
    "staticfiles": {
      "KEY_PREFIX": "staticfiles_general",
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    },
    "configuration": {
      "KEY_PREFIX": "configuration",
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    },
    "celery": {
      "KEY_PREFIX":  "celery",
      "TIMEOUT": "7200",
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    },
    "course_structure_cache": {
      "KEY_PREFIX": "course_structure",
      "TIMEOUT": 0,
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    }
  }
}
```

**Comment by regisb** [comment]
Hi @shashikiranraifox! I'm not entirely sure that a timeout of 0 will disable the cache -- maybe it keeps the value in the cache forever instead. Can you please try with timeout=1? Note that you will have to change the value both in the lms.env.json and cms.env.json files.

**Comment by shashikiranraifox** [comment]
Hi @regisb . Thanks for the suggestion.  I have changed value in both the files as you have suggested. Below is how it looks now

>   "course_structure_cache": {
>       "KEY_PREFIX": "course_structure",
>       "TIMEOUT": 1,
>       "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
>       "KEY_FUNCTION": "util.memcache.safe_key",
>       "LOCATION": "memcached:11211"
>     }
> 

Even then the issue[If I add new sections and units to the course, it does not come up immediately even if published] still remains.  Are they are other places, I have to reduce the timeout.

**Comment by shashikiranraifox** [comment]
@regisb 
I found the solution to this. We had to remove the docker images of cms_worker and lms_worker and then freshly build it. Probably the config files(env files) get applied when the image itself is built or the docker container must have been immutable for these config files.

p.s: The better solution would have been if adding a Site configuration in the Django admin could have been applied. But that seems not to work.

With regards,
Shashi Kiran G M

**Comment by regisb** [comment]
> I found the solution to this. We had to remove the docker images of cms_worker and lms_worker and then freshly build it. Probably the config files(env files) get applied when the image itself is built or the docker container must have been immutable for these config files.

This is not the case. The config files are update with `tutor config save` and bind-mounted inside the containers at runtime.
