### ISSUE TITLE
Installation docs should warn prominently that 4Gb of RAM are needed for Docker

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#299]
Too many Mac OS users end up with a crash occurring during the mysql database migrations (see https://github.com/overhangio/tutor/issues/286). Installation docs should more prominently display a warning. Also, we should give explanations on how to get rid of the corrupt database.

**Comment by dyatko** [comment]
Or even 5Gb in my case :-)

**Comment by regisb** [comment]
Also, we should probably explain how to get rid of a corrupt MySQL database, as detailed in this comment: https://github.com/overhangio/tutor/issues/286#issuecomment-592943708
