### ISSUE TITLE
Cannot settheme for dev on localhost:8000

### ISSUE THREAD

**Issue by PavlosIsaris** [overhangio/tutor#303]
**Bug description**

I have a tutor installation, and I would like to set a theme for development so that I can start customizing it.
I am trying these steps:

```
tutor dev runserver lms
```

Here I get the following output:
```
Starting tutor_dev_mongodb_1 ... done
Starting tutor_dev_memcached_1     ... done
Starting tutor_dev_memcached_1 ... 
Starting tutor_dev_elasticsearch_1 ... done
Starting tutor_dev_smtp_1          ... done
Starting tutor_dev_rabbitmq_1      ... done
Starting tutor_dev_forum_1         ... done
Setting file permissions for user openedx...
File permissions set.

```
As you can see, there is no `tutor_dev_lms_1` starting...
However, I am able to access the LMS via localhost:8000.

I then open a new terminal (while the `tutor dev runserver lms` process is running), and try to set my theme (as the [tutorial](https://docs.tutor.overhang.io/dev.html#customised-themes) suggests):

```
tutor dev settheme red-theme localhost:8000
```

But here I get the following error:

```
ERROR: No container found for lms_1
Error: Command failed with status 1: docker-compose -f /home/paul/.local/share/tutor/env/local/docker-compose.yml -f /home/paul/.local/share/tutor/env/dev/docker-compose.yml --project-name tutor_dev exec lms sh -e -c 
export DJANGO_SETTINGS_MODULE=$SERVICE_VARIANT.envs.$SETTINGS
echo "Loading settings $DJANGO_SETTINGS_MODULE"

echo "Assigning theme red-theme to localhost:8000..."
./manage.py lms shell -c "
from django.contrib.sites.models import Site
site, _ = Site.objects.get_or_create(domain='localhost:8000')
if not site.name:
    site.name = 'localhost:8000'
    site.save()
site.themes.all().delete()
site.themes.create(theme_dir_name='red-theme')"

```

What should I do?

**How to reproduce**

```
tutor dev runserver lms

#open new terminal

tutor dev settheme red-theme localhost:8000
```

**Environment**

System: Ubuntu 18.04
tutor vesrion:  3.11.6
docker-compose version: 1.25.4, build 8d51620a

**Additional context**

If I run the `settheme` command, but with `local` instead of `dev`, it works as expected (sets the theme correctly).
The problem with `local` is that I cannot run the `watchthemes` command.

**Comment by carlos-wong** [comment]
@regisb I think the run command of docker-compose is cause of this issue. See https://github.com/docker/compose/issues/6549

**Comment by PavlosIsaris** [comment]
The solution was to run (note the use of `dev` instead of `local`:

```bash
tutor dev start
```

**Comment by regisb** [comment]
Good job investigating this yourself @PavlosIsaris :) The behaviour of the `dev settheme` command (and all other init commands) will be improved in the next release.

**Comment by maharanavikas** [comment]
I want to see my custom themes in tutor local but the tutor local run watchthemes is not working. It's giving no such service: watchthemes
