### ISSUE TITLE
Tutor not quite as easy as advertised on Ubuntu

### ISSUE THREAD

**Issue by frohro** [overhangio/tutor#304]
Hi Regis,
I made a brand new install of Ubuntu 20.04.  In order to get tutor to work, I did three things:

- sudo apt install docker docker-compose curl
- sudo usermod -aG docker $USER

Then I could follow your instructions in the docs.  If you like I could create a .rst file for Ubuntu, or modify the one you have.  I think yours is probably set up for the cloud where some of these things are done for you already.

Thanks,

Rob

**Comment by regisb** [comment]
Hi @frohro! I tried to clarify the docs as best as I could in the latest release, and they will make it clearer how to install docker/docker-compose along with tutor.
