### ISSUE TITLE
Installation: Error at firewall setup process

### ISSUE THREAD

**Issue by tr37ion** [overhangio/tutor#307]
**Bug description**

Starting installation process `sudo tutor local quickstart` results in error:
```
docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local up --remove-orphans -d
Creating network "tutor_local_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-c854eadecc47 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
Error: Command failed with status 1: docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local up --remove-orphans -d
```

**How to reproduce**

```
$ sudo tutor local quickstart
```
**Environment**

Other docker images already running and firewall is already configured on this system.
```
Linux abs.server.net 4.19.97-1-lts #1 SMP Fri, 17 Jan 2020 23:09:48 +0000 x86_64 GNU/Linux
```
**Additional context**

Nothing special to add. Firewall is running and other docker images are running just fine. No changes done except for
```
$ export LANG=en_US.UTF-8  
$ export LC_ALL=en_US.UTF-8
```

**Comment by tr37ion** [comment]
Where can I find the setup script to remove the firewall config?

**Comment by regisb** [comment]
Hi @tr37ion! There is an error with your firewall. Unfortunately, I am not in a capacity to help you disable it. You should note that setting up firewalls with docker is tricky. See for instance this question I asked a while ago on StackOverflow: https://stackoverflow.com/questions/54769872/iptables-with-docker-port-mapping/54795204

Also, you should not be running Tutor with sudo. See the explanation here: https://github.com/overhangio/tutor/commit/cf041568d0aabae08d1c3dd7129508fb2d64a1a1#diff-4f31c1e2c9e43e4d6edbcd36ed58f8b8R43
