### ISSUE TITLE
Integrating nbviewer

### ISSUE THREAD

**Issue by awantik** [overhangio/tutor#309]
Loved openedx & more with tutor. I am trying to convince my team for adopting openedx & drop other LMS. One important feature that will make this easy is integrating nbviewer. I am new to both openedx & tutor. Is this issue resolved? Pls share with me the steps.
I am getting this error
![Screenshot from 2020-04-01 19-18-54](https://user-images.githubusercontent.com/19047368/78144788-b1a66f80-744d-11ea-8dc5-0e07238c9fce.png)

**Comment by regisb** [comment]
Hi @awantik! nbviewer is currently not supported out of the box in Open edX, so it's also not compatible with Tutor. As I mentioned [elsewhere](https://github.com/overhangio/tutor/issues/84#issuecomment-607422652), I could dedicate some time to creating a new XBlock and a tutor plugin to easily deploy it, but that would need some financial backing.
