### ISSUE TITLE
request update to last update branch

### ISSUE THREAD

**Issue by mohammad-chavoshipor** [overhangio/tutor#312]
Please update to the latest branch
Need a mobile field in the last commit 
[phone field](https://github.com/edx/edx-platform/commit/80320ab7a023fe45ae08a033e24f462abfef99f0)

**Comment by regisb** [comment]
Unfortunately I cannot upgrade edx-platform to the latest relase, as it is incompatible with Ironwood. You are welcome to run tutor with your own fork of edx-platform that includes the above commit. Please check the docs to learn how to do so: https://docs.tutor.overhang.io/configuration.html#running-a-fork-of-edx-platform

**Comment by mohammad-chavoshipor** [comment]
> Unfortunately I cannot upgrade edx-platform to the latest relase, as it is incompatible with Ironwood. You are welcome to run tutor with your own fork of edx-platform that includes the above commit. Please check the docs to learn how to do so: https://docs.tutor.overhang.io/configuration.html#running-a-fork-of-edx-platform


Thanks a lot
Is it possible to add the Userinfo field model and rewrite the registration form?
I did this but it didn't work!
https://github.com/open-craft/custom-form-app/tree/master/custom_reg_form

You can guide me so I can add fields to the registration page and files
RegisterModel.js
And ..
Rewrite?
