### ISSUE TITLE
How can I install tutor with Open edx ginkgo version with its devstack.

### ISSUE THREAD

**Issue by ciskshitij** [overhangio/tutor#313]
How can I install tutor with Open edx ginkgo version with its devstack.

**Comment by regisb** [comment]
You can't. Tutor is compatible with Ironwood; it used to be compatible with Hawthorn (prior to v3), but did not exist at the time of Ginkgo. Please don't use Github issues to ask questions. Instead, head to the official forums: discuss.overhang.io
