### ISSUE TITLE
Support terminating SSL before outside fo nginx

### ISSUE THREAD

**Issue by dariothornhill** [overhangio/tutor#327]
In my setup we have a load balancer which does all the HTTPS and forwards to nginx on port 80

I've noticed that if i set ACTIVATE_HTTPS: false it changes my external https link to http in the application configs and when set to true it removed nginx port 80 and adds Let's Encrypt.

This is a problem because our SSL is terminated at a load balancer which has the certificate installed and routes traffic to nginx over HTTP.

I would like to be able to configure tutor to use HTTPS links in combination with port 80 in nginx and no let's encrypt, without having to manually edit them after each time I run tutor config save.

**Comment by regisb** [comment]
Hi @dariothornhill! Please read this: https://docs.tutor.overhang.io/local.html#running-open-edx-behind-a-web-proxy

**Comment by dariothornhill** [comment]
I've read this again and WEB_PROXY is set to true and I already have custom ports for the nginx container. The SSL is also already taken care of elsewhere specifically at the load balancer which routes to nginx container port 80.

It's not clear to me how this will prevent the generation of http instead of https based links when I next run tutor config save. Can you provide a bit more detail on what I have have missed in the reading?

**Comment by regisb** [comment]
In this setup, you should keep `ACTIVATE_HTTPS: true`.
