### ISSUE TITLE
ERROR: Package 'tutor-openedx' requires a different Python: 2.7.12 not in '>=3.5'

### ISSUE THREAD

**Issue by Djas2017** [overhangio/tutor#331]
**Bug description**
I am following the instructions described in this installation tutorial https://docs.tutor.overhang.io/install.html and getting the error: <<ERROR: Package 'tutor-openedx' requires a different Python: 2.7.12 not in '>=3.5'>>

`# pip install -e .
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///root/OpenedX-Tutor/tutor
ERROR: Package 'tutor-openedx' requires a different Python: 2.7.12 not in '>=3.5'`

**How to reproduce**
See above.
`# pip install -e .`

**Environment**
Installing on Ubuntu server 
`# cat /etc/issue
Ubuntu 16.04.6 LTS`

`# python -V
Python 2.7.12`

`# python3 --version
Python 3.5.2`
**Additional context**
N/A

**Comment by regisb** [comment]
As instructed, you need python 3.6 or greater to install tutor-openedx from source: https://docs.tutor.overhang.io/install.html#from-source

You can try your luck with `pip3 install tutor-openedx` instead.
