### ISSUE TITLE
tutor v3.12.5 - Ecommerce v0.1.13 showing "Server Error"

### ISSUE THREAD

**Issue by createinnovative** [overhangio/tutor#332]
**Bug description**
A message "Server Error" is showing on the ecommerce site at ecommerce.mydomain.com . That same error is also showing at ecommerce.mydomain.com/accounts/profile/

I am able to login into the ecommerce site but the urls mentioned above are showing an error so no information is being displayed.

** `tutor local logs lms --tail=100` ** on ecommerce.mydomain.com/accounts/profile/ is showing:

ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
ecommerce_1         |     return self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
ecommerce_1         |     return compiled_parent._render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
ecommerce_1         |     return self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
ecommerce_1         |     return compiled_parent._render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
ecommerce_1         |     return self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
ecommerce_1         |     result = block.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
ecommerce_1         |     result = block.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 216, in render
ecommerce_1         |     return template.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
ecommerce_1         |     return self._render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
ecommerce_1         |     return self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
ecommerce_1         |     result = self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
ecommerce_1         |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/urls/base.py", line 87, in reverse
ecommerce_1         |     raise NoReverseMatch("%s is not a registered namespace" % key)
ecommerce_1         | NoReverseMatch: u'catalogue' is not a registered namespace

**How to reproduce**
I followed all the steps in the documentation to enable the ecommerce plugin

tutor plugins enable discovery ecommerce
tutor config save
tutor local quickstart

**Environment**
Ubuntu 18.04 and the Tutor version v3.12.5

**Comment by createinnovative** [comment]
**tutor local logs --tail=100 ecommerce** on ecommerce.mydomain.com is showing

ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
ecommerce_1         |     return compiled_parent._render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
ecommerce_1         |     return self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
ecommerce_1         |     return compiled_parent._render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
ecommerce_1         |     return self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
ecommerce_1         |     result = block.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
ecommerce_1         |     result = block.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 216, in render
ecommerce_1         |     return template.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
ecommerce_1         |     return self._render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
ecommerce_1         |     return self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
ecommerce_1         |     result = self.nodelist.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
ecommerce_1         |     bit = node.render_annotated(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
ecommerce_1         |     return self.render(context)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
ecommerce_1         |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
ecommerce_1         |   File "/openedx/venv/local/lib/python2.7/site-packages/django/urls/base.py", line 87, in reverse
ecommerce_1         |     raise NoReverseMatch("%s is not a registered namespace" % key)
ecommerce_1         | NoReverseMatch: u'catalogue' is not a registered namespace
ecommerce_1         | 2020-05-24 16:52:49,011 WARNING 147 [django.request] /openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py:152 - Not Found: /
ecommerce_1         | 2020-05-24 16:52:49,011 WARNING 147 [django.request] /openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py:152 - Not Found: /
ecommerce_1         | 2020-05-24 16:52:49,011 WARNING 147 [django.request] /openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py:152 - Not Found: /

**Comment by regisb** [comment]
Hi @createinnovative! Can you please move this issue to https://pypi.org/project/tutor-ecommerce/issues ?

**Comment by createinnovative** [comment]
Okay i will do so. Thanks
