### ISSUE TITLE
Change top left logo 

### ISSUE THREAD

**Issue by adesrod** [overhangio/tutor#333]
First at all, I know it's a silly question but I have to do it, I need your help to found the way to change the logo in the platform (top left), I've tried many ways but still I haven’t figured out how to do it. The version of tutor is 3.11.12. Thanks for your time.

**Comment by regisb** [comment]
Hi @adesrod! Please don't ask support questions here. Instead, move to the official forums: https://discuss.overhang.io

Also, please read https://docs.tutor.overhang.io/troubleshooting.html
