### ISSUE TITLE
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)

### ISSUE THREAD

**Issue by Djas2017** [overhangio/tutor#334]
**Bug description**
I am getting the error:

```
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)

Warning: Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
    [8/10] Waiting for MySQL service (this may take a while)...
...
```

Followed instructions in https://discuss.overhang.io/t/tutor-local-start-cant-work-mysql-issue/67 but same issue!

```
tutor local stop
sudo rm -rf $(tutor config printroot)/data/mysql
tutor local quickstart
```

**How to reproduce**
Followed the instructions and the last command executed:
`tutor local quickstart`

**Environment**
```
# cat /etc/issue
Ubuntu 20.04 LTS

#docker-compose --version
docker-compose version 1.25.5

# docker --version
Docker version 19.03.9, build 9d988398e7
```

**Additional context**
N/A

**Comment by regisb** [comment]
@Djas2017 can you please attempt to upgrade to the latest release (v3.12.6) and see if it works for you?

**Comment by tuanh118** [comment]
I fixed this issue by increasing Docker Memory to 5GB (4GB is not enough)

See here for more info https://docs.tutor.overhang.io/troubleshooting.html#running-migrations-killed-command-failed-with-status-137-docker-compose

**Comment by Pt0lemaeus** [comment]
how to increasing docker memory in a vitural box linux ?
