### ISSUE TITLE
Suggestion: single-level domain names as default to avoid SSL/TLS complications

### ISSUE THREAD

**Issue by opyh** [overhangio/tutor#336]
I've just completed a k8s test installation of this project, and I'm delighted how easy you made deploying such a complex system. Kudos!

Here is a suggestion to save some people time.

### What happened / current state

The Tutor installer creates sub-sub-domains per default, e.g., `studio.academy.mydomain.com` and `preview.academy.mydomain.com`. This didn't work with my wildcard cert `*.mydomain.com`. SSL error messages can be very cryptic, even if you are experienced, and can make such an issue difficult to find.

If you have a `*.mydomain.com` wildcard certificate,

- This hostname works: `academy.mydomain.com`
- Hist hostname does not work: `studio.academy.mydomain.com` (as the domain name does not match `*.mydomain.com`)

### Suggestion / potential fix

For generating the `preview` and `studio` hostnames: 

- remove the TLD + SLD part from the entered domain (`mycourses.mycompanyname.co.uk` → `mycourses.mycompanyname`)
- if the rest of the domain name has a dot, join the hostname using a dash instead of a dot (so the studio hostname would be `mycourses-studio.mycompanyname`, not `studio.mycourses.mycompanyname`)

This is just a suggestion that might save some people hours of debugging, especially if they're not advanced. You might have good arguments against this idea - in this case, feel free to close this issue :)

### Context

Many people use platforms with built-in wildcard certificate support.

### For poor souls finding this issue via Google…

Here is a checklist to debug SSL termination in k8s:

- Check that the DNS entry actually points to your ingress controller IP and not somewhere else: `nslookup studio.mydomain.com`. If the IP is wrong, it might not have propagated yet (you can check this with [DNSChecker](https://dnschecker.org)). If your ingress IP is `1.2.3.4` and your DNS `A` record actually points to `1.2.3.4`, but the entry hasn't propagated to your local nameservers yet, you can add a `--resolve studio.mydomain.com:443:1.2.3.4` parameter to `curl` to force `curl` to talk to the correct IP of your ingress controller.
- Install [`stern`](https://github.com/wercker/stern), run `stern '.*' -n openedx` and `stern '.*' -n MY_INGRESS_CONTROLLER_NAMESPACE` in parallel while trying the next steps.
- Try `curl --head -vvv https://studio.mydomain.com` to find out if the ingress controller responds
- If you get an SSL-related error message, try `curl --head -vvv --insecure https://studio.mydomain.com` to find out **which** SSL certificate your server returns
- If you get something like `SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`, the certificate domain likely doesn't match your app's domain.
- Compare the SSL certificate's domain name with your expected domain name. It should match.
- If the ingress controller gives you a fake certificate or the default certificate but not the one for your domain name, check that your `Ingress` resource rule has a `host` and that it is correct.
- You can get very detailed infos about the certificates that your server sends by running this command: `openssl s_client -connect studio.mydomain.com:443 -servername studio.mydomain.com | openssl x509 -noout -text`

Maybe this saves somebody ;)

**Comment by regisb** [comment]
Hi @opyh! Thanks a lot for the detailed information, I appreciate it. I must say that I'm not so keen to modify the default studio hostname. The change you propose makes sense, especially for your use case, but the naming scheme is more difficult to explain to non-technical users.

However, I would like to help people facing the same issue as you to detect the underlying issue more easily. Until now I've considered custom certificates as an advanced requirement and so I did not care to give too much support to those users. Your comment makes me rethink this. Is there any way we can help users detect the problem earlier? What error message were you facing? Did you face certificate errors in your browser, or on the backend? It would be great if you could paste those error messages in your first issue comment.

**Comment by opyh** [comment]
Sorry, I don't have the original error messages anymore. The first visible error happens in a browser, depending on the situation you either see something indifferent like "can't connect to server", or a security error.

I think that explicit support for custom certs is really outside of your scope, as it can be so tricky and is very dependent on your specific ingress setup. Supporting all variants officially would be tedious distraction from building what makes your project unique.

I assume most operators that want to install Tutor in an existing cluster have a running SSL ingress setup already. For everybody else, a standard ingress TLS setup with cert-manager + nginx would be sufficient.

In a perfect world, the command line tool could theoretically recognize the most common situations, as it has access to k8s resources:

- DNS not propagated
- DNS propagated, but no HTTP response (-> compare IP with existing ingress IPs)
- `openssl s_client -connect 1.2.3.4:443 -servername studio.mydomain.com | openssl x509 -noout -text` delivers no cert or cert with wrong Common Name (CN)
- Ingress delivers a certificate that is not from LetsEncrypt or root CA signed
- No ingress configuration exists
- Ingress configuration points to a wrong internal hostname or port

Would make for an awesome generic tool not only for Tutor, if I had the time I'd already implement it ;)

Feel free to close this issue though!
