### ISSUE TITLE
paver update_assets errors

### ISSUE THREAD

**Issue by thanhlongtld** [overhangio/tutor#337]
When I try to run paver update_assets --settings=tutor.development, I get the following error. I don't know how to fix it. Please help me!

openedx@8b5652489502:~/edx-platform$ paver update_assets --settings=tutor.development
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
---> pavelib.assets.process_xmodule_assets
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
NO_PYTHON_UNINSTALL is set. No attempts will be made to uninstall old Python libs.
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/development.txt
xmodule_assets common/static/xmodule
		Finished processing xmodule assets.
mkdir_p path('common/static/common/js/vendor')
mkdir_p path('common/static/common/css')
mkdir_p path('common/static/common/css/vendor')
Copying vendor files into static directory

Captured Task Output:

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_node_prereqs
---> pavelib.assets.process_xmodule_assets
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/development.txt
xmodule_assets common/static/xmodule
mkdir_p path('common/static/common/js/vendor')
mkdir_p path('common/static/common/css')
mkdir_p path('common/static/common/css/vendor')
Traceback (most recent call last):
  File "/openedx/venv/local/lib/python2.7/site-packages/paver/tasks.py", line 201, in _run_task
    return do_task()
  File "/openedx/venv/local/lib/python2.7/site-packages/paver/tasks.py", line 198, in do_task
    return func(**kw)
  File "pavelib/utils/timer.py", line 39, in timed
    return wrapped(*args, **kwargs)
  File "pavelib/assets.py", line 939, in update_assets
    process_npm_assets()
  File "pavelib/assets.py", line 641, in process_npm_assets
    copy_vendor_library(library)
  File "pavelib/assets.py", line 612, in copy_vendor_library
    raise Exception('Missing vendor file {library_path}'.format(library_path=library_path))
Exception: Missing vendor file node_modules/backbone.paginator/lib/backbone.paginator.js

**Comment by regisb** [comment]
Are you mounting an edx-platform repository from the host? You almost certainly need to install nodejs dependencies. Please run `npm install` prior to updating the assets.

Please do not open a Github issue for asking for help. Instead, please go to the official Tutor forums: https://discuss.overhang.io/
