### ISSUE TITLE
Docker manifest unknown when doing local quickstart from Web UI

### ISSUE THREAD

**Issue by mihaiplesa** [overhangio/tutor#343]
**Bug description**

When upgrading from Ironwood am getting the following:
```
ERROR: manifest for localhost:5000/overhangio/openedx:10.0.1 not found: manifest unknown: manifest unknown
```

**How to reproduce**

Do `local quickstart` inside the web UI.
Have tried setting DOCKER_REGISTRY and TUTOR_DOCKER_REGISTRY to `docker.io/` but `local quickstart` seems to overwrite that.

**Environment**

Using the Tutor AWS AMI at https://aws.amazon.com/marketplace/pp/Overhangio-Tutor/B07PV3TB8X (v3.11.8)

**Additional context**

**Comment by regisb** [comment]
Hi @mihaiplesa! Did you try to unset the `DOCKER_REGISTRY`? From the web UI:

    config save --unset DOCKER_REGISTRY

Then:

    local quickstart

If it doesn't work, then it means we got a caching issue on our hands...

**Comment by mihaiplesa** [comment]
Hi @regisb, thank you for the quick reply. Have just retried:

```
> config printvalue DOCKER_REGISTRY                                                                                                                                                                            
localhost:5000/
> config save --unset DOCKER_REGISTRY                                                                                                                                                                          
Configuration saved to /home/tutor/.local/share/tutor/config.yml
Environment generated in /home/tutor/.local/share/tutor/env
> config printvalue DOCKER_REGISTRY                                                                                                                                                                            
localhost:5000/
````

Still doesn't pick the change and fails on `local quickstart`.

**Comment by regisb** [comment]
Ok so we definitely have a caching issue with the webui addon. Please try the following:

1. Run `config save --unset DOCKER_REGISTRY` from the web UI
2. Refresh the page (with F5)
3. Run `config printvalue DOCKER_REGISTRY`

**Comment by mihaiplesa** [comment]
Same result unfortunately. Have tried different tutor versions from a few v3 the latest v10.0.1.

**Comment by regisb** [comment]
Right. I now understand what is going on. Are you able to ssh into the server? You need to edit the file in `/etc/systemd/system/tutor-webui.service` and remove the line `Environment=TUTOR_DOCKER_REGISTRY=localhost:5000/`. Then, run:

```
sudo systemctl daemon-reload
sudo systemctl restart tutor-webui
```

This custom docker registry is a PITA that was imposed by AWS. We need to find a way to improve the docker registry to automatically pull from docker.io when the images are not present on the server.

**Comment by regisb** [comment]
> This custom docker registry is a PITA that was imposed by AWS. We need to find a way to improve the docker registry to automatically pull from docker.io when the images are not present on the server.

I found a way to achieve that. On the server, run:

```
docker stop docker_registry
docker rm docker_registry
docker run -d -p 5000:5000 --restart=always --name docker_registry -e REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io docker.io/registry:2.7.1
```

This change will be included in future versions of the AMI.

**Comment by mihaiplesa** [comment]
Was just trying `tutor local quickstart` via SSH using `tutor` user and gets stuck at:

```
Waiting for mongodb/elasticsearch...
2020/06/17 10:26:28 Waiting for: tcp://mongodb:27017
2020/06/17 10:26:28 Waiting for: http://elasticsearch:9200
2020/06/17 10:26:28 Problem with dial: dial tcp: lookup mongodb on 127.0.0.11:53: no such host. Sleeping 5s
2020/06/17 10:26:28 Received 200 from http://elasticsearch:9200
2020/06/17 10:26:33 Problem with dial: dial tcp: lookup mongodb on 127.0.0.11:53: no such host. Sleeping 5s
```

From `mongo` container logs:
```
IMPORTANT: UPGRADE PROBLEM: The data files need to be fully upgraded to version 3.4 before attempting an upgrade to 3.6; see http://dochub.mongodb.org/core/3.6-upgrade-fcv for more details.
```

**Comment by regisb** [comment]
> This is a separate thing now, happy to rename this issue if we want it to be generic about upgrade to v10 on the AWS AMI.

Indeed, this is a separate issue. Run `tutor local upgrade --from=ironwood` and if it does not resolve your issue, please open a new topic on the discussion forums: https://discuss.overhang.io.
