### ISSUE TITLE
Error following the quickstart then trying new resources, building the image from scratch.

### ISSUE THREAD

**Issue by GustavoMS97** [overhangio/tutor#346]
**Bug description**
I am trying to configure Tutor in the company i'm working right now, and, one of the requirements is that i needed to try the unrevised translation files from **Transifex** (files are linked). So, replacing the [django.po](https://www.transifex.com/open-edx/open-edx-releases/release-ironwood/pt_BR/download/for_translation/) and [djangojs.po](https://www.transifex.com/open-edx/open-edx-releases/release-ironwood-js/pt_BR/download/for_translation/) file inside the path where both needed to be ("$(tutor config printroot)/env/build/openedx/locale/pt_BR/LC_MESSAGES") and following the build guide, it always fails. 

**How to reproduce**
Step 1: Follow the quickstart guide to install tutor (https://docs.tutor.overhang.io/quickstart.html)
Step 2: Download the translation files to test new translations (Linked before)
Step 3: Follow the "Custom Translations" guide (https://docs.tutor.overhang.io/configuration.html#adding-custom-translations)
Step 4: Use the build command specified `tutor images build openedx openedx-dev`

**Environment**
OS: Linux Mint 19.3
Tutor: 10.0.8

**Error below:**
ERROR: Could not find a version that satisfies the requirement pycontracts==1.8.14 (from -r requirements/edx/base.txt (line 184)) (from versions: 1.2.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.7.12, 1.7.13, 1.7.14, 1.7.15, 1.7.16, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12)
ERROR: No matching distribution found for pycontracts==1.8.14 (from -r requirements/edx/base.txt (line 184))
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/openedx/venv/bin/python3.5 -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install -r requirements/edx/base.txt' returned a non-zero code: 1
Error: Command failed with status 1: docker build -t docker.io/overhangio/openedx:10.0.8 /home/gustavo/.local/share/tutor/env/build/openedx

![image](https://user-images.githubusercontent.com/19798281/86253408-e3cd8780-bb8a-11ea-991c-7f25c8e12217.png)

**Comment by regisb** [comment]
Hi! This is a new issue that was also noticed in this conversation: https://discuss.overhang.io/t/tutor-images-build-openedx-failed/717/2
Basically, pycontracts==1.8.14 was pulled from pypi, which made the package uninstallable. The upstream fix is here: https://github.com/edx/edx-platform/pull/24376/commits
The fix will be available in Tutor v10.0.10, which should be released in a few minutes.
