### ISSUE TITLE
Mongodb error when upgrading 

### ISSUE THREAD

**Issue by GustavoMS97** [overhangio/tutor#349]
**Bug description**
Yesterday i reported a [bug related to the python library error](https://github.com/overhangio/tutor/issues/346) when following the image build process. Tried to remove everything following the [uninstallation guide](https://docs.tutor.overhang.io/install.html#uninstallation) and start over now with version 10.0.10, got an error from docker. So i went back, installed everything with 10.0.8 and tried to follow [this guide to upgrade](https://docs.tutor.overhang.io/install.html#upgrading) referenced from [this answer](https://github.com/overhangio/tutor/issues/348#issuecomment-652818507), but instead got an error from mongodb referenced from the image below, so i cant upgrade nor build the images.

**Environment**
OS: Linux Mint 19.3 Tricia
Tutor: 10.0.8

**Additional context**
![image](https://user-images.githubusercontent.com/19798281/86359013-d544a600-bc46-11ea-80f3-e45f730a4b98.png)

**Comment by regisb** [comment]
After you encounter this error, what is the output of `tutor local logs mongodb`?

**Comment by GustavoMS97** [comment]
It's a giant log but the end is like this 
![image](https://user-images.githubusercontent.com/19798281/86368985-3cb52280-bc54-11ea-960d-0203cbb5ccad.png)

**Comment by regisb** [comment]
I don't understand: are you trying to upgrade an existing platform or are you installing from scratch? In the latter case you should not be running `tutor local upgrade`. You should only run `upgrade` when upgrading from v3 to v10.

**Comment by GustavoMS97** [comment]
I needed to upgrade tutor from v.10.0.8 to v10.0.10, following the initial steps but changing the command on **Quickstart (1-click install)** using v.10.0.10, but it crashed. So, i saw another comment showing how to update, like i said before.

**Comment by regisb** [comment]
If you are upgrading from v10.0.8 to v10.0.10 don't run `tutor local upgrade`. It's not clear to me now if your mongodb is now configured to run 3.2 or 3.6. I'll close this now. Feel free to discuss this further on the forums: https://discuss.overhang.io
