### ISSUE TITLE
Docs suggestion

### ISSUE THREAD

**Issue by juansele** [overhangio/tutor#352]
For the alternative install method using pip, in Ubuntu 18.04 users need to install python3-pip. It installs as pip3.

I suggest updating the requirements to:
sudo apt install python3 libyaml-dev python3-pip

and maybe add a note "you might need to use pip3 depending on your setup" ?

**Comment by dannymontalvo** [comment]
Hello,
Please any help would be apreciated, i run the command "pip install -e ." what about next ? i cannot see working the command tutor, and no containers ares running.

**Comment by dannymontalvo** [comment]
Reviewing the source code, there is a makefile, and Dockerfile, any help how to proceed form here?, how to build the binaries? and how to get up and running tutor from source code?

Thanks.

**Comment by regisb** [comment]
@dannymontalvo Github issues are for keeping track of Tutor issues, not asking for help. Please read the [troubleshooting docs](https://docs.tutor.overhang.io/troubleshooting.html) and head to the forums: https://discuss.overhang.io
