### ISSUE TITLE
Setting DATA_DIR should be a path

### ISSUE THREAD

**Issue by moraleja39** [overhangio/tutor#353]
**Bug description**
At 4d6de0138a554df45815df37193fcdf3f5b6852f, the setting `DATA_DIR` was added in Tutor config files as a plain string:
https://github.com/overhangio/tutor/blob/27d74c1343ad803a45c981b221cbfd1040738f6c/tutor/templates/apps/openedx/settings/partials/common_all.py#L20
However, in LMS' env `common.py`, it is defined as a `Path`:
https://github.com/edx/edx-platform/blob/7b93a7b1a2c20ffbd98f6d18a03f3074061c01b2/lms/envs/common.py#L534-L538
I have just noticed this is an issue while accessing the sysadmin dashboard courses section, where they use the `/` operand on the `DATA_DIR` value, and since it is defined as a string, throws:
```
...
  File "/openedx/edx-platform/lms/djangoapps/dashboard/sysadmin.py", line 343, in make_datatable
    + self.git_info_for_course(gdir))
  File "/openedx/edx-platform/lms/djangoapps/dashboard/sysadmin.py", line 251, in git_info_for_course
    gdir = settings.DATA_DIR / cdir
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**How to reproduce**
Enable the sysadmin dashboard, navigate to `/sysadmin/courses`.

**Environment**
Debian 10, tutor 10.0.10

**Possible fix**
I temporarily fixed this by manually editing `tutor/env/apps/openedx/settings/lms/development.py` and setting `DATA_DIR` as a path:

```
from path import Path as path
...
DATA_DIR = path("/openedx/data/")
```

However I am not sure if this could have unintended side effects because some other view expects `DATA_DIR` to be a string. My development instance seems to be running fine for now.

**Comment by regisb** [comment]
@moraleja39,
Thanks for the detailed bug report. To be honest, I wasn't even aware that this sysadmin dashboard even existed. It is now enabled by default. As you suggested, I changed the DATA_DIR setting from a str to a Path object. This feature will be available in v10.0.11, but I don't expect to make a new release before a couple days. In the meantime, you can enable this feature by running Tutor from the master branch.

**Comment by regisb** [comment]
Update: v10.0.11 will be released in a couple minutes.

**Comment by moraleja39** [comment]
Thanks for this blazingly fast release.
