### ISSUE TITLE
CMS and LMS worker Timeout issue

### ISSUE THREAD

**Issue by Arutselvan6** [overhangio/tutor#360]
This is the same issue like "issue no. 145" but for me the reason is not the RAM. My System RAM is also 8GB but still getting this issue. Help me solve it.
I'm trying to start tutor with the following command:
**tutor local start**

**### Unexpected Behavior**
forum_1           | Loading config.ru.
forum_1           | I, [2020-08-11T05:34:39.358624 #15]  INFO -- : listening on addr=0.0.0.0:4567 fd=12
forum_1           | I, [2020-08-11T05:34:39.359219 #15]  INFO -- : worker=0 spawning...
forum_1           | I, [2020-08-11T05:34:39.379227 #15]  INFO -- : worker=1 spawning...
forum_1           | I, [2020-08-11T05:34:39.394171 #24]  INFO -- : worker=0 ready
forum_1           | I, [2020-08-11T05:34:39.410108 #15]  INFO -- : worker=2 spawning...
forum_1           | I, [2020-08-11T05:34:39.436266 #27]  INFO -- : worker=1 ready
forum_1           | I, [2020-08-11T05:34:39.448258 #30]  INFO -- : worker=2 ready
forum_1           | I, [2020-08-11T05:34:39.457896 #15]  INFO -- : worker=3 spawning...
forum_1           | I, [2020-08-11T05:34:39.474126 #15]  INFO -- : master process ready
forum_1           | I, [2020-08-11T05:34:39.477835 #33]  INFO -- : worker=3 ready
lms_1             | [2020-08-11 05:35:03 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:59)
lms_1             | [2020-08-11 05:35:03 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:60)
lms_1             | [2020-08-11 05:35:03 +0000] [59] [INFO] Worker exiting (pid: 59)
lms_1             | [2020-08-11 05:35:03 +0000] [60] [INFO] Worker exiting (pid: 60)
cms_1             | [2020-08-11 05:35:03 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:59)
cms_1             | [2020-08-11 05:35:03 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:60)
cms_1             | [2020-08-11 05:35:03 +0000] [60] [INFO] Worker exiting (pid: 60)
cms_1             | [2020-08-11 05:35:03 +0000] [59] [INFO] Worker exiting (pid: 59)
lms_1             | [2020-08-11 05:35:04 +0000] [72] [INFO] Booting worker with pid: 72
lms_1             | [2020-08-11 05:35:04 +0000] [71] [INFO] Booting worker with pid: 71
cms_1             | [2020-08-11 05:35:04 +0000] [71] [INFO] Booting worker with pid: 71
cms_1             | [2020-08-11 05:35:04 +0000] [72] [INFO] Booting worker with pid: 72
lms_1             | [2020-08-11 05:35:34 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:72)
lms_1             | [2020-08-11 05:35:34 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:71)
lms_1             | [2020-08-11 05:35:34 +0000] [72] [INFO] Worker exiting (pid: 72)
lms_1             | [2020-08-11 05:35:34 +0000] [71] [INFO] Worker exiting (pid: 71)
cms_1             | [2020-08-11 05:35:34 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:72)
cms_1             | [2020-08-11 05:35:34 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:71)
cms_1             | [2020-08-11 05:35:34 +0000] [72] [INFO] Worker exiting (pid: 72)
cms_1             | [2020-08-11 05:35:35 +0000] [71] [INFO] Worker exiting (pid: 71)
lms_1             | [2020-08-11 05:35:35 +0000] [83] [INFO] Booting worker with pid: 83
lms_1             | [2020-08-11 05:35:35 +0000] [84] [INFO] Booting worker with pid: 84
cms_1             | [2020-08-11 05:35:35 +0000] [83] [INFO] Booting worker with pid: 83
cms_1             | [2020-08-11 05:35:36 +0000] [84] [INFO] Booting worker with pid: 84
lms_1             | [2020-08-11 05:36:06 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:83)
lms_1             | [2020-08-11 05:36:06 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:84)
lms_1             | [2020-08-11 05:36:06 +0000] [84] [INFO] Worker exiting (pid: 84)
lms_1             | [2020-08-11 05:36:06 +0000] [83] [INFO] Worker exiting (pid: 83)
cms_1             | [2020-08-11 05:36:06 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:83)
cms_1             | [2020-08-11 05:36:06 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:84)
cms_1             | [2020-08-11 05:36:06 +0000] [83] [INFO] Worker exiting (pid: 83)
cms_1             | [2020-08-11 05:36:06 +0000] [84] [INFO] Worker exiting (pid: 84)
lms_1             | [2020-08-11 05:36:07 +0000] [93] [INFO] Booting worker with pid: 93
lms_1             | [2020-08-11 05:36:07 +0000] [94] [INFO] Booting worker with pid: 94
cms_1             | [2020-08-11 05:36:07 +0000] [93] [INFO] Booting worker with pid: 93
cms_1             | [2020-08-11 05:36:07 +0000] [94] [INFO] Booting worker with pid: 94
nginx_1           | 2020/08/11 05:36:25 [error] 6#6: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: local.overhang.io, request: "GET / HTTP/1.1", upstream: "http://172.18.0.10:8000/", host: "local.overhang.io"
nginx_1           | 172.18.0.1 - - [11/Aug/2020:05:36:25 +0000] http://local.overhang.io "GET / HTTP/1.1" 504 578 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" "-"
lms_1             | [2020-08-11 05:36:37 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:93)
lms_1             | [2020-08-11 05:36:37 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:94)
lms_1             | [2020-08-11 05:36:37 +0000] [94] [INFO] Worker exiting (pid: 94)
lms_1             | [2020-08-11 05:36:37 +0000] [93] [INFO] Worker exiting (pid: 93)
cms_1             | [2020-08-11 05:36:37 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:93)
cms_1             | [2020-08-11 05:36:37 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:94)
cms_1             | [2020-08-11 05:36:37 +0000] [94] [INFO] Worker exiting (pid: 94)
cms_1             | [2020-08-11 05:36:37 +0000] [93] [INFO] Worker exiting (pid: 93)
lms_1             | [2020-08-11 05:36:38 +0000] [105] [INFO] Booting worker with pid: 105
lms_1             | [2020-08-11 05:36:38 +0000] [106] [INFO] Booting worker with pid: 106
cms_1             | [2020-08-11 05:36:38 +0000] [105] [INFO] Booting worker with pid: 105
cms_1             | [2020-08-11 05:36:38 +0000] [107] [INFO] Booting worker with pid: 107

**Comment by regisb** [comment]
Please discuss your issues in the forums prior to posting here.
