### ISSUE TITLE
Allow to override individual docker image in Tutor version 3

### ISSUE THREAD

**Issue by pakaponk** [overhangio/tutor#361]
**Is your feature request related to a problem? Please describe.**
I currently need to use Tutor version 3.12.6 because I would like to use the Figures plugin.
When I deploy OpenEdX to GKE, I push my custom-built image to GCR so K8S would be able to pull images from this registry instead.
However, when I changed `DOCKER_IMAGE_OPENEDX` to `gcr.io/my-project/openedx`, it still prefixes the default docker registry`docker.io`. Thus, my images cannot be pulled successfully.

We have already solved this problem in 10.1.0. I think we could cherry-pick [this commit](https://github.com/overhangio/tutor/commit/bbd92223eee4a17b6b59e81dfea084388b28dc98) then release a new version 3.12.7 to solve this problem.

**Describe the solution you'd like**
Same solution as version 10.1.0. 

**Describe alternatives you've considered**
For now, to circumvent the problem, I could change the default docker registry to an empty string then set each docker image individually.

**Comment by regisb** [comment]
Unfortunately, Tutor v3 is no longer supported for free users.
