### ISSUE TITLE
Elasticsearch bug

### ISSUE THREAD

**Issue by insad** [overhangio/tutor#369]
**Bug description**
See the following bug repeating every 5 sec in the console, after "tutor start":

forum_1          | ERROR: ElasticSearch configuration validation failed. "rake search:validate_index" failed with the following message: Alias 'content' does not exist.
mongodb_1        | 2020-10-05T13:51:32.006+0000 I NETWORK  [conn58] end connection 172.18.0.8:45414 (7 connections now open)
mongodb_1        | 2020-10-05T13:51:32.006+0000 I NETWORK  [conn57] end connection 172.18.0.8:45412 (6 connections now open)
tutor_local_forum_1 exited with code 101

**How to reproduce**
Fresh installation of tutor (last night installed) according to instructions at https://docs.tutor.overhang.io/local.html

**Environment**
Ubuntu 20.04 
Tutor 10.2.3

**Additional context**
None.

**Comment by regisb** [comment]
Hi @insad! Did you run `tutor local quickstart`?

**Comment by insad** [comment]
No I didn't, I followed the step-by-step instructions. But now I'm doing a quickstart, and see a lot of migrations in the console. So that will be the cause also behind my other bug report probably. Will keep you updated.....

**Comment by insad** [comment]
This problem has been solved after running `tutor local quickstart`
