### ISSUE TITLE
Fresh installation not working: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by insad** [overhangio/tutor#370]
**Note:** Domain name has been replaced everywhere by "hidden-name.academy".  
A site was running normally under Apache2 with letsencrypt certificate at https://hidden-name.academy, I only replace the symbolic link in "/etc/apache2/sites-enabled" with a link to "openedx.conf"; besides I removed all other configurations under "/etc/apache2/sites-enabled" and restarted the apache2 webserver.

**Bug description**
Chrome shows an ERR_TOO_MANY_REDIRECTS error at https://hidden-name.academy/

**How to reproduce**
Fresh installation (last night) according to https://docs.tutor.overhang.io/local.html
URL https://hidden-name.academy/ gives an ERR_TOO_MANY_REDIRECTS

*Console output:*
`nginx_1          | 172.18.0.1 - - [05/Oct/2020:14:23:29 +0000] http://hidden-name.academy "GET / HTTP/1.1" 301 186 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36" "89.115.xxx.xx"`

*config.yml*
```
ACTIVATE_HTTPS: true
ANDROID_OAUTH2_SECRET: xxxxxxxx
CMS_HOST: studio.hidden-name.academy
CONTACT_EMAIL: info@hidden-name.academy
ID: xxxxxxxx
JWT_RSA_PRIVATE_KEY: xxxxxxx
LANGUAGE_CODE: es-419
LMS_HOST: hidden-name.academy
MYSQL_ROOT_PASSWORD: xxxxxxxx
NGINX_HTTPS_PORT: 444
NGINX_HTTP_PORT: 81
OPENEDX_MYSQL_PASSWORD: xxxxxxxx
OPENEDX_SECRET_KEY: xxxxxxxx
PLATFORM_NAME: XXXXXXX
WEB_PROXY: true
```

*openedx.conf*
```
<VirtualHost *:80>
   ServerName hidden-name.academy
   Redirect / https://hidden-name.academy/
</VirtualHost>
<VirtualHost *:80>
   ServerName preview.hidden-name.academy
   Redirect / https://preview.hidden-name.academy/
</VirtualHost>
<VirtualHost *:80>
   ServerName studio.hidden-name.academy
   Redirect / https://studio.hidden-name.academy/
</VirtualHost>

<VirtualHost *:443>
    ServerName hidden-name.academy
    ServerAlias preview.hidden-name.academy studio.hidden-name.academy
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/hidden-name.academy/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/hidden-name.academy/privkey.pem

    ProxyPreserveHost On
    ProxyRequests On
    ProxyPass / http://localhost:81/
    ProxyPassReverse / http://localhost:81/
</VirtualHost>
```
*curl command in terminal:*
curl -v 'http;//localhost:81/'
```
*   Trying 127.0.0.1:81...
* Connected to localhost (127.0.0.1) port 81 (#0)
> GET / HTTP/1.1
> Host: localhost:81
> User-Agent: curl/7.71.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.13.12
< Date: Mon, 05 Oct 2020 14:47:18 GMT
< Content-Type: text/html
< Content-Length: 186
< Connection: keep-alive
< Location: https://studio.hidden-name.academy/
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.13.12</center>
</body>
</html>
* Connection #0 to host localhost left intact
```

**Environment**
Ubuntu 20.04
Tutor 10.2.3

**Additional context**
After stopping tutor and apache2, checked if some process was listening to ports 80, 81, 443, 444 with `sudo lsof -i:[port]` - that was not the case.

**Comment by insad** [comment]
This problem stays, even after performing `tutor local quickstart`

**Comment by regisb** [comment]
@insad Did you follow the instructions to run Open edX behind a web proxy? https://docs.tutor.overhang.io/local.html?highlight=web_proxy#running-open-edx-behind-a-web-proxy

Please don't use Github issues as a way to get support. I'll keep this issue open, but in the future please open a new topic in the official Tutor forums: https://discuss.overhang.io

**Comment by insad** [comment]
Yes I did, as you can see in my config.yml file. I will try a fresh install, removing all the docker containers, later this day.

**Comment by regisb** [comment]
I see that `ACTIVATE_HTTPS: true`. Did you get a "Potentially invalid configuration: ACTIVATE_HTTPS=true WEB_PROXY=false" warning during quickstart? It is not mentioned in the docs, and I will address this now, but you should set `ACTIVATE_HTTPS: false`.

**Comment by regisb** [comment]
Can you please try to replace the nginx port ProxyPass and ProxyPassReverse statements as follows:

```
ProxyPass / http://localhost:444/
ProxyPassReverse / http://localhost:444/
```

Then reload the Apache server. If this resolves your issue we'll fix the proxy template in Tutor.

**Comment by insad** [comment]
Yes it's working now!
