### ISSUE TITLE
Support multiple tenants

### ISSUE THREAD

**Issue by kesavkolla** [overhangio/tutor#376]
Is it possible to support multi-tenant environment with tutor? I would like to separate the infrastructure components with application server. I'd imagine the Open-Edx has two application servers (CMS, LMS) rest other things are infra components.

Ideally infra components (Database, cache, queue etc..) should be common with multi-tenant support by different schemas, different namespaces etc... Application servers will be configured to use the infra components.

Is this something achievable with tutor?

**Comment by regisb** [comment]
Anything is possible! It just requires more or less work. Please don't use Github issues for support. Instead, post your questions on the official forums: https://discuss.overhang.io
