### ISSUE TITLE
Support for envoyproxy

### ISSUE THREAD

**Issue by kesavkolla** [overhangio/tutor#377]
Is it possible to add envoyproxy as a reverse proxy instead of nginx/apache. I'd love to add this as a contribution too. I need some starting pointers on how to proceed with this.

IMO there is no separate server needed as a webserver. gunicorn will start the CMS and LMS and envoyproxy is enough to do the reverse proxy for load balancing and routing.

**Comment by regisb** [comment]
Indeed, the nginx container is not very useful anymore, now that we serve static assets with Whitenoise in the LMS/CMS containers. However, media assets are still served by nginx.
Please do not use Github as a place to ask for new features. Instead, you should first discuss your ideas in the official forums: https://discuss.overhang.io
