### ISSUE TITLE
Adaptation for windows (fork)

### ISSUE THREAD

**Issue by scwall** [overhangio/tutor#381]
Hello, 
Currently working on openedx for deployment for a clients, the project has been deployed by my "project manager" on the server for different universities  with the help of **tutor**. 
Working on windows I couldn't use tutor in the current state. I created a fork and made some adaptations to make it work on windows.  
I don't know if I used the most adequate methods to modify the project (I'm a junior dev :) ). I wanted to share my fork with you if you are interested in adding it to the initial project.

https://github.com/scwall/tutor

Thank's you in advance

**Comment by regisb** [comment]
@scwall Thanks for this! This is tremendously useful. Not bad for a "junior dev" ;)

I am planning on backporting your changes to Tutor. I just need a few clarifications:

- What is the value `os.getuid()` and `getpass.getuser()` on Windows?
- The pcrypt library does not seem to be very actively maintained, and I'm not keen on introducing yet another dependency. Especially as we already have pycryptodome bundled with Tutor. Can you please confirm that the following piece of code works on Windows:

```
from Crypto.Protocol.KDF import bcrypt, bcrypt_check
text = "passw0rd"
bcrypt(text.encode(), 12).decode()
# Correct password
bcrypt_check(text.encode(), encrypted.encode())
print("correct")
# Incorrect password
try:
    bcrypt_check("incorrect".encode(), encrypted.encode())
except ValueError:
    print("incorrect")
```

**Comment by scwall** [comment]
Hello sorry for the response time I had to switch to another project and I wasn't available :). I was running the tests now but I see this has already been done, I'll try to be more reactive next time.

**Comment by regisb** [comment]
No worries. Can you confirm that the newest release works for Windows?
If yes, it would be truly awesome if you could contribute some docs on how to get Tutor to work on Windows.

**Comment by scwall** [comment]
> Pas de soucis. Pouvez-vous confirmer que la version la plus récente fonctionne pour Windows?
> Si oui, ce serait vraiment génial si vous pouviez contribuer quelques documents sur la façon d’obtenir Tutor de travailler sur Windows.

No worries I look at it immediately I post quickly

**Comment by scwall** [comment]
Error in windows
  ```
  return os.getuid()
AttributeError: module 'os' has no attribute 'getuid'
```


And for install setup for develop
```
pkg_resources.DistributionNotFound: The 'requests' distribution was not found and is required by kubernetes
(venv) PS C:\Python\tutor-original> python setup.py develop

```

**Comment by scwall** [comment]
I posted a pull requests with the modifications for this one to work under windows 10, the user doesn't matter under windows 10 I just sent back the win32 information if needed otherwise it's enough to retrieve the user with the other command sent, the use of the command you had put for windows sends an error 

https://github.com/overhangio/tutor/pull/385

**Comment by regisb** [comment]
I guess I can close this?
