### ISSUE TITLE
Course unit doesn't load

### ISSUE THREAD

**Issue by iyoet** [overhangio/tutor#386]
I'm having the same problem that described in overhang's discuss page [here](https://discuss.overhang.io/t/not-able-to-add-the-unit-to-the-course/273). course unit doesn't load. anyone has the same problem? 

i'm on ubuntu 20.04, Docker version 19.03.8, build afacb8b7f0, Python 3.8.5.

**Comment by regisb** [comment]
Please don't ask for support in Github issues. Instead, post a *thorough* and *precise* description of your problem in the forums: https://discuss.overhang.io.
