### ISSUE TITLE
cms- and lms-worker pods not starting due to failed import debug_toolbar

### ISSUE THREAD

**Issue by uvwild** [overhangio/tutor#391]
am trying to setup a helm chart for installing openedx.
I managed the manual tutor installation from the k8s commandline.
I also found a project which has done before on outdated versions.

[helm chart](https://github.com/uvwild/tutor-helm-chart.git)

Most pods are starting but I get a repeating error with the debug_toolbar in the cms- and lms-worker pods.
I am looking around but cant seem to find the place to influence the setting of the container to disable this import (SETTINGS variable I think)

thanks for any pointers in the right direction would be helpful. Or is the 10.5.2 broken?

**Comment by regisb** [comment]
Hi @uvwild! Please do not open Github issues for support. Instead, open a new topic in the [official support forums](https://discuss.overhang.io) as outlined in the [troubleshooting](https://docs.tutor.overhang.io/troubleshooting.html) section of the docs.

**Comment by uvwild** [comment]
sorry for not finding the discuss forum first. I found the openedx which is another abstraction level.

 I thought  the DJANGO_SETTINGS_MODULE as being useeful for this.  Thanks for the confirmation .
no i just have to figure out how to get it to the right place via the helm chart
