### ISSUE TITLE
Read-only filesystem in containers

### ISSUE THREAD

**Issue by vejeta** [overhangio/tutor#392]
**Bug description**

See also: https://discuss.overhang.io/t/permissions-issues-in-the-docker-containers/1145

With tutor 11.0.2, in MacOS, the system we use for development, when spinning up containers:
```
tutor dev runserver cms
```
We are getting consistently these errors on the docker container:

```
Setting file permissions for user openedx...
chown: changing ownership of '/openedx/config': Read-only file system
chown: changing ownership of '/openedx/config/cms.env.json': Read-only file system
chown: changing ownership of '/openedx/config/lms.env.json': Read-only file system
Error: Command failed with status 1: docker-compose -f /Users/neithan/.local/share/tutor/env/local/docker-compose.yml -f /Users/neithan /.local/share/tutor/env/dev/docker-compose.yml --project-name tutor_dev run --rm --service-ports lms
```
This can be overcome by editing the docker-compose files manually:

```
/Users/neithan/.local/share/tutor/env/local/docker-compose.yml
/Users/neithan/.local/share/tutor/env/dev/docker-compose.yml
```
And mounting the volumes with something distinct from :ro (read-only), for example, we put “:z” instead of “:ro”

After that, we can do
```
tutor images build openedx-dev
tutor dev runserver cms
```
to be able to spin up the containers fine:

```
The cms service will be available at http://studio.local.overhang.io:8001
docker-compose -f /Users/neithan/.local/share/tutor/env/local/docker-compose.yml -f /Users/neithan/.local/share/tutor/env/dev/docker-compose.yml --project-name tutor_dev run --rm --service-ports cms
Starting tutor_dev_lms_1 ... done
Creating tutor_dev_cms_run ... done
Setting file permissions for user openedx...
File permissions set.
```

This seems to be a bug in tutor, in the way docker-compose files are created.

**How to reproduce**
See above.

**Environment**

Tutor version 11.0.2
MacOS Catalina 10.15.7
Docker Desktop 3.0.1

**Additional context**

It seems having the volumes with read only was to try to have compatibility with docker warm. 
See:
https://github.com/overhangio/tutor/issues/323
https://stackoverflow.com/questions/35218194/what-is-z-flag-in-docker-containers-volumes-from-option

**Comment by regisb** [comment]
Thanks for the detailed report @vejeta! Can you please try the following fix and tell me if it works for you:

- Edit the `$(tutor config printroot)/env/build/openedx-dev/bin/docker-entrypoint.sh` file
- Add `-perm /u=w` to the `find` command such that it becomes:

    find /openedx -not -path "/openedx/edx-platform/*" -not -user openedx -perm /u=w -exec chown openedx:openedx {} \+

- Run `tutor images build openedx-dev`
- Run `tutor dev runserver cms`

**Comment by vejeta** [comment]
@regisb: Before all, I did a 

```
tutor config save
``` 

That restored the docker compose files to their original :ro state on the volumes.

Then performed the steps you mentioned, and everything worked fine.

Do you think I should rebuild the `openedx` image with --no-cache to doublecheck, or this is not needed?

**Comment by regisb** [comment]
That's great. I'll push the fix then. Thanks for testing.

> Do you think I should rebuild the openedx image with --no-cache to doublecheck, or this is not needed?

No, this should be unecessary.

**Comment by regisb** [comment]
Looks like this issue occurred again, despite the earlier fix: https://discuss.overhang.io/t/permissions-issues-in-the-docker-containers/1145/11
Replacing `-perm /u=w` by `-writable` should do the job.
