### ISSUE TITLE
11.0.4 install can no longer pull docker images

### ISSUE THREAD

**Issue by GoldUniform** [overhangio/tutor#393]
**Bug description**

I just upgraded tutor on OSX to 11.0.4 from 11.0.3 to get around the 'read only' mount problem. I can no longer run `tutor dev run watchthemes` as it cannot pull the 11.0.4 image from the docker repo.

```
Pulling watchthemes (docker.io/overhangio/openedx-dev:11.0.4)...
ERROR: pull access denied for overhangio/openedx-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**How to reproduce**

`tutor dev run watchthemes`

**Environment**

OSX Big Sur, Tutor 11.0.4

**Additional context**

I have not hit my pull limit.

**Comment by regisb** [comment]
Please do not create Github issues to ask for support: https://docs.tutor.overhang.io/troubleshooting.html

The openedx-dev image is not available for download and must be built by yourself, as documented: https://docs.tutor.overhang.io/dev.html

**Comment by GoldUniform** [comment]
I wasn't asking for support. The code did not throw an error before upgrade, and then it did after upgrade, looking like an issue with the new version - and I didn't see anything noting that in upgrade docs. If I can't make a ticket for that then what are tickets for.

**Comment by GoldUniform** [comment]
Alright I see that I should have gone to the forum first, I missed that before - my apologies.
