### ISSUE TITLE
Openedx on EKS not getting customized opnedx version 

### ISSUE THREAD

**Issue by Tush37** [overhangio/tutor#401]
I’m able to successfully create cluster on aws and deploy default images of openedx app.

But with eks after tutor k8s init its showing default page even after building openedx from my own repo( Customized openedx code).

Please help me to get my customized openedx version to deploy on eks cluster.

**Comment by Tush37** [comment]
Resolved.

Steps :
tutor config printvalue DOCKER_IMAGE_OPENEDX

tutor config save --set “DOCKER_IMAGE_OPENEDX=dockerhubusername/openedx:3.11.6”

tutor images build openedx --build-arg EDX_PLATFORM_REPOSITORY=gitrepourl --build-arg EDX_PLATFORM_VERSION=branch

docker push username/openedx:3.11.6

tutor config save --set “DOCKER_IMAGE_OPENEDX=dockerhubusername/openedx:3.11.6”

tutor k8s start

kubectl annotate ingress.extensions/web -n openedx kubernetes.io/ingress.class=alb alb.ingress.kubernetes.io/scheme=internet-facing

**Comment by regisb** [comment]
In the future, please don't open Github issues when asking for support: https://docs.tutor.overhang.io/troubleshooting.html
