### ISSUE TITLE
Getting error after activating https on AWS EKS for tutor k8s start

### ISSUE THREAD

**Issue by Tush37** [overhangio/tutor#402]
Tutor platform works fine with http but when i enable https by choosing y in tutor config save --interactive I’m getting below error.

unable to recognize “/home/ubuntu/.local/share/tutor/env”: no matches for kind “Certificate” in version “certmanager.k8s.io/v1alpha1”

@regisb , I have created eks cluster on aws.

**Comment by regisb** [comment]
@Tush37 Please don't use the Github issues for support. Instead, and as clearly indicated in the [docs](https://docs.tutor.overhang.io/troubleshooting.html), create a topic in the [official forums](https://discuss.overhang.io/).
