### ISSUE TITLE
Swarm deployment

### ISSUE THREAD

**Issue by yanus** [overhangio/tutor#403]
It would be great to see Swarm as an alternative to Kubernetes deployment. We would like to run Tutor on our existing Swarm cluster. It would probably be possible to manually adjust and deploy the docker-compose.yml file, but having this as an option within the tutor script itself would be ideal.
It shouldn't be too hard, as Swarm supports docker-compose.yml files to specify the containers, see https://docs.docker.com/engine/reference/commandline/stack_deploy/. I could look into this myself, but unfortunately I am not too familiar with either Tutor nor Python. Let me know if these is anybody willing to take it on or I should just give it a shot!

Cheers,
Yannick

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Tutor forums: https://discuss.overhang.io.

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing

We have considered Docker Swarm support for Tutor. As you mentioned, that "shouldn't be too hard". But any contribution to Tutor has to be maintained in the future, and this is costly in terms of time and energy. Tutor already supports docker-compose and Kubernetes deployment. Personally, I do not have time to maintain a third deployment target for free. However, if there is a market for that, I would be willing to implement this feature as a plugin and package it as part of the commercial edition.
