### ISSUE TITLE
Wrong Redis container configuration

### ISSUE THREAD

**Issue by moraleja39** [overhangio/tutor#404]
**Bug description**
The Redis container mounted configuration is wrongly set here:
https://github.com/overhangio/tutor/blob/e3a00c1bb66a9d4680271f7f7aa7464419f85811/tutor/templates/local/docker-compose.yml#L44
This means that the custom configuration is not applied, and the snapshots are not saved in the tutor data directory, but in a volume defined in the Redis image.
The line should be:
` - ../apps/redis/redis.conf:/openedx/redis/config/redis.conf:ro`

However, after I changed and tested it, I noticed that Redis would not start:
```
1:C 16 Feb 2021 09:02:12.651 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 16 Feb 2021 09:02:12.651 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 16 Feb 2021 09:02:12.651 # Configuration loaded
1:M 16 Feb 2021 09:02:12.651 # Can't open the append-only file: Permission denied
```
Redis steps down from root and runs with UID 999, but the data folder created by docker-compose is owned by root.
However, after looking at the Redis entrypoint script (https://github.com/docker-library/redis/blob/04e150e0c6fb21e1eb0a79dde9998c37903358d3/6.0/docker-entrypoint.sh#L11-L14), I noticed that it can be easily fixed by changing the redis service workdir:
```
services:
  redis:
    working_dir: /openedx/redis/
    ...
```
That way Redis takes ownership of the data folder on startup and everything runs as expected.

Hope you find this useful.

**How to reproduce**
Just run a fresh installation with Tutor 11+. You will see an empty directory named `redis.conf` in `$TUTOR_ROOT/env/redis`, and also an always empty `$TUTOR_ROOT/data/redis`.

**Environment**
Debian 10 / Tutor 11.2.0

**Comment by regisb** [comment]
@moraleja39 Usually, tutor issues are first discussed on the Tutor forums -- but in this particular case you are right to consider that this is an actual issue (and a serious one). Thanks for the thorough description and for the proposed fixes, this makes my life much easier. I will promptly produce a new version to include the fix.
