### ISSUE TITLE
Fail to set a configuration parameter when its value has multiple '=' characters

### ISSUE THREAD

**Issue by ndtho8205** [overhangio/tutor#405]
**Bug description & How to reproduce**

I followed the recommendation in `tutor-ecommerce/README.md` to set `ECOMMERCE_PAYMENT_PROCESSORS` parameter.
However, it returns an error as follows.

```sh
$ cat ecommerce-config.yml
cybersource:
  transaction_key: +Yuwbw3Pge2A==

$ tutor config save -set "ECOMMERCE_PAYMENT_PROCESSORS=$(cat ecommerce-config.yml)"
Usage: tutor config save [OPTIONS]
Try 'tutor config save -h' for help.

Error: Invalid value for '-s' / '--set': 'ECOMMERCE_PAYMENT_PROCESSORS=cybersource:
  transaction_key: +Yuwbw3Pge2A==' is not of the form 'key=value'.
```

It is because the `transaction_key` is encoded using base64 which has multiple '=' characters at the end.
The `YamlParamType` parses the param by splitting it at **any** "=" character producing a list that has more than two elements to destructure, thus raise a ValueError.

https://github.com/overhangio/tutor/blob/59e368a449e30b6fc5bf08c93296823d0fee4518/tutor/commands/config.py#L20-L32

It can be fixed by updating line 25 to:

```python
k, v = value.split("=", maxsplit=1)
```

**Environment**

tutor version 11.2.3

**Comment by regisb** [comment]
This will be fixed in the next release. Thanks for the thorough bug description!
