### ISSUE TITLE
Have a problem with translating content "UnicodeDecodeError: 'ascii' codec can't decode" 

### ISSUE THREAD

**Issue by NauarNiktosh** [overhangio/tutor#410]
I am creating the file django.po,
When I am using Russian letters and want to display them in place of English words,

![image](https://user-images.githubusercontent.com/80881442/112840410-bdf0f700-90b8-11eb-8de0-732dce028238.png)

I have this kind of problem: "
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
The command '/bin/sh -c ./manage.py lms --settings=tutor.i18n compilejsi18n' returned a non-zero code: 1
Error: Command failed with status 1: docker build -t docker.io/overhangio/openedx:11.2.4 /root/.local/share/tutor/env/build/openedx
"
![image](https://user-images.githubusercontent.com/80881442/112840509-dc56f280-90b8-11eb-82b0-8ead8905dba5.png)

I've tried to configure the locale of the Ubuntu system, but it didn't help

![image](https://user-images.githubusercontent.com/80881442/112840711-1b854380-90b9-11eb-8520-ff0b8b968eed.png)

I tried to change in django.po like "About" => "About Us" it worked.

Anyone who knows how to fix this problem with the codec 'ascii', please, share the answer with me.

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Tutor forums: https://discuss.overhang.io.

In your topic, please replace any screenshot by copy-pasted logs. Also, include your django.po file such that people without a Cyrillic keyboard can replicate your issue.

**Comment by regisb** [comment]
You might be interested in this conversation: https://discuss.overhang.io/t/translating-login-registration-page/1378/3
