### ISSUE TITLE
Docker build for image openedx has broken dependency for py2neo

### ISSUE THREAD

**Issue by zakum1** [overhangio/tutor#411]
**Bug description**

In the latest version 11.2.4, when doing `tutor images build openedx`, there is an error:

```
ERROR: Could not find a version that satisfies the requirement py2neo==3.1.2 (from -r ./requirements/edx/base.txt (line 178)) (from versions: 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0, 4.3.0, 2020.0.0, 2020.1.0, 2020.1.1, 2021.0.0, 2021.0.1)
ERROR: No matching distribution found for py2neo==3.1.2 (from -r ./requirements/edx/base.txt (line 178))
WARNING: You are using pip version 20.0.2; however, version 21.0.1 is available.
```
This occurs on this step:

```
Step 34/87 : RUN pip install -r ./requirements/edx/base.txt
```

**How to reproduce**

`tutor images build openedx`

**Environment**

MacOS v11.2.3

**Additional context**

I see on `edx/edx-platform` this commit a few hours ago has changed this dependency due to PyPi having dropped this version:

https://github.com/edx/edx-platform/commit/5111a83be6d418d762d15df5fe931701dfb8f3e9#diff-160eb30f60d519b8fe8a919cb2646a7ebec7652952129cfdd803776e70be6300

Is there a quick workaround for this?

**Comment by regisb** [comment]
Thanks for raising this issue @zakum1! The fix is now available in v11.2.5.
