### ISSUE TITLE
Tutor email not send

### ISSUE THREAD

**Issue by snighdha09** [overhangio/tutor#416]
When I try to register in studio i am unable to receive activation code. What is the problem?  Is there a bug in tutor Or some other problem

Please post on our forums: https://discuss.overhang.io for questions about using `tutor`.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker.

**Comment by BbrSofiane** [comment]
Hi @snighdha09,

- Please ask your question on the forum -> https://discuss.overhang.io
- Take the time to describe your setup (version, etc..)
- Also, have a look at the [documentation ](https://docs.tutor.overhang.io/troubleshooting.html)on how to troubleshoot tutor and look for any information that could help other people understand your problem.

Hope this helps
