### ISSUE TITLE
LMS 502 due to buffer size not enough

### ISSUE THREAD

**Issue by wey-gu** [overhangio/tutor#426]
**Bug description**
LMS:
```log
invalid request block size: 4123 (max 4096)...skip
[uwsgi-http key: studio.xxx client_addr: 172.18.0.12 client_port: 42700] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 647]
```

**How to reproduce**
tutor local quick start
> create course, maybe with a long title?

**Environment**
Ubuntu 20.04

**Additional context**
Same as  https://github.com/overhangio/tutor-ecommerce/issues/14

**Comment by regisb** [comment]
Hi @wey-gu! Indeed, this looks like a bug. It was reported privately by another person in a different context (Openshift). The solution would consist of increasing the uwsgi buffer size, just like the in the tutor-ecommerce issue you reported. Would you like to open a PR?

**Comment by wey-gu** [comment]
> Hi @wey-gu! Indeed, this looks like a bug. It was reported privately by another person in a different context (Openshift). The solution would consist of increasing the uwsgi buffer size, just like the in the tutor-ecommerce issue you reported. Would you like to open a PR?

Will create one :)
