### ISSUE TITLE
SCORM XBlock not available in local mode (quickstart)

### ISSUE THREAD

**Issue by ruizanthony** [overhangio/tutor#434]
After running
tutor local quickstart

and after adding scormxblock in the advanced modules list
[
    "scormxblock"
]

The scorm xblock is not available for use in the studio.

**Comment by BbrSofiane** [comment]
Hi @ruizanthony,

Please use the [forum](https://discuss.overhang.io/) first if you have any questions/issues. 

Also, the more information you can provide the easier it is to help you, see: https://docs.tutor.overhang.io/troubleshooting.html
