### ISSUE TITLE
Discussion notification emails are not being sent

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#439]
**Bug description**

See description here: https://discuss.overhang.io/t/does-tutor-support-ace/1451/3?u=regis

When answering a forum conversation in the LMS, users should receive email notifications (provided the feature is enabled). This is not the case: the email sending task is processed by celery, but the SMTP server does not receive any request. 

**How to reproduce**

1. Enable forum notifications ([instructions](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_discussion_notifications.html)) by adding `{"enable_forum_notifications":true}` to the site configuration.
2. Make a comment in a forum
3. With a different user, write a reply to the initial comment.

A notification email should be sent, but it's not the case.

To debug this issue, it is recommended to run the LMS without workers (`CELERY_ALWAYS_EAGER = True`).

**Comment by pcliupc** [comment]
In my environment, I found settings.ACE_ROUTING_KEY was set to 'edx.core.low', that's the reason why the send mail task is never consumed.  After setting ACE_ROUTING_KEY to "edx.lms.core.default" in lms.env.json, the email notification works. @regisb
