### ISSUE TITLE
The default ACE emails look terrible

### ISSUE THREAD

**Issue by BbrSofiane** [overhangio/tutor#447]
**Is your feature request related to a problem? Please describe.**
The default rendered ACE emails currently require additional configuration to be usable out of the box as described in this [post](https://discuss.overhang.io/t/does-tutor-support-ace/1451/7?u=bbrsofiane).

1. There is no default logo
2. There is no default email address

**Describe the solution you'd like**
Add default sane values that will improve the usability of the platform out of the box.
- [ ] Set a default platform logo
- [x] Set a default mailing address

**Comment by BbrSofiane** [comment]
There is a default logo set in [common.py](https://github.com/edx/edx-platform/blob/c0bed879541b628f819d71412ea6d29da1fa9e46/lms/envs/common.py#L4718). Should the steps required to set the logo added somewhere?

**Comment by regisb** [comment]
Yes, I think it's important that we provide a better default for this setting. For instance: the URL of the LMS logo.

**Comment by regisb** [comment]
@BbrSofiane do you think you will have time to work on this in the coming weeks?

**Comment by BbrSofiane** [comment]
@regisb yes, I will have time to finish it this weekend.

**Comment by pcliupc** [comment]
I think it will be better if the from address of the email can also be configured (the email address is used by default, for example, if the sending email address is contact@overhang.io, 'contact' is shown as from address). The from address can be configured through site_configuration['email_from_address'] in LMS.

**Comment by regisb** [comment]
Wait, is this issue actually closed @BbrSofiane? I believe we still need to address the question of the logo, right?

> I think it will be better if the from address of the email can also be configured (the email address is used by default, for example, if the sending email address is contact@overhang.io, 'contact' is shown as from address). The from address can be configured through site_configuration['email_from_address'] in LMS.

@pcliupc As you point out, users always have the possibility of customizing the "from" address via the site configuration, right? In tutor there is now a `site-configuration` utility for that:

    tutor local run lms site-configuration set -d mylms.com email_from_address me@nospam.com

**Comment by BbrSofiane** [comment]
>  I believe we still need to address the question of the logo, right?

Yes, but I am not sure I am clear on what to do with 

> For instance: the URL of the LMS logo.

Right now the default value for the email logo is the same as the LMS logo (`DEFAULT_EMAIL_LOGO_URL = 'https://edx-cdn.org/v3/default/logo.png'`). 

Are you suggesting we add `LOGO_URL_PNG ='https://edx-cdn.org/v3/default/logo.png'`?

**Comment by regisb** [comment]
I suggest we point the email logo to the default logo stored as a static asset in the LMS:

    # E.g: https://demo.openedx.overhang.io/static/images/logo.png
    DEFAULT_EMAIL_LOGO_URL = "{{ "https" if ENABLE_HTTPS else "http" }}://{{ LMS_HOST }}/static/images/logo.png"

The problem with this solution is that it completely ignores theme- or site configuration- specific logos. I have experimented with a lazy string evaluation that seems to work. I'll open a PR.

**Comment by pcliupc** [comment]
> Wait, is this issue actually closed @BbrSofiane? I believe we still need to address the question of the logo, right?
> 
> > I think it will be better if the from address of the email can also be configured (the email address is used by default, for example, if the sending email address is [contact@overhang.io](mailto:contact@overhang.io), 'contact' is shown as from address). The from address can be configured through site_configuration['email_from_address'] in LMS.
> 
> @pcliupc As you point out, users always have the possibility of customizing the "from" address via the site configuration, right? In tutor there is now a `site-configuration` utility for that:
> 
> ```
> tutor local run lms site-configuration set -d mylms.com email_from_address me@nospam.com
> ```

sounds good.
