### ISSUE TITLE
The Mongodb database name of the forums is hardcoded and cannot be modified

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#449]
**Is your feature request related to a problem? Please describe.**

People running Tutor for Open edX SaaS want to run run a single Mongodb cluster for all their customers. For that, they need to create different databases on the same server. The problem is that the MongoDb database is hardcoded to "cs_comments_service".

**Describe the solution you'd like**

Introduce a `FORUM_MONGODB_DATABASE` that will default to "cs_comments_service" and will be used in the forum entrypoint.

**Additional context**

This issue was first reported here: 
https://discuss.overhang.io/t/tutor-k8s-deployment-mongodb-password/1586
https://discuss.overhang.io/t/setup-open-edx-saas-based-with-tutor/1597

**Comment by ChrisChV** [comment]
Hi @regisb!
Is anyone already working on this issue? I would like to contribute solving it

**Comment by regisb** [comment]
No one is, and you are most welcome to start working on it :)

**Comment by pcliupc** [comment]
> No one is, and you are most welcome to start working on it :)

@regisb @ChrisChV I have met this issue before and I would like to share my experience here:

1. add forum index name config in tutor and set env in k8s deployments
2. patch forum code to use the index config (can be set in cs_comments_service/models/content.rb)

**Comment by regisb** [comment]
Oh damn, @pcliupc you mean that the index name is hardcoded in the forum service? @ChrisChV do you feel like opening an upstream pull request to address that?

**Comment by pcliupc** [comment]
> Oh damn, @pcliupc you mean that the index name is hardcoded in the forum service? @ChrisChV do you feel like opening an upstream pull request to address that?

yes, in latest version, the indices for different types (such as comment, comment_thread) are separated but still hard coded.

**Comment by pcliupc** [comment]
> Oh damn, @pcliupc you mean that the index name is hardcoded in the forum service? @ChrisChV do you feel like opening an upstream pull request to address that?

Yes, the index name is hard coded. But sorry for mistaking mongodb name as index name :(
The mongodb name can be configured through set MONGOHQ_URL in tutor/templates/build/forum/bin/docker-entrypoint.sh.

**Comment by regisb** [comment]
Right! It's not too bad if the index/collection names are hard-coded, as long as we can modify the database name.

**Comment by ChrisChV** [comment]
Yes, I agree. First we have to resolve the hard coded database name.

**Comment by regisb** [comment]
This was resolved by https://github.com/overhangio/tutor/pull/453
