### ISSUE TITLE
The Open edX forum should be an optional feature

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#450]
**Is your feature request related to a problem? Please describe.**
Not everyone wants to run the Open edX forums on the LMS. Thus, forums should be moved to an officially-supported "forum" plugin.

**Describe the solution you'd like**

- Disable the forums by default in tutor-openedx
- Create an official forum plugin hosted on github.com/overhangio
- Make sure that the forum plugin is bundled with the `tutor` binary generated by GitHub Actions

**Additional context**
This issue was first reported here: https://discuss.overhang.io/t/disabling-the-forum-in-tutor/1599

**Comment by ghassanmas** [comment]
I am intrested in reolsving this:
To make sure I am in the right direction here is my inteded to be workflow: 
For tutor 
- Remove everything relaeted the fourm (service and image)  from the standard tutor templates, congfiguration settings..etc
- Create a plugin in a separate repo, simliar to overhangio/tutor-mfe  
- When **enabled**, tutor shuold run as how it's running now by defualt, creating service/job, building fourm if in dev..etc

**Comment by regisb** [comment]
Thanks for offering your help @ghassanmas! Your description of the work to be done is fairly accurate. It's certainly _not_ what I would consider an "easy" issue to tackle, especially if you are new to Tutor, but it's a great introduction to the Tutor internals and the plugin system. Also, I can provide advice as you make progress.

We will need to create the plugin before removing it from the Tutor core. I think it would be best to make the removal effective in Maple, and not before.

**Comment by ghassanmas** [comment]
@regisb, following throught I have started with creating a draft for the plugin, with only the patches being pushed in the meantime, let's move the conversation there I guess, overhangio/tutor-forum/pull/1

**Comment by regisb** [comment]
Closed by https://github.com/overhangio/tutor/pull/513
