### ISSUE TITLE
Zsh autocomplete is not working

### ISSUE THREAD

**Issue by habibahsan** [overhangio/tutor#457]
Hi, tried to find the answer in various places including [community forums](https://discuss.overhang.io/) but out of luck.

**Zsh autocomplete is not working with Ubuntu 20.04**
I installed tutor with this [direct-binary-download](https://docs.tutor.overhang.io/install.html#direct-binary-download) method

**My action here**
![2021-06-21_02-46](https://user-images.githubusercontent.com/49414485/122687997-68516400-d23b-11eb-8834-ba55a7480d0f.png)

**Environment**
Linux nashabibah 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by imantaba** [comment]
Bash completion is not working too for tutor version 12.0.0

**Comment by regisb** [comment]
Source completion was changed in Click v0.8: 

https://click.palletsprojects.com/en/8.0.x/changes/?highlight=completion#version-8-0-0
https://click.palletsprojects.com/en/8.0.x/shell-completion/

In zsh you should now run:

    echo "$(_TUTOR_COMPLETE=zsh_source tutor)" >> .zshrc

And in bash:


    echo "$(_TUTOR_COMPLETE=bash_source tutor)" >> .bashrc

I'll create a pull request to fix the docs.

**Comment by habibahsan** [comment]
It's working like a charm 👏 
Thank you @regisb for your contribution.

**Comment by regisb** [comment]
Let's keep this open until #459 is merged :)
