### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement py2neo==3.1.2

### ISSUE THREAD

**Issue by chethankumar4046** [overhangio/tutor#466]
**Bug description**
I am going to update the tutor from 10.3.1 to 12.0.1 
I got the above error. How can i fix this 

**How to reproduce**
build image openedx

**Environment**
ubuntu 18.04.5, tutor 12.0.1

**Comment by regisb** [comment]
Please don't ask for support. Instead, describe your issue on the forums: discuss.overhang.io/

(you should first upgrade to 10.5.4, then to 12.0.1)
