### ISSUE TITLE
Server error displayed when accessing LMS site

### ISSUE THREAD

**Issue by MarkJoseph1216** [overhangio/tutor#472]
Hello sir, when I accessing both LMS and CMS site, this error has been displayed, what is the meaning of this error? I hope you can help me, Thank you.

![image](https://user-images.githubusercontent.com/51809423/126675002-5eabfa7d-92a6-4f9c-bd6d-924ab724afd4.png)

**Comment by BbrSofiane** [comment]
To get help on your issue have a look at the [troubleshooting guide](https://docs.tutor.overhang.io/troubleshooting.html) if nothing work, open an post in the [forum](https://discuss.overhang.io/).
