### ISSUE TITLE
`zsh: segmentation fault` when running `tutor local quickstart`

### ISSUE THREAD

**Issue by lpm0073** [overhangio/tutor#473]
**Bug description**
running the command `tutor local quickstart` generates the following console output:

> ==================================================
        Interactive platform configuration
==================================================
zsh: segmentation fault  tutor local quickstart

I do not have any other information to provide beyond this

This is a run-time exception generated by Tutor

**How to reproduce**
tutor local quickstart

**Environment**
Mac mini (M1, 2020) running macOS Big Sur 11.5 (20G71), and Docker Desktop Version 3.5.2 (3.5.2.18). Rosetta is also installed.
zsh --version = zsh 5.8 (x86_64-apple-darwin20.0)
which zsh = /bin/zsh

No other noteworthy applications are presently running on this machine. I've tried basic trouble shooting: rebooting, restarting the terminal app, checked the path and startup profile of zsh. I uninstalled any unnecessary homebrew packages. 

**Additional context**
The command "tutor config save --interactive" produces the same error.

Out of curiosity i attempted some other random commands, each of which seem to generate appropriate responses. For example, "tutor local createuser mcdaniel lpm0073@gmail.com --superuser --staff" produces the message, "Error: Project root does not exist. Make sure to generate the initial configuration with tutor config save --interactive or tutor local quickstart prior to running other commands."

Thus as far as I can tell, the zsh exception only arises from the quickstart and "tutor config save" commands

**Comment by lpm0073** [comment]
The command "tutor config save --interactive" produces the same error.

**Comment by lpm0073** [comment]
Out of curiosity i attempted some other random commands, each of which seem to generate appropriate responses. For example, "tutor local createuser mcdaniel lpm0073@gmail.com --superuser --staff" produces the message, "Error: Project root does not exist. Make sure to generate the initial configuration with `tutor config save --interactive` or `tutor local quickstart` prior to running other commands."

Thus as far as I can tell, the zsh exception only arises from the quickstart and "tutor config save" commands

**Comment by ghassanmas** [comment]
I have a simliar machine MAC M1 wtih ARM, I encounterd the same error, after an hour of  debugging, it turns out that this line of code is reposible: 
https://github.com/overhangio/tutor/blob/c678638ea2b14ff203333a8c196a6fadd194685b/tutor/utils.py#L102 

Which is a function for the `pycryptodome` , and they have already risen a related issue with the same error https://github.com/Legrandin/pycryptodome/issues/506, due to falling tests

**Comment by ghassanmas** [comment]
Also to confirm, that your error cause is same reason that I mentioned above, you should be able to reproduce the error as by running the following from `python` shell , 

```
Python 3.9.2 (default, Feb 24 2021, 05:06:40) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Crypto.PublicKey import RSA
>>> RSA.generate(2048)
zsh: segmentation fault  python3

```

**Comment by ghassanmas** [comment]
What the solution was for me, is to use python 3.8, instead of python 3.9, given as I explained in this comment, the test weren't falling for [python 3.8](https://github.com/Legrandin/pycryptodome/issues/506#issuecomment-778508382). 
If you want to use my __temp solution__, be aware that you would have uninstall `tutor` first since you want to reinstall it in `python 3.8` env and you don't want to have a conflict cli names.

**Comment by regisb** [comment]
Thanks for the thorough report @lpm0073 @ghassanmas. Unfortunately I was not able to reproduce the issue on my Linux machine with Python 3.9.1:

```
$ python
Python 3.9.1 (default, Aug 10 2021, 09:20:19) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Crypto.PublicKey import RSA
>>> RSA.generate(2048)
RsaKey(n=23607865662900940079059802157423655175402406416144926764454127367375266844676366957283486992491301942605823415899671460451533103420796812749564671403208815381125135080491557036595860432273165721537203849412148425594042200654775683811789885590937908841365193773654592435668088553843958587661699166373472113656715016170558067340893048538521753608256255003756188768990490803817340791500962242662843035213932397587150018862041849119451577465265682654849511696196926012140612754564394913373007972295293783853434487954203253032161832569390179213786491733584448057340196692468153293346581867163196325026805193107448283178263, e=65537, d=11038821418538655389363994494913853258809818017601556498364504113852195932399788321443975420623460066530115136007712926588141144510407982182645445669097342614811315775426454058134517066951417168220193834983453353496751853425778925531690421425934918404705978006267576451391286444119675739499808354119533487754150695734750504048385437266654246037017708194140601699204007667842500444463400605012629282536816796228285742851062691294345844842695286209818454905810818449455137048455230649655963598867875622130164455464201336729612651212769153288393711963159112958635373910753114161326082421243687405512960263275665719760581, p=146023044372074688172621492492716229227480588992409429390952199457962723928208223379998286797999187632910197030077713523504859891880656456455539951921185576713241946333925619884585048441092889423413640234402309527362876183912626863417641246100286028580698553675828588273517773881401453256669908956104870234549, q=161672191977773108624866598160110735486555030554782176626311743833216713045909546352541258732128208260194798117101905853006103973694348512908090781554090262576082102439529611440979291913592803335547519136943889049721395239717236500495016653368454937108908310633051661269854263098644828692164464777644893602587, u=77097882733428320375280714485408356040315127412597963742760140217954047304954085395010207180267383099367990078304898890803865723508913356609930867672751515992842747302196402219453929766765784936677156107417002791556095190280523634029859487241521100556399755583417874891757916469656824802150716146465917009383)
```

It was reported [here](https://github.com/Legrandin/pycryptodome/issues/509) that installing `cffi==1.14.5` solved the problem. Can you please attempt to run `pip install cffi==1.14.5` and then the code above?

**Comment by ghassanmas** [comment]
@regisb indeed, I wouldn't guess it will be reproducible on a Linux machine, the issue has to do with apple silicon ARM64, it occurs when `cffi` successfully loads the `GMP`  native C library **and** tries to run it if `cffi` fails to load the library, then `pycryptodome` will use an alternative to the `GMP` library and there won't be an issue. I wrote a detailed explanation here https://github.com/Legrandin/pycryptodome/pull/541#issuecomment-893458367

**Comment by regisb** [comment]
Yes @ghassanmas I saw your answers.

> It was reported here that installing cffi==1.14.5 solved the problem. Can you please attempt to run pip install cffi==1.14.5 and then the code above?

Did you see this part of my comment?

**Comment by ghassanmas** [comment]
@regisb Sorry for not following correctly, I have just tested, and it didn't fixed it:

```
>>> cffi.__version__
'1.14.5'
>>> from Crypto.PublicKey import RSA
>>> RSA.generate(2048)
zsh: segmentation fault  /opt/homebrew/bin/python3.9

```

**Comment by regisb** [comment]
Thanks @ghassanmas. We'll wait for an answer on your pycryptodome issue. If there isn't, we'll have to fork the project.

**Comment by ghassanmas** [comment]
Yeah agree, I could help with that, also it might be worth considering an alternative library  like https://github.com/pyca/cryptography

**Comment by regisb** [comment]
@ghassanmas `cryptography` seems better supported than cryptodome, so I agree with your suggestion to switch over. Would you have the time and be able to make the change in Tutor? We mostly need to change the `tutor.utils` module. I could attempt to do it but I have little experience with this library.

**Comment by ghassanmas** [comment]
@regisb yeah I would be happy to devote some time to it although I think it would save a lot of time if I understood the main architecture of  tutor before starting, that being said, would it be possible to have a call for about 30-45min? 
 The goal would be just for me to fill some gaps about tutor.

**Comment by regisb** [comment]
@ghassanmas sure thing! Sent you a PM.

One thing that I'm worried about is that cryptography relies on a Rust toolchain; replacing cryptodome would require users either to have a `rustc` compiler or to run `pip install wheel`. I hope we can get around this issue.

**Comment by ghassanmas** [comment]
@regisb just responded to your PM, thank you. 

Regarding Rust, it seems that might be needed for the build process, i.e. install from the source code, according to the [doc](https://cryptography.io/en/latest/installation/#rust), also if tutor uses `cryptodome` for generating RSA keys only, would you think this library [RSA python](https://stuvel.eu/python-rsa-doc/index.html) might be relevant as well? ,  worth noting that according to the author it might take [around 7 second](https://stuvel.eu/python-rsa-doc/usage.html#time-to-generate-a-key) for generating 2048 bit key (on one core machine).

**Comment by regisb** [comment]
Tutor uses cryptodome for more than just generating RSA keys. See this [utils.py](https://github.com/overhangio/tutor/blob/master/tutor/utils.py) module.

**Comment by ghassanmas** [comment]
Yes correct, I have looking into the native module support from python, for other usage it seems that [this module](https://docs.python.org/3/library/crypt.html#module-crypt) could cover it, so we can use crypto for hashing and compare the hash.

Note: according to python documentation this works in [UNIX system](https://docs.python.org/3/library/unix.html), which should run smoothly given tutor uses Ubuntu docker image? 

We can discuss tomorrow  in the call, see what our best option are, it seems though for Python to use cryptography efficiently (run quicky) python has to rely or use other run time...

**Comment by regisb** [comment]
Okay so we just had a very productive meeting with @ghassanmas. A few conclusions:

The pure-Python [rsa](https://stuvel.eu/python-rsa-doc/usage.html) library is interesting, but too slow for our purpose. On my machine, generating a private key takes ~30x longer than with pycryptodome:

```
$ time python -c "from Crypto.PublicKey import RSA; RSA.generate(2048)"
real    0m0,326s
user    0m0,297s
sys     0m0,026s
$ time python -c "import rsa; rsa.newkeys(2048)"
real    0m10,059s
user    0m9,889s
sys     0m0,156s
```

It should be possible to monkey-patch the cryptodome library to _not_ make use of the GMP implementation. I opened #487 to this effect. @lpm0073 @ghassanmas would you be able to try out this PR to see if it fixes the problem for you?

```
git clone https://github.com/overhangio/tutor
cd tutor
git checkout regisb/fix-arm-segfault
pip install -e .
tutor config save
```

**Comment by ghassanmas** [comment]
@regisb Unfortunately did not fix it, I will write more detials on the PR.
