### ISSUE TITLE
Unable to run tutor quickstart using separate MySql instance due to CLI warnings

### ISSUE THREAD

**Issue by harry-hathorn** [overhangio/tutor#477]
**Bug description**
Failing to run quickstart with the following warning: "[Warning] Using a password on the command line interface can be insecure."

I am trying to run tutor local quickstart with custom configuration as follows i.e. a seperate MySql server.
RUN_MYSQL: false
MYSQL_HOST: 127.0.0.1
MYSQL_ROOT_USERNAME: root
MYSQL_ROOT_PASSWORD: rootPassword

When running the quickstart it fails to run this line:
[line 18 templates/hooks/mysql/init](https://github.com/overhangio/tutor/blob/master/tutor/templates/hooks/mysql/init#:~:text=edx-platform%20database-,mysql,--u%20%7B%7B%20MYSQL_ROOT_USERNAME%20%7D%7D%20--password)

It fails with 10 warning attempts. The warning being: 

"[Warning] Using a password on the command line interface can be insecure."

It is not possible to suppress this warning my mysql 5.7 installation. 
According to this
[stackoverflow question](https://stackoverflow.com/questions/20751352/suppress-warning-messages-using-mysql-from-within-terminal-but-password-written)

You need to store password in a seperate file or append the line 2>/dev/null
e.g. 

mysql -u root -pMYPASSWORD -e "show databases" 2>/dev/null

However I am unable to alter the quickstart script to do this. Please help, i'm unable to install.

**How to reproduce**
1. Running Ubuntu 18.04, install Mysql 5.7. 
2. Set up a root username and password for mysql. 
3. try to run command (i.e. the CLI command that runs with tutor local quickstart )
mysql -u root --password="rootPassword" --host "127.0.0.1" --port 3306 -e 'CREATE DATABASE IF NOT EXISTS openedx;'
4. blocked by warning: [Warning] Using a password on the command line interface can be insecure.

**Environment**
Running Ubuntu 18.04
Running local Mysql 5.7

**Comment by insad** [comment]
Besides that I suppose you should use the forum for asking support, the warning has nothing to do with your problem, as the same warning appears using the dockerized mysql.
Did you read the following line in the instructions: "Note that you are responsible for creating the root user if you are using a managed database."
Probably the mysql root user doesn't have a password (seems the default in Ubuntu, you can login as root simply with "sudo mysql"), see here https://devanswers.co/how-to-reset-mysql-root-password-ubuntu/ for instructions to set a root password.

**Comment by BbrSofiane** [comment]
@harry-hathorn  as @insad said, please post your question in the [forum](https://discuss.overhang.io/).
