### ISSUE TITLE
Dead links to pages from kubectl book

### ISSUE THREAD

**Issue by 0x29a** [overhangio/tutor#479]
The book has been removed: https://github.com/kubernetes/kubectl/commit/7134adff7cdfd2f3ff21c0d31882691969f849b8 and links to its pages are dead now.

For example, check `declarative application management` link on [this page](https://docs.tutor.overhang.io/k8s.html#technical-details).

**Comment by regisb** [comment]
Thanks for creating this issue @0x29a! Can you please review the PR?
