### ISSUE TITLE
Email Verification issue

### ISSUE THREAD

**Issue by hassan52230** [overhangio/tutor#480]
I am using tutor open edx on ubuntu. currently the functionalities  are working fine. but the email verification issue when i sign in i don't receive email. i have port 587 25 and 465 with office365 and gmail also and  firewall is deactivated. Sometimes it shows frozen error and and sometimes 53 defer error. i can't find a solution for this email verification or other way around. i tried to deactivate the setting but it didn't worked out. Please help me out?
This error is shown in terminal
417   ** hassan.ghaffar@analytics.com.pk R=dnslookup T=remote_smtp: all hosts for 'analytics.com.pk' have been failing for a long time (and retry time not reached)

tp_1           |   423   ** hassan.ghaffar@analytics.com.pk R=dnslookup T=remote_smtp: all hosts for 'analytics.com.pk' have been failing for a long time (and retry time not reached)
smtp_1           |   423 LOG: MAIN
smtp_1           |   423   Frozen (delivery error message)

**Comment by insad** [comment]
Besides that you should post this kind of questions on the forum (https://discuss.overhang.io/), you should try the following on a machine separate from your server (replace "yourdomain.com" with the domain you are running Tutor with). 

```
C:\>nslookup yourdomain.com 
Server:  xxxxxxxx
Address:  fe80::1

Non-authoritative answer:
Name:    yourdomain.com
Address:  xxx.xxx.xxx.xxx
```


Take note of the last line with an IP (xxx.xxx.xxx.xxx).

Now do again an nslookup, but this time using this IP:


```
C:\Users\Alberto>nslookup xxx.xxx.xxx.xxx
Server:  xxxxxxxx
Address:  fe80::1

Name:    yourdomain.com
Address:  xxx.xxx.xxx.xxx
```


This time, the "Name" should be equal to the domain you run Tutor with.

If this is NOT the case, reverse DNS pointers are not well configured for your domain, and you cannot use the built-in SMTP server in Tutor for sending out emails, as emails will be rejected by most mailservers.

If you pay for a fixed IP, probably you can have the reverse DNS pointers configured by your ISP or datacenter (or do it yourself in some configuration console provided by the ISP / datacenter). 

If you use a dynamic IP (like I do using namecheap dynamic DNS), you'll be out of luck, as the name you typically will see in the last step is something like 'xxx.xxx.xxx.xxx.rev.yourisp.com'.

In this case, you can configure SMTP for:

1) If your ISP still provides for it, an SMTP-server hosted by your ISP (ask your ISP for mail server IP and login credentials); most ISP don't provide anymore mail service for their customers nowadays I think, at least my provider (Vodafone) gave up long time ago.
2) gmail SMTP - in this last case, the first email you send from your server will be rejected by gmail, but you'll get a security warning email in your gmail box, with a link where you can approve the use of gmail SMTP; after you confirm, subsequent emails sent from your server through gmail SMTP should have no problems. See also https://kb.synology.com/en-global/SRM/tutorial/How_to_use_Gmail_SMTP_server_to_send_emails_for_SRM

**Comment by regisb** [comment]
As suggested by @insad, please move this conversation [the forums](https://discuss.overhang.io/) @hassan52230.
