### ISSUE TITLE
Building the openedx-dev Docker image takes longer because of ipython

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#488]
**Bug description**

While building the openedx-dev Docker image, ipython is installed from source:

```
# We install ipython from source to avoid too many deprecation warnings
# https://github.com/ipython/ipython/issues/12206
# We might be able to avoid this once they make a release later than 7.19.0.
RUN pip install ipdb==0.13.4 git+https://github.com/ipython/ipython.git@d0649a54a8936a8019d54549779dc92bcbde4e68#egg=ipython
```

Now that there are [later releases of ipython](https://pypi.org/project/ipython/), we don't have to install from source anymore. Installing from pypi should considerably speed up this step.

**How to reproduce**

    tutor images build openedx-dev

**Additional context**

This issue was first reported by @ghassanmas.

**Comment by ghassanmas** [comment]
@regisb Just made a PR to fix it, review it on your peace.
