### ISSUE TITLE
The course prerequisites feature should be enabled by default

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#492]
**Is your feature request related to a problem? Please describe.**
Currently, the course prerequisistes feature is not enabled by default. Enabling it requires the use of a plugin. This feature is really useful for everyone and does not have any side effect.

See this conversation: https://discuss.overhang.io/t/course-prerequisites/162/
How to enable course prerequisites: https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_prerequisites.html
Usage docs: https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/set_up_course/studio_add_course_information/studio_prerequisites.html#specify-prerequisite-courses

**Describe the solution you'd like**

Prerequisites should be enabled after `tutor local quickstart`.

**Comment by Drakko25** [comment]
Hey @regisb, I wanted to work on this issue and created a PR with the fix https://github.com/overhangio/tutor/pull/506. Please let me know if any issues. Regards.
