### ISSUE TITLE
13.0.2 Upgrading a Kubernetes-managed installation from Tutor to Maple breaks Services

### ISSUE THREAD

**Issue by fghaas** [overhangio/tutor#551]
**Bug description**
Upgrading a Kubernetes-managed installation from Tutor to Maple breaks, because Kubernetes doesn't like the `nodePort` update to Services (the change that landed in 7c1e85ef4ba94cce1d597a1a3ea69cedbc2bde49).

**How to reproduce**
* Install Tutor 12.1.7, run `tutor k8s quickstart`
* Install Tutor 13.0.2, run `tutor k8s quickstart` again
* Observe that all Services break with:
   ```
   Service "mysql" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
   Service "redis" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
   ```

**Environment**
This is on Ubuntu Focal, against Kubernetes 1.18.20.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
<https://docs.tutor.overhang.io/k8s.html> doesn't cover Open edX release upgrades specifically, but <https://docs.tutor.overhang.io/install.html#upgrading> mentions re-running `tutor local quickstart`, so I am assuming that for Kubernetes, the same approach should work (with `tutor k8s quickstart`).

I understand that I can get around this with running `tutor k8s stop` while still on version 12, followed by `tutor k8s quickstart` on version 13 (because the persistent volumes persist, no data is lost this way), and people who ran Lilac on Tutor may want to do that when running the release upgrade. But the problem with that is that d8d0560b9e647d36bf3d596a559d41a6e01c06f6 only landed in version 13, meaning that doing so removes the Caddy service (and its external IP), so when people do that they will have to update their DNS records for the new IP external IP address they will receive. Meaning, the service interruption they incur may be longer than they expect.

Is there a way to add a follow-up change to 7c1e85ef4ba94cce1d597a1a3ea69cedbc2bde49, so that the Service change behaves nicely on a major release upgrade?

**Comment by regisb** [comment]
Thanks for the report @fghaas. Would the following procedure work?

1. Upgrade to v13
2. `tutor k8s stop`
3. `tutor k8s quickstart`

**Comment by fghaas** [comment]
I think that would work, yes. But I'm not sure what the expectation is, i.e. what Tutor _wants_ to support in this scenario.

The current documentation doesn't say that you need to stop everything in order to upgrade a running Kubernetes-deployed Tutor installation from one Open edX release to another. But then again, I'm not exactly sure how to make a no-downtime, _in-place_ upgrade safe in the Kubified Open edX context. You probably have given this more thought than I have. :)

**Comment by regisb** [comment]
It is definitely not expected that we are able to run a no-downtime upgrade from one major Open edX release to the next. Minor Tutor upgrades should work without downtime (vX.Y.Z -> vX.Y+1.Z), but major upgrades usually contain too many changes (and in particular: non-backward compatible database migrations) for us to expect that they are run without downtime.

I think it would make sense to stop all non-caddy services as part of `tutor k8s upgrade --from=lilac`: https://github.com/overhangio/tutor/blob/dbb79c0fa08457c3b04e426a609157de21bd3dbe/tutor/commands/k8s.py#L449
~This command is run as part of `tutor k8s quickstart` after an upgrade from v12 to v13.~ Scratch that :sweat:: the `tutor k8s upgrade` command _should definitely_ be run as part of `tutor k8s quickstart` after an upgrade from v12 to v13. It is currently _not_ run, and this should be considered a bug.

I'll open a PR to:
1. run `upgrade` as part of `quickstart`, when necessary.
2. stop all services (other than caddy) during `upgrade --from=lilac`.
