### ISSUE TITLE
when  tutor set common version to "open-release/maple.master" then tutor can not build openedx image correctly

### ISSUE THREAD

**Issue by gostdioh** [overhangio/tutor#562]
**Bug description**

Since frontend-app-gradebook  has fixed a bug about courseID on URL. I want to checkout the last version. thus, I setup 
`tutor config save --set OPENEDX_COMMON_VERSION="open-release/maple.master"` 
Then, I can not build openedx correctly.

**How to reproduce**

**Environment**

MacOS

**Additional context**

=> ERROR [code 8/8] RUN git fetch --depth=2 https://github.com/edx/edx-platform/ 85eb44445b8a6207b967bd4af5666e521a4af9b5  7.6s
------
 > [code 8/8] RUN git fetch --depth=2 https://github.com/edx/edx-platform/ 85eb44445b8a6207b967bd4af5666e521a4af9b5 && git cherry-pick 85eb44445b8a6207b967bd4af5666e521a4af9b5:
#18 6.728 From https://github.com/edx/edx-platform
#18 6.728  * branch            85eb44445b8a6207b967bd4af5666e521a4af9b5 -> FETCH_HEAD
#18 7.334 The previous cherry-pick is now empty, possibly due to conflict resolution.
#18 7.334 If you wish to commit it anyway, use:
#18 7.334 
#18 7.334     git commit --allow-empty
#18 7.334 
#18 7.334 Otherwise, please use 'git cherry-pick --skip'
#18 7.334 On branch open-release/maple.master
#18 7.334 Your branch is ahead of 'origin/open-release/maple.master' by 4 commits.
#18 7.334   (use "git push" to publish your local commits)
#18 7.334 
#18 7.334 You are currently cherry-picking commit 85eb444.
#18 7.334   (all conflicts fixed: run "git cherry-pick --continue")
#18 7.334   (use "git cherry-pick --skip" to skip this patch)
#18 7.334   (use "git cherry-pick --abort" to cancel the cherry-pick operation)
#18 7.334 
#18 7.334 nothing to commit, working tree clean
------
executor failed running [/bin/sh -c git fetch --depth=2 https://github.com/edx/edx-platform/ 85eb44445b8a6207b967bd4af5666e521a4af9b5 && git cherry-pick 85eb44445b8a6207b967bd4af5666e521a4af9b5]: exit code: 1
Error: Command failed with status 1: docker build -t docker.io/gostdio/openedx:latest /Users/project/my-cluster/instances/newed/env/build/openedx

**Comment by regisb** [comment]
This is correct. Please read the following section of the docs: https://docs.tutor.overhang.io/configuration.html#running-a-fork-of-edx-platform
Also, please don't use GitHub issues for support. See: https://docs.tutor.overhang.io/troubleshooting.html
