### ISSUE TITLE
Reinstallation issue on tutor

### ISSUE THREAD

**Issue by mshukurlu** [overhangio/tutor#566]
**Bug description**

I have uninstalled tutor by reading   [Uninstallation guide](https://docs.tutor.overhang.io/install.html#uninstallation),

I have done the steps for uninstall, After this when I need to install tutor it gives me an  error,

When I clear all volumes, all containers then installation go on,

I think this is a bug because the tutor does not remove all data  from containers.

I tested this 2 times.

![Screenshot_1](https://user-images.githubusercontent.com/11161906/149515693-8b35f9ae-28b0-4c6b-b4ae-73ae92b069bc.png)
 

 

**How to reproduce**
Install tutor  then uninstall after new installation I am facing with the issue,

**Environment**

Windows 10 Machine with Ubuntu 18.04 wsdl , tutor version - tutor, version 13.1.0

**Additional context**
After removing containers and data it works.

**Comment by iamCristYe** [comment]
@mshukurlu Are you sure you've stopped containers before removing the files? That's what I missed when I came across the same error last time.

**Comment by mshukurlu** [comment]
@iamCristYe Yes, sure, I had made all steps regarding to insturction

**Comment by iamCristYe** [comment]
I'm a bit curious why in some cases not removing containers is OK, while in other scenarios not OK.

**Comment by regisb** [comment]
Docker black magic...

**Comment by mshukurlu** [comment]
@regisb thank you much for your time and effort resolving this issue.
