### ISSUE TITLE
Some steps failing in `tutor local quickstart`

### ISSUE THREAD

**Issue by pedroalvesbatista** [overhangio/tutor#584]
**Bug description**

After trying to run tutor locally using quickstart, the following errors occurs :

tutor local quickstart
==================================================
        Interactive platform configuration
==================================================
Are you configuring a production platform? Type 'n' if you are just testing Tutor on your local computer [Y/n] 
Your website domain name for students (LMS) [lms.myproject.com.br] 
Your website domain name for teachers (CMS) [cms.myproject.com.br] 
Your platform name/title [My Project] 
Your public contact email address [myproject@gmail.com] 
The default language code for the platform [pt-br] 
Activate SSL/TLS certificates for HTTPS access? Important note: this will NOT work in a development environment. [y/N] n
Configuration saved to /home/mylab/.local/share/tutor/config.yml
Environment generated in /home/mylab/.local/share/tutor/env
==============================================
        Stopping any existing platform
==============================================
docker-compose -f /home/mylab/.local/share/tutor/env/local/docker-compose.yml -f /home/mylab/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local stop
======================================================
        Starting the platform in detached mode
======================================================
docker-compose -f /home/mylab/.local/share/tutor/env/local/docker-compose.yml -f /home/mylab/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local up --remove-orphans --build -d
Starting tutor_local_mysql_1 ... 
Starting tutor_local_redis_1 ... 
Starting tutor_local_elasticsearch_1 ... 
Starting tutor_local_mongodb_1       ... 
Starting tutor_local_smtp_1          ... error
Starting tutor_local_elasticsearch_1 ... error

ERROR: for tutor_local_smtp_1  Cannot start service smtp: network 53641226fb7fdae447dfc69ba2f587a66abac5f6e4547bd4c1e44a7ed1016201 not found

Starting tutor_local_mysql_1         ... error
runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/data/elasticsearch" to rootfs at "/usr/share/elasticsearch/data" caused: stat /home/mylab/.local/share/tutor/data/elasticsearch: permission denied: unknown

Starting tutor_local_redis_1         ... error
ailed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/data/mysql" to rootfs at "/var/lib/mysql" caused: stat /home/mylab/.local/share/tutor/data/mysql: permission denied: unknown

ERROR: for tutor_local_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/data/redis" to rootfs at "/openedx/redis/data" caused: stat stat /home/mylab/.local/share/tutor/data/redis: permission denied: unknown

ERROR: for caddy  Cannot start service caddy: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/env/apps/caddy/Caddyfile" to rootfs at "/etc/caddy/Caddyfile" caused: stat /home/mylab/.local/share/tutor/env/apps/caddy/Caddyfile: permission denied: unknown

ERROR: for tutor_local_mongodb_1  Cannot start service mongodb: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/data/mongodb" to rootfs at "/data/db" caused: stat /home/mylab/.local/share/tutor/data/mongodb: permission denied: unknown

ERROR: for smtp  Cannot start service smtp: network 53641226fb7fdae447dfc69ba2f587a66abac5f6e4547bd4c1e44a7ed1016201 not found

ERROR: for elasticsearch  Cannot start service elasticsearch: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/data/elasticsearch" to rootfs at "/usr/share/elasticsearch/data" caused: stat /home/mylab/.local/share/tutor/data/elasticsearch: permission denied: unknown

ERROR: for mysql  Cannot start service mysql: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/data/mysql" to rootfs at "/var/lib/mysql" caused: stat /home/mylab/.local/share/tutor/data/mysql: permission denied: unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/data/redis" to rootfs at "/openedx/redis/data" caused: stat /home/mylab/.local/share/tutor/data/redis: permission denied: unknown

ERROR: for caddy  Cannot start service caddy: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/env/apps/caddy/Caddyfile" to rootfs at "/etc/caddy/Caddyfile" caused: stat /home/mylab/.local/share/tutor/env/apps/caddy/Caddyfile: permission denied: unknown

ERROR: for mongodb  Cannot start service mongodb: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/mylab/.local/share/tutor/data/mongodb" to rootfs at "/data/db" caused: stat /home/mylab/.local/share/tutor/data/mongodb: permission denied: unknown
ERROR: Encountered errors while bringing up the project.
Error: Command failed with status 1: docker-compose -f /home/mylab/.local/share/tutor/env/local/docker-compose.yml -f /home/mylab/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local up --remove-orphans --build -d

**How to reproduce**

Run `tutor local quickstart`

**Environment**

Debian 10 "Buster" `amd64`
Docker Engine - Community
 Version:           20.10.11

`docker-compose version : 1.29.2`

**Additional context**

Running as non-root user, already tried to change permissions for `docker-compose`.

**Comment by BbrSofiane** [comment]
For [Troubleshooting](https://docs.tutor.overhang.io/troubleshooting.html#troubleshooting), please open a [thread on the forum](https://discuss.overhang.io/) first to ask for help.
