### ISSUE TITLE
Page Not Found in any course

### ISSUE THREAD

**Issue by martinbouhier** [overhangio/tutor#589]
After run `tutor local quickstart` and created some demo courses, if I click in view course, this redirect to: `http://local.overhang.io/None/course/course-v1:test22+test22+test22/home` and the page shows `Page not found The page that you were looking for was not found. Go back to the [homepage](http://local.overhang.io/) .`
How can I solved it?
Thanks

**Comment by BbrSofiane** [comment]
Please follow [Troubleshooting](https://docs.tutor.overhang.io/troubleshooting.html) instructions to get help.
