### ISSUE TITLE
ARM 64 - node sass issue

### ISSUE THREAD

**Issue by JeffKatzy** [overhangio/tutor#596]
I followed the tutorial for installing tutor with arm-64 [here](https://docs.tutor.overhang.io/tutorials/arm64.html) (including running the `tutor dev dc build lms` command).

When I get to the final step, `tutor dev start`, I run into the following error.
```
#12 74.70 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#12 74.70 gyp ERR! stack     at PythonFinder.failNoPython (/openedx/app/node_modules/node-gyp/lib/configure.js:484:19)
#12 74.70 gyp ERR! stack     at PythonFinder.<anonymous> (/openedx/app/node_modules/node-gyp/lib/configure.js:406:16)
#12 74.70 gyp ERR! stack     at F (/openedx/app/node_modules/which/which.js:68:16)
#12 74.70 gyp ERR! stack     at E (/openedx/app/node_modules/which/which.js:80:29)
#12 74.70 gyp ERR! stack     at /openedx/app/node_modules/which/which.js:89:16
#12 74.70 gyp ERR! stack     at /openedx/app/node_modules/isexe/index.js:42:5
#12 74.70 gyp ERR! stack     at /openedx/app/node_modules/isexe/mode.js:8:5
#12 74.70 gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
#12 74.70 gyp ERR! System Linux 5.10.76-linuxkit
#12 74.70 gyp ERR! command "/usr/local/bin/node" "/openedx/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#12 74.70 gyp ERR! cwd /openedx/app/node_modules/node-sass
#12 74.70 gyp ERR! node -v v12.22.10
#12 74.70 gyp ERR! node-gyp -v v3.8.0
#12 74.70 gyp ERR! not ok
...
#12 75.87 npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
#12 75.87 npm ERR! Exit status 1
#12 75.87 npm ERR!
#12 75.87 npm ERR! Failed at the node-sass@4.14.1 postinstall script.
```

I believe this is related to the [following](https://bitonron.medium.com/how-to-fix-react-and-node-sass-issue-with-docker-on-the-new-apple-m1-chips-a0541da302fe).

I am not sure if the `Can't find Python executable "python", you can set the PYTHON env variable.` is another issue.

**Comment by JeffKatzy** [comment]
Was able to get further by changing the dockerfile to perform a find and replace on `node-sass` in the `package.json` file with the following: 

```
# Install nodejs requirements
ARG NPM_REGISTRY=https://registry.npmjs.org/
COPY --from=code /openedx/edx-platform/package.json /openedx/edx-platform/package.json
WORKDIR /openedx/edx-platform

RUN sed -i 's/.*node-sass.*/"sass": "^1.49.8",/' /openedx/edx-platform/package.json

RUN npm install --verbose --registry=$NPM_REGISTRY
```

However, now I run into the following issue when performing `tutor local start`.

```
=> CANCELED [account 3/3] RUN bash -c "set -a && source /  601.2s
 => ERROR [profile 3/3] RUN bash -c "set -a && source /ope  601.0s
------
 > [profile 3/3] RUN bash -c "set -a && source /openedx/env/production && source /openedx/env/production.override && npm run build":
#73 0.575
#73 0.575 > @edx/frontend-app-profile@1.0.0-semantically-released build /openedx/app
#73 0.575 > fedx-scripts webpack
#73 0.575
#73 0.680 Running with resolved config:
#73 0.680 /openedx/app/node_modules/@edx/frontend-build/config/webpack.prod.config.js
#73 0.680
#73 599.8 Killed
#73 600.7 npm ERR! code ELIFECYCLE
#73 600.7 npm ERR! errno 137
#73 600.7 npm ERR! @edx/frontend-app-profile@1.0.0-semantically-released build: `fedx-scripts webpack`
#73 600.7 npm ERR! Exit status 137
#73 600.7 npm ERR!
#73 600.7 npm ERR! Failed at the @edx/frontend-app-profile@1.0.0-semantically-released build script.
#73 600.7 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#73 600.8
#73 600.8 npm ERR! A complete log of this run can be found in:
#73 600.8 npm ERR!     /root/.npm/_logs/2022-02-24T20_40_13_217Z-debug.log
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c bash -c "set -a && source /openedx/env/production && source /openedx/env/production.override && npm run build"]: exit code: 137
Error: Command failed with status 17: docker-compose -f /Users/jeffreykatz/Library/Application Support/tutor/env/local/docker-compose.yml -f /Users/jeffreykatz/
```

**Comment by jigsawlabs-student** [comment]
Potentially fixed the above by installing tutor-mfe, with the fix to the dockerfile described [here](https://github.com/overhangio/tutor-mfe/issues/31).  However, now running into a new error.

```
73 39.79 ERROR in ./src/index.scss
#73 39.79 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
#73 39.79 ModuleBuildError: Module build failed (from ./node_modules/image-webpack-loader/index.js):
#73 39.79 Error: Cannot find module 'gifsicle'
#73 39.79 Require stack:
#73 39.79 - /openedx/app/node_modules/imagemin-gifsicle/index.js
```

Found this related [stackoverflow](https://stackoverflow.com/questions/65147246/cannot-find-module-gifsicle-for-loading-image-webpack), but still working to resolve.

**Comment by yarons** [comment]
> 
> ```
> #73 39.79 Error: Cannot find module 'gifsicle'
> #73 39.79 Require stack:
> #73 39.79 - /openedx/app/node_modules/imagemin-gifsicle/index.js
> ```
> 
> Found this related [stackoverflow](https://stackoverflow.com/questions/65147246/cannot-find-module-gifsicle-for-loading-image-webpack), but still working to resolve.

There's definitely an ARM64 binary:
https://packages.ubuntu.com/jammy/gifsicle
But, if you'll click to the "arm64" link you'll end up in a page saying that it's not in the repository:
https://packages.ubuntu.com/jammy/arm64/gifsicle/download

The solution is to track down the Launchpad build process and get the `deb` files from its artifacts:
https://launchpad.net/ubuntu/+source/gifsicle/1.93-2/+build/22295342

Since there are no complicated dependencies you should have the binary installed pretty easily, but that's just half the story. 

In that case I'm seeing some peculiar stuff:
https://github.com/imagemin/gifsicle-bin/issues/124 (It's not a real dependency, it's just Unicode garbage).
https://www.npmjs.com/package/gifsicle (I'm trying to understand if this package is really needed as it's executing the `gifsicle` binary directly).
I'm trying to think if there's anything that can be done in that aspect with Node 12.

**Comment by regisb** [comment]
Guys, please discuss your issues in the forum. Do not use GitHub issues to troubleshoot your installation. Come back to GitHub once you have identified a precise problem. See: https://docs.tutor.overhang.io/troubleshooting.html
