### ISSUE TITLE
arm64: current SMTP Docker image (devture/exim-relay:4.94.2-r0-4) does not support ARM and should be upgraded

### ISSUE THREAD

**Issue by yarons** [overhangio/tutor#600]
**Bug description**
The current exim-relay (4.94) has no arm64 support, the newer version (4.95 and all its variations) support arm64.
It solved a problem with the smtp container, I'm not sure about other broken functionality but it runs.

https://registry.hub.docker.com/r/devture/exim-relay/tags

**How to reproduce**
Start docker on Ubuntu arm64.

**Environment**
Ubuntu 20.04.4 on arm64 (Thanks @bradenmacdonald !)

**Additional context**
The system is not up yet, there are many issues but once it'll be up I'll be able to test the SMTP functionality to see if it works.

**Comment by bradenmacdonald** [comment]
@yarons Will you be opening these changes as a PR? It's a little hard for me to follow the details see the implications with just a description.
