### ISSUE TITLE
tutor build openedx-dev ERROR

### ISSUE THREAD

**Issue by Harshgaur14** [overhangio/tutor#605]
![Screenshot from 2022-03-10 06-08-45](https://user-images.githubusercontent.com/65892351/157596932-564238a1-d7a6-4291-b589-ecc8c34de344.png)

after running tutor build openedx-dev , it hangs here 
I am confused what to do next ?

**Comment by BbrSofiane** [comment]
Please follow the instructions for [troubleshooting](https://docs.tutor.overhang.io/troubleshooting.html). If you can't find any help in the [documentation](https://docs.tutor.overhang.io/dev.html#open-edx-development), ask for help in the [forum](https://discuss.overhang.io/) not with a Github issue,

Thank you.
