### ISSUE TITLE
Tutor 13.1.6 broke "tutor k8s quickstart"

### ISSUE THREAD

**Issue by fghaas** [overhangio/tutor#611]
**Bug description**
After upgrading to Tutor 13.1.6, `tutor k8s quickstart` is broken.

**How to reproduce**
* Create a Tutor environment using 13.1.5.
* Upgrade to Tutor 13.1.6.
* Run `tutor config save`.
* Run `tutor k8s quickstart -I`.
* Observe the following error when getting to the "Initialising mysql..." step:
   ```
   Initialising all services...
   Initialising mysql...
   kubectl apply --kustomize /home/florian/git/tutor-deploy/--selector/env app.kubernetes.io/name=mysql-job-20220316140124
   ```
* Note that the correct `kubectl apply` command would be:
   ```
   Initialising all services...
   Initialising mysql...
   kubectl apply --kustomize /home/florian/git/tutor-deploy/env --selector app.kubernetes.io/name=mysql-job-20220316140124
   ```

**Environment**
Tutor 13.1.6 against Kubernetes 1.21.6.

**Additional context**
This problem appears to have been introduced in #593. In particular, [here](https://github.com/overhangio/tutor/pull/593/commits/c219d0a1a5b2759011514453324f1f70dc0e3efa#diff-e313e8286976537a9d30beb92045cbbd9743ffed0b4920baebf66966bfbf427bR115) and  [here](https://github.com/overhangio/tutor/pull/593/commits/c219d0a1a5b2759011514453324f1f70dc0e3efa#diff-e313e8286976537a9d30beb92045cbbd9743ffed0b4920baebf66966bfbf427bR225) I think the method that needs to be called is `apply_command()`, not `kubectl_apply()`.

**Comment by regisb** [comment]
I'm sorry Florian, what is the error that you observe? Is there an error message that is printed in the shell? Are you observing unexpected behaviour?

**Comment by fghaas** [comment]
Here's the error message:

```
Initialising all services...
Initialising mysql...
kubectl apply --kustomize /home/florian/git/tutor-deploy/--selector/env app.kubernetes.io/name=mysql-job-20220316124429
error: Unexpected args: [app.kubernetes.io/name=mysql-job-20220316124429]
See 'kubectl apply -h' for help and examples
Error: Command failed with status 1: kubectl apply --kustomize /home/florian/git/tutor-deploy/--selector/env app.kubernetes.io/name=mysql-job-20220316124429
```

Note that what causes this error is the `--selector` argument getting injected in the middle of the  `$TUTOR_ROOT/env` path.

**Comment by regisb** [comment]
Thanks for the quick answer Florian! The fix is here: https://github.com/overhangio/tutor/pull/613
I'll merge and create a new release right away.

**Comment by fghaas** [comment]
Just confirming that I have tested this with 13.1.7, and the issue is gone. `tutor k8s quickstart -I` now completes without a hitch again. Thank you!

**Comment by razorinc** [comment]
Sadly, trying to run `tutor k8s quickstart` using the binary of the version 13.1.7 throw me the same error:
```bash
Namespace does not exist: now creating it...
kubectl apply --kustomize /home/user/tutor/--wait/env --selector app.kubernetes.io/component=namespace
error: evalsymlink failure on '/home/user/--wait/env' : lstat /home/user/--wait: no such file or directory
Error: Command failed with status 1: kubectl apply --kustomize /home/user/--wait/env --selector app.kubernetes.io/component=namespace
```

```bash
~ $ tutor --version
tutor, version 13.1.7
```

**Comment by regisb** [comment]
Thanks for the report @razorinc. This issue affects not just users of the binary, but also people who install tutor from pip. I'll merge the following PR and release v13.1.8 in the next few minutes.

**Comment by razorinc** [comment]
Hi @regisb! Thanks for the prompt fix! Yes, but I did not explain myself correctly, I meant that the bug was still present in the 13.1.7 version. I was about to commit the fix but you was so fast on tackling the bug :)
