### ISSUE TITLE
The MFE plugin does not get deployed on k8s due to missing image on hub.docker.io

### ISSUE THREAD

**Issue by razorinc** [overhangio/tutor#617]
**Bug description**

The bug is the missing container on docker hub for the plugin mfe.
```bash
~ $ tutor plugins list
android==13.0.0 (disabled)
discovery==13.0.0 (disabled)
ecommerce==13.0.0 (disabled)
forum==13.0.0 (disabled)
license==13.0.0 (disabled)
mfe==13.0.2
minio==13.0.1 (disabled)
notes==13.0.1 (disabled)
richie==13.0.0 (disabled)
webui==13.0.0 (disabled)
xqueue==13.0.0 (disabled)
```
From the k8s logs I can see: `container "mfe" in pod "mfe-644b8799fc-xzmz5" is waiting to start: trying and failing to pull image` and checking on docker hub, I noticed that does not exist a container with the tag `13.0.2`, actually the last container is 

**How to reproduce**

Running a quickstart deployment on k8s: `tutor k8s quickstart`

**Environment**

Environment k8s on Debian and tutor version 13.1.8

**Additional context**

**Comment by CodeWithEmad** [comment]
MFE images are not pushed to [docker.io](http://docker.io/) because they include user-specific configuration. You are supposed to build the images yourself, and push them to your own private registry as documented here:
https://github.com/overhangio/tutor-mfe#running-mfes-on-kubernetes

**Comment by razorinc** [comment]
@CodeWithEmad thank you very much for your answer, make sense ! I will make sure to open a ticket and do a contribution on the documentation that refer to the link you shared, so that since the mfe plugin is enabled by default, users will know that's a mandatory step before running `tutor k8s quickstart`

**Comment by razorinc** [comment]
Hi Regis,

Thank you for letting me know. Maybe I can contribute to the doc, since in
the quickstart wasnt mentioned.

Thanks for the clarification.
