### ISSUE TITLE
Example of using `openedx-dockerfile-minimal` in the config.

### ISSUE THREAD

**Issue by mitangelo** [overhangio/tutor#629]
Can you provide an example of using `openedx-dockerfile-minimal`

**Comment by insad** [comment]
Sorry, but I think you should post your question here: https://discuss.overhang.io/

**Comment by mitangelo** [comment]
I did not see any examples in the source. So thought it would be a nice addition to add relevant examples for users

**Comment by insad** [comment]
Please read https://docs.tutor.overhang.io/troubleshooting.html

*** Warning: Do not create a Github issue! ***

**Comment by erickhgm** [comment]
All Tutor YAML plugins work in the same way, you just need to change the patches.

```
name: openedx_dockerfile_minimal
version: 0.1.0
patches:
  openedx-dockerfile-minimal: |
    COPY --chown=app:app ./custom/my-custom-script.sh /openedx/bin
```

After that, put the `openedx_dockerfile_minimal` in `PLUGINS` attribute of the `config.yml`file.
