### ISSUE TITLE
Error while executing commands inside service pods as per the documentation

### ISSUE THREAD

**Issue by kaustavb12** [overhangio/tutor#636]
**Bug description**
The tutor docs [recommends](https://github.com/overhangio/tutor/blame/master/docs/k8s.rst#L115-L122) the following command to run a python shell in lms container:
`tutor k8s exec lms ./manage.py lms shell`

However there are two issues with running the command as is :

1. Tutor expects the `k8s exec` cli commands to be of the form `tutor k8s exec [OPTIONS] SERVICE COMMAND` and thus throws the error `Error: Got unexpected extra arguments (lms shell)`. To run the service commands we need to add them to quotes such as `tutor k8s exec lms "./manage.py lms shell"`. Perhaps the docs should be modified to indicate that.

3. By default the sevice commands runs using the development settings, and thus throws the below error since it cannot find the debug toolbar installed:
![image](https://user-images.githubusercontent.com/36229857/162887896-4b1275d1-1c7d-4f73-9aba-fa2b1e1c7273.png)

Perhaps something like [BASE_OPENEDX_COMMAND](https://github.com/overhangio/tutor/blob/baf7d03cf801a398a5aa48ea80af275df418e215/tutor/jobs.py#L6) could be used with `k8s exec` to set the correct settings.
Or, the docs could simply guide the user to set the correct settings in the form of:
`tutor k8s exec lms "DJANGO_SETTINGS_MODULE=lms.envs.tutor.production ./manage.py lms shell"`

**How to reproduce**
1. Spin up a tutor k8s deployment with `tutor k8s quickstart`
2. Run `tutor k8s exec lms ./manage.py lms shell` to try to get to the lms shell.

**Environment**
Error encountered using tutor version 13.1.8

**Additional context**

**Comment by regisb** [comment]
This is an issue, as diagnosed here: https://github.com/overhangio/2u-tutor-adoption/issues/52

**Comment by regisb** [comment]
Actually, you raised two different issues:

- the fact that you cannot run `tutor k8s exec lms ./manage.py lms shell` (without quotes) will be resolved by #637.
- the missing environment variables that cause incorrect django settings to be loaded will be resolved once I merge this other PR: #640. This PR gets rid of the Docker entrypoint altogether and adds the DJANGO_SETTINGS_MODULE setting to the Docker containers. Thus, it will no longer be necessary to pass `--settings` arguments.

In the meantime, the workaround for your issues is to run management commands as follows:

    tutor k8s exec lms "./manage.py lms --settings=tutor.production ..."

In the future, you will be able to write instead:

    tutor k8s exec lms ./manage.py lms ...

**Comment by kaustavb12** [comment]
@regisb
It's good to know that the issues reported here are already been worked upon.
And thanks for the awesome work with Tutor !!
