### ISSUE TITLE
Not able to install tutor Indigo and tutor Figures

### ISSUE THREAD

**Issue by manojkumarhr** [overhangio/tutor#651]
![tutor figure error](https://user-images.githubusercontent.com/7630852/164993536-c1d35f78-66dd-4e99-b0ee-74787dbec042.png)

i am trying to install tutor plugins ( Like Figures, Indigo) not able to install i have also tried to install xblock from main openedx plugins list but not able to. Tried for indigo theme but also facing same error please solve the bugs 
![tutorr errror logs](https://user-images.githubusercontent.com/7630852/164993753-a8e5b1be-b20c-43a1-8571-d8925f4161a3.png)

for your refence i have uploaded tutor error logs please guide m

**Comment by manojkumarhr** [comment]
and also not able to install any xblock plugins of openedx please guide me thanks in advance.

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Tutor forums: https://discuss.overhang.io.

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing

**Comment by manojkumarhr** [comment]
i am using tutor 13.2.0 version still getting error
