### ISSUE TITLE
rehash cmd if using zsh and which tutor returns /usr/local/bin instead of venv/bin

### ISSUE THREAD

**Issue by natea** [overhangio/tutor#652]
**Bug description**

Not really a bug, but might want to add this to the documentation: if you're using zsh and you install tutor inside a virtualenv, you may not get the PATH updated to use the tutor binary in `venv/bin`, but it will still use the binary in `/usr/local/bin` if you're installed a previous version of Tutor.

**How to reproduce**

```
(tutor-venv)$ which tutor
/usr/local/bin/tutor
(tutor-venv)$ rehash
(tutor-venv)$ which tutor
/Users/nateaune/Documents/code/tutor-venv/bin/tutor
```

**Environment**

MacOS 12.2.1 ARM (M1 Mac)

**Additional context**

Thanks to @regisb for introducing me to the `rehash` command! And the warning to find an alternative shell to `zsh`.

**Comment by insad** [comment]
It's not only a zsh problem, happens also with bash.

In the documentation `https://docs.tutor.overhang.io/install.html#download` there's a clear warning already:

Choose ***one*** of the installation methods below. If you install Tutor in different ways, you will end up with multiple tutor executables, which is going to be very confusing. At any time, you can check the path to your tutor executable by running `which tutor`.

**Comment by regisb** [comment]
Yeah, this is one of the issues that occurred during yesterday's workshop. I'm not sure how to improve the installation instructions further without bloating them... I'd like to keep them as concise as possible, to make sure they are actually understood and clear for everyone. I'm going to close this issue for now. If you'd like to improve the instructions for running on macOS/zsh, maybe we should be writing a [tutorial](docs.tutor.overhang.io/tutorials.html)?

**Comment by natea** [comment]
I mostly added it as an issue, not to suggest that it should be a part of the documentation because it's probably a small percentage of users who will encounter this, but more as a breadcrumb, so that if someone (maybe me again?) encounters this error, there will be a clear explanation of how to resolve it.

Website: http://www.appsembler.com ( http://www.appsembler.com/ )
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea

Phone: +1 (617) 702-4331
