### ISSUE TITLE
Upgrade elasticsearch

### ISSUE THREAD

**Issue by IDerr** [overhangio/tutor#653]
Hello tutor team,  hope that you're doing well

I would like to know if an elasticsearch upgrade is planned due to log4shell issue, I have seen that tutor uses elasticsearch 7.10.1 version which seems to be affected by the CVE
https://hub.docker.com/_/elasticsearch?tab=tags&page=1&name=7.1

Thanks a lot for your work

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Tutor forums: https://discuss.overhang.io.

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing

On the topic of log4shell, please check this topic: https://discuss.overhang.io/t/log4shell-vulnerability/2227/2
