### ISSUE TITLE
Installing Tutor + Lilac on ARM64 fails due to Shapely's "geos" requirement

### ISSUE THREAD

**Issue by oedx2** [overhangio/tutor#661]
**Bug description**
I attempted to install Tutor 12.0.4 + Lilac.2 on an macOS M1 ARM64 system, and it errors out when trying to install Shapely due to not finding geos
```
OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
```

**How to reproduce**

```
xcode-select --install
	To get git
git clone https://github.com/overhangio/tutor
cd tutor
git checkout v12.0.4
pip install -e .
tutor config save
tutor images build openedx 
```

Yields

```
#24 35.36 Collecting shapely==1.7.1
#24 35.38   Downloading Shapely-1.7.1.tar.gz (383 kB)
#24 35.59     ERROR: Command errored out with exit status 1:
#24 35.59      command: /openedx/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uz82ibq1/shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uz82ibq1/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-uz82ibq1/shapely/pip-egg-info
#24 35.59          cwd: /tmp/pip-install-uz82ibq1/shapely/
#24 35.59     Complete output (11 lines):
#24 35.59     Failed `CDLL(libgeos_c.so.1)`
#24 35.59     Failed `CDLL(libgeos_c.so)`
#24 35.59     Traceback (most recent call last):
#24 35.59       File "<string>", line 1, in <module>
#24 35.59       File "/tmp/pip-install-uz82ibq1/shapely/setup.py", line 85, in <module>
#24 35.59         from shapely._buildcfg import geos_version_string, geos_version, \
#24 35.59       File "/tmp/pip-install-uz82ibq1/shapely/shapely/_buildcfg.py", line 169, in <module>
#24 35.59         lgeos = load_dll('geos_c',
#24 35.59       File "/tmp/pip-install-uz82ibq1/shapely/shapely/_buildcfg.py", line 162, in load_dll
#24 35.59         raise OSError(
#24 35.59     OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
```

**Environment**
On a M1 MacBookAir in MacOS 12.3.1 (latest)
(I also confirmed this occurs on ARM64 Ubuntu 20.04 running under Parallels on the same M1 Mac.)
Tutor 12.0.4

**Additional context**
I cannot use Maple and newer because of unfixed bugs which break my courses which forced me to revert to Lilac. I'll try again when Nutmeg is released. (Beyond which, it's my understanding that Maple on ARM64 doesn't work due to the mfe plugin not working, and the mfe plugin being required for my classes too, since when I tried Maple it was even more broken until I enabled MFE.)

Per recommendations on the internet I tried both "pip install geos" and "brew install geos", but neither yielded a different result (presumably because they're changing the state on macOS, not in the container?)

**Comment by regisb** [comment]
Hi,
Tutor v12 is no longer supported. There are solutions to run Tutor on ARM in v13. Please don't use GitHub issues for support.

https://docs.tutor.overhang.io/tutorials/arm64.html
https://docs.tutor.overhang.io/troubleshooting.html
