### ISSUE TITLE
tutor k8s start fails with no PatchStrategicMerge

### ISSUE THREAD

**Issue by edazzocaisser** [overhangio/tutor#704]
**Bug description**

We receive a kustomize error while running `tutor k8s start`:

```
Run tutor k8s start
kubectl get namespaces openedx-prod
NAME           STATUS   AGE
openedx-prod   Active   49d
Namespace already exists: skipping creation.
kubectl apply --kustomize /home/runner/.local/share/tutor/env --wait --selector app.kubernetes.io/component=volume
error: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- k8s/override.yml
`: patch appears to be empty; files=[k8s/override.yml], Patch=
Error: Command failed with status 1: kubectl apply --kustomize /home/runner/.local/share/tutor/env --wait --selector app.kubernetes.io/component=volume
Error: Process completed with exit code 1.
```
We don't specify a `k8s-override` patch, so [tutor/tutor/templates/k8s/override.yml ](https://github.com/overhangio/tutor/blob/master/tutor/templates/k8s/override.yml) results in an empty file.

**How to reproduce**

Please se above for most of the details.

I don't believe we have any manual changes to config.yml.

**Environment**

We're running this in a custom github action running on `ubuntu-latest`, using tutor version 14.0.3

Reverting to 14.0.2 fixed our automation.

**Additional context**

It looks like `patchesStrategicMerge` just needs to be omitted from [kustomization.yml](https://github.com/overhangio/tutor/blob/master/tutor/templates/kustomization.yml) when we're not customizing any base resources.

This is based on peeking at kustomize's [PatchStrategicMergeTransformer](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer.go#L50)

**Comment by regisb** [comment]
Resolved by #705.
