### ISSUE TITLE
ORA2 folder is incorrectly set

### ISSUE THREAD

**Issue by sambapete** [overhangio/tutor#707]
According to tutor/templates/apps/openedx/settings/partials/common_all.py
**ORA2_FILEUPLOAD_BACKEND = “filesystem”
ORA2_FILEUPLOAD_ROOT = “/openedx/data/ora2"
ORA2_FILEUPLOAD_CACHE_NAME = “ora2-storage”**

Unfortunately when using Tutor (v14.0.3), the directory **data/lms/ora2/'SET-ME-PLEASE (ex. bucket-name)'** is created and used instead.

This is the default value of AWS_STORAGE_BUCKET_NAME in edx-platform.

I've tried setting up AWS_STORAGE_BUCKET_NAME to a different value through a plugin but it keeps recreating the directory **data/lms/ora2/'SET-ME-PLEASE (ex. bucket-name)'**

Are the ORA2_* variables even used? Is ORA2 properly supported in Tutor?

Is there a way to change the value of AWS_STORAGE_BUCKET_NAME in Tutor?

**Comment by insad** [comment]
Isn't the minio plugin being used here? I'm myself trying to get video upload working, still fighting with CORS error from minio.

**Comment by sambapete** [comment]
Not using the Minio plugin. Just using the filesystem right now.

**Comment by sambapete** [comment]
I have no problems if using the minio plugin instead of using the filesystem. That could be a workaround for now if we decide to got his way. Thanks for the suggestion @insad

**Comment by regisb** [comment]
I can't believe I left this issue to rot for more than six months. Sorry Pierre! Working on a fix right now. The issue actually stems from the `FILE_UPLOAD_STORAGE_BUCKET_NAME` setting, which has defaulted to `AWS_STORAGE_BUCKET_NAME` since [June 2019](https://github.com/openedx/edx-platform/commit/993a21181a3)...
