### ISSUE TITLE
Bind mounting MFEs fails on dev

### ISSUE THREAD

**Issue by moonesque** [overhangio/tutor#711]
This bug has been [reported on tutor-mfe](https://github.com/overhangio/tutor-mfe/issues/57) but I believe it concerns tutor not tutor-mfe.

**Bug description**
Running `tutor dev start --mount=<MFE_PATH> <MFE_NAME>` results in docker-compose error. Please find the output for the command regarding the `profile` MFE from the [tutor-mfe readme](https://github.com/overhangio/tutor-mfe#mfe-development) in the **How to reproduce** section below.
I've tried the command using both syntaxes of `--mount`, running the commands in the `frontend-app-profile` directory:
`tutor dev start --mount=profile:.:/openedx/app`
and
`tutor dev start --mount=. profile`

**How to reproduce**
command: `tutor dev start --mount=. profile`
output:
```
Bind-mount: /home/mahan/projects/avid/mfe-dev/frontend-app-profile -> /openedx/app in profile
docker-compose -f /home/mahan/projects/avid/mfe-dev/tutor-13.3.1/env/local/docker-compose.yml -f /home/mahan/projects/avid/mfe-dev/tutor-13.3.1/env/local/docker-compose.prod.yml -f /home/mahan/projects/avid/mfe-dev/tutor-13.3.1/env/local/docker-compose.tmp.yml --project-name tutor_local stop
ERROR: The Compose file is invalid because:
Service profile has neither an image nor a build context specified. At least one must be provided.
Error applying action 'compose:project:started': func=<function _stop_on_dev_start at 0x7f2ce7811a60> contexts=[]'
Error: Command failed with status 1: docker-compose -f /home/mahan/projects/avid/mfe-dev/tutor-13.3.1/env/local/docker-compose.yml -f /home/mahan/projects/avid/mfe-dev/tutor-13.3.1/env/local/docker-compose.prod.yml -f /home/mahan/projects/avid/mfe-dev/tutor-13.3.1/env/local/docker-compose.tmp.yml --project-name tutor_local stop
```
mfe plugin is installed and enabled.

**Environment**
Ubuntu 20.04
Tutor version: 13.3.1
tutor-mfe version: 13.0.6

**Additional context**
The problem seems to be that running `tutor dev start` triggers `_stop_on_dev_start` ([code](https://github.com/overhangio/tutor/blob/698da4b1adfa9509876a9bd6b09cb755f87b137e/tutor/commands/local.py#L176)) which in turns calls `self.__update_docker_compose_tmp()` ([code](https://github.com/overhangio/tutor/blob/698da4b1adfa9509876a9bd6b09cb755f87b137e/tutor/commands/compose.py#L35)) on the runner which populates `/env/local/docker-compose.tmp.yml` with the volume configuration:
```
 services:
   profile:
     volumes:
     - /home/mahan/projects/avid/mfe-dev/frontend-app-profile:/openedx/app
 version: '3.7'
```
But since the profile mfe service is not defined in the `/env/local/docker-compose.prod.yml` docker-compose sees the service definition as insufficient.
I've gone through [this PR](https://github.com/overhangio/tutor/pull/657) by @kdmccormick which seems closely related.
I'm thinking a solution would be that services must only be added to `docker-compose.tmp.yml` files if such service exists in non temp files.

**Comment by regisb** [comment]
I'm currently working on a fix to this issue. In the meantime, it seems to me that Compose v2 is not affected by this issue. On my machine, I use `docker compose` instead of `docker-compose` (note the missing dash) and the issue does not occur. Thus, as a temporary fix, you may install Compose as a [Docker plugin](https://docs.docker.com/compose/install/compose-plugin/#installing-compose-on-linux-systems) and define the `TUTOR_USE_COMPOSE_SUBCOMMAND` environment variable: 

    export TUTOR_USE_COMPOSE_SUBCOMMAND=1

Of course this would only be a temporary fix.

Cc @dagg who might be interested in this.
