### ISSUE TITLE
Allow importing of custom demo courses

### ISSUE THREAD

**Issue by frob** [overhangio/tutor#730]
**Is your feature request related to a problem? Please describe.**

The provided demo course is a good representation of core edx functionality but what about when working with a customized installation. Often we will want to test custom or contributed xblocks which are not a part of the core product.

**Describe the solution you'd like**

It would nice to add an option to the `importdemocourse` command to allow for a custom demo course to be imported.

**Describe alternatives you've considered**

All other processes for this would be manual. Either manually creating a demo course or importing a demo course through the UI.

**Additional context**

I was thinking of something like this:

`tutor dev importdemocourse --path_to_course ./tests/democourse`

Looks like this is mostly just a built in script that does most the work. https://github.com/overhangio/tutor/blob/master/tutor/templates/hooks/cms/importdemocourse

```
echo "Loading settings $DJANGO_SETTINGS_MODULE"

# Import demo course
git clone https://github.com/openedx/edx-demo-course --branch {{ OPENEDX_COMMON_VERSION }} --depth 1 ../edx-demo-course
python ./manage.py cms import ../data ../edx-demo-course

# Re-index courses
./manage.py cms reindex_course --all --setup
```

I think this means we could we could override that template with a custom plugin but I think it would be far more useful to make this a part/feature of tutor so that it doesn't need to be hard coded.

**Comment by regisb** [comment]
Right. I see how custom courses would be a useful addition to the `importdemocourse` command. Currently, the corresponding import script cannot be templated with variables other than those coming from the Tutor configuration, so we will have to change that. It's certainly not impossible.

**Comment by frob** [comment]
Is there another script that uses arguments? I can take a first pass if there is an example job runner that has an argument.

**Comment by regisb** [comment]
Yes, the settheme command for instance.

Note that this issue is somehow related to this one: https://github.com/overhangio/2u-tutor-adoption/issues/75

**Comment by regisb** [comment]
This feature should be even easier now that pluggable "do" tasks are part of Tutor.
