### ISSUE TITLE
Unable to access courseware page with tutor 14.2.3

### ISSUE THREAD

**Issue by pcliupc** [overhangio/tutor#754]
**Bug description**
After creating a course in studio, unable to enter courseware page in LMS.
The link of courseware is abnormal:

> http://local.overhang.io/courses/course-v1:fira+test+2023/jump_to/None/course/course-v1:fira+test+2023

Also found some error logs in cms-worker:

> cms-worker_1                 | Traceback (most recent call last):
> cms-worker_1                 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/tasks.py", line 713, in update_outline_from_modulestore_task
> cms-worker_1                 |     update_outline_from_modulestore(course_key)
> cms-worker_1                 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/outlines.py", line 381, in update_outline_from_modulestore
> cms-worker_1                 |     course_outline_data, content_errors = get_outline_from_modulestore(course_key)
> cms-worker_1                 |   File "/opt/pyenv/versions/3.8.12/lib/python3.8/contextlib.py", line 75, in inner
> cms-worker_1                 |     return func(*args, **kwds)
> cms-worker_1                 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/outlines.py", line 341, in get_outline_from_modulestore
> cms-worker_1                 |     for section in course.get_children():
> cms-worker_1                 | AttributeError: 'NoneType' object has no attribute 'get_children'

**How to reproduce**

- start the platform with tutor 14.2.3: tutor local start
- login to studio and create a test course
- click "View Online"
- gets 404 "The page that you were looking for was not found. Go back to the [homepage](http://local.overhang.io/) ."

**Environment**

- mac os
- tutor 14.2.3

**Additional context**

**Comment by regisb** [comment]
Hey PengCheng, long time no see! Starting from Nutmeg, you need to enable the MFE plugin by default: https://github.com/overhangio/tutor-mfe/ In Nutmeg MFEs are a bit of a PITA because you need to rebuild the mfe Docker image all the f*cking time. But it's getting better in Olive, scheduled for Monday, which will deliver dynamic MFE configuration.

**Comment by pcliupc** [comment]
> Hey PengCheng, long time no see! Starting from Nutmeg, you need to enable the MFE plugin by default: https://github.com/overhangio/tutor-mfe/ In Nutmeg MFEs are a bit of a PITA because you need to rebuild the mfe Docker image all the f*cking time. But it's getting better in Olive, scheduled for Monday, which will deliver dynamic MFE configuration.

Hi Regis, good work and I will have a try. Thanks!
