### ISSUE TITLE
Duplicated changelog entries between v14 and v15

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/tutor#761]
**Bug description**

The [v15.0.0 notes](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md#v1500-2022-12-06) include several entries from the [v14.0.0 notes](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md#v1400-2022-06-09), including:
* [Bugfix] Remove edX references from bulk emails
* [Improvement] For Tutor Nightly (and only Nightly), official plugins are now installed from their nightly branches on GitHub instead of a version range on PyPI. This will allow Nightly users to install all official plugins by running pip install -e ".[full]".
* [Bugfix] Start MongoDB when running migrations, because a new data migration fails if MongoDB is not running

**How to reproduce**
n/a

**Environment**
n/a

**Additional context**

I assume this is something to do with the new Scriv-generated changelog, otherwise I would just open a PR against the changelog. I can take a look later, but I figured I'd open the issue in case someone knew a quick fix to it.

**Comment by regisb** [comment]
Good catch! It's enough to just modify the CHANGELOG file. The scriv workflow is really quite simple and straightforward, so that's all we need to do. I opened a PR.
