### ISSUE TITLE
Error loading Python lib during launch.

### ISSUE THREAD

**Issue by Llewellynvdm** [overhangio/tutor#765]
**Bug description**

```
[7893] Error loading Python lib '/tmp/_MEIcyvkMV/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIcyvkMV/libpython3.7m.so.1.0)
```

**How to reproduce**

Pull a Ubuntu 20.4 Image with 4 GB RAM, 2 vCPUs, 80 GB SSD up on [Lightsail](https://lightsail.aws.amazon.com) -AWS

Once signed in, create script `install.sh` add the following to it, give execution rights `sudo chmod +x install.sh` and run.
```
#!/bin/bash

sudo hostnamectl set-hostname ourname.education
sudo apt update

sudo mkdir -p /etc/apt/keyrings &&
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg &&
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
sudo apt-get update && sudo apt-get upgrade -y

sudo apt-get remove docker \
    docker-engine \
    docker.io \
    containerd \
    runc

sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
    
sudo apt-get install \
    python3. \
    python3-pip \
    libyaml-dev -y
    
sudo apt-get install docker-ce docker-ce-cli containerd.io -y

sudo curl -SL https://github.com/docker/compose/releases/download/v2.14.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

sudo chmod 0755 /usr/local/bin/docker-compose && sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

sudo groupadd docker

sudo usermod -aG docker $USER

sudo systemctl enable docker.service
sudo systemctl enable containerd.service

sudo curl -L "https://github.com/overhangio/tutor/releases/download/v15.1.0/tutor-$(uname -s)_$(uname -m)" -o /usr/local/bin/tutor
sudo chmod 0755 /usr/local/bin/tutor

tutor local launch
```

**Environment**

AWS server Ubuntu 20.4 Image with 4 GB RAM, 2 vCPUs, 80 GB SSD 

**Additional context**

I am running a v12.x Tutor instance and have not upgraded it as yet, first wanted to test the newer versions, any idea what my be the cause... I have of course Googled this to death already, and have tried number of different fixes. But alas I know to little about Phyton environmental setup, please help!

**Comment by Llewellynvdm** [comment]
Also tried this with 8 GB RAM, 2 vCPUs, 160 GB SSD.

**Comment by regisb** [comment]
> [7893] Error loading Python lib '/tmp/_MEIcyvkMV/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIcyvkMV/libpython3.7m.so.1.0)

Is this the full error context? I'm trying to figure out whether the error comes from tutor or docker-compose. What is the output of `tutor --version`?

**Comment by Llewellynvdm** [comment]
Hey sorry for the delay... its output is `tutor, version 14.0.5`

**Comment by Llewellynvdm** [comment]
Hmmm that was my last try.. since I could not get the 15.1.0 to work. Which means when I opened this issue it was the output would have been `tutor, version 15.1.0`

In fact let me dump this instance and run the bash script I [wrote here](https://github.com/overhangio/tutor/issues/765#issue-1505234317). One moment...

**Comment by Llewellynvdm** [comment]
Okay so I setup the whole system with my script... and then ran a few commands to see the output.

![image](https://user-images.githubusercontent.com/5607939/210757886-08c8dc78-6f61-4c67-9995-6fe5217f17b5.png)

So it does not work...

**Comment by regisb** [comment]
Right. The binary release of Tutor is failing on your system because you are running an older version (20.04) of Ubuntu than the one the binary was built with (22.04). Basically, you are facing this issue: https://github.com/pyinstaller/pyinstaller/issues/7033

It's not your fault: we should be building the tutor binary with the oldest possible release of Ubuntu/MacOS, as discussed here: https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible

We'll push a fix to build the binary with an older release of Ubuntu. In the meantime, I suggest that you install Tutor not by downloading the binary, but with `pip install`:

```
sudo rm /usr/local/bin/tutor
pip install --user tutor[full]
```

Moreover, this will allow you to install custom plugins, as explained here: https://docs.tutor.overhang.io/install.html#binary-release

These two issues (backward compatibility and plugin detection) are the reason why we do not recommend the binary releases as the default installation method anymore.

**Comment by Llewellynvdm** [comment]
Thank you.. (wow I did not catch that) hmm AWS only has Ubuntu 20.04 on the Lightsail area. I will try a EC2 container... that should work.

Anyway I really appreciate your help, thanks!
