### ISSUE TITLE
Broken 'Pages' view in Studio is back in Tutor 14 / Nutmeg

### ISSUE THREAD

**Issue by angonz** [overhangio/tutor#769]
**Bug description**
The old problem with Pages in Studio is back in Nutmeg is back.
It was described and patched in [Open edX's PR #30550](https://github.com/openedx/edx-platform/pull/30550). This patch was [cherry picked](https://github.com/openedx/edx-platform/pull/30550#issuecomment-1148464626) in Tutor for the [14.0.0 release](https://github.com/overhangio/tutor/pull/635/files#diff-ebe2aa009411bb8f1a30abe8461ed746d5c8f5869aec9ec7e9221b4ff40960d1) and [improved later to use git am](https://github.com/overhangio/tutor/commit/e5850eb02e202b2f4c0fe56e51d04a1f213f1857#diff-ebe2aa009411bb8f1a30abe8461ed746d5c8f5869aec9ec7e9221b4ff40960d1).
Now the [original patch](https://github.com/open-craft/edx-platform/commit/3d54f284f82b61e693ad652d8d6e46a226fcb36d.patch) for some reason disappeared and the `tutor build images openedx` raises a 404 error:
```
Step 22/111 : RUN curl -fsSL https://github.com/open-craft/edx-platform/commit/3d54f284f82b61e693ad652d8d6e46a226fcb36d.patch | git am
 ---> Running in 3d18bd335af2
curl: (22) The requested URL returned error: 404 
```

The original PR was merged in [a new commit](https://github.com/openedx/edx-platform/commit/8169aa99da32902b00a7f76a20c627ea1d44576c) for Olive. I tried to cherry pick this patch instead, but it fails because `xmodule` was [moved to the root folder](https://github.com/openedx/edx-platform/pull/30394) and the patch does not work anymore as-is:
```
 => ERROR [code 4/8] RUN curl -fsSL https://github.com/openedx/edx-platform/commit/8169aa99da32902b00a7f76a20c627ea1d44576c.patch | git am                            1.6s
------                                                                                                                                                                     
 > [code 4/8] RUN curl -fsSL https://github.com/openedx/edx-platform/commit/8169aa99da32902b00a7f76a20c627ea1d44576c.patch | git am:                                       
#14 1.481 error: xmodule/tabs.py: does not exist in index
#14 1.481 hint: Use 'git am --show-current-patch' to see the failed patch
#14 1.481 Applying: fix: if pages and resources view is disabled, show all pages in studio (#30550)
#14 1.481 Patch failed at 0001 fix: if pages and resources view is disabled, show all pages in studio (#30550)
#14 1.481 When you have resolved this problem, run "git am --continue".
#14 1.481 If you prefer to skip this patch, run "git am --skip" instead.
#14 1.481 To restore the original branch and stop patching, run "git am --abort".
------
```

The problem should not happen in Olive, as the patch is already merged. It will happen only in Tutor 14/Nutmeg where the openedx docker image is built after the [original patch](https://github.com/open-craft/edx-platform/commit/3d54f284f82b61e693ad652d8d6e46a226fcb36d.patch) disappeared.

I've made a naughty patch, by changing the [patch](https://github.com/overhangio/tutor/blob/3772bda4380a0a990e53170b51bfa172a468f4e4/tutor/templates/build/openedx/Dockerfile#L52) in `tutor/templates/build/openedx/Dockerfile` to:

```
# Fix broken "Pages" view in Studio
# https://github.com/openedx/edx-platform/pull/30550
RUN curl -fsSL https://github.com/openedx/edx-platform/commit/8169aa99da32902b00a7f76a20c627ea1d44576c.patch | sed "s/xmodule\/tabs/common\/lib\/xmodule\/xmodule\/tabs/" | git am
```

What do you suggest?

**How to reproduce**

``` 
tutor images build openedx --no-cache
```

**Environment**
Tutor 14.x.x / Nutmeg

**Comment by regisb** [comment]
Thanks for the detailed report. I'll add the patch to a nutmeg branch in our private repo, and will release v14.2.4.
