### ISSUE TITLE
No Nutmeg.3 in tutor v14 releases?

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#770]
Hi @regisb 
I was looking around and noticed that unlike version 13 (which tutor supported all maple releases, on the latest version of 14 (14.2.3) `open-release/nutmeg.2` is set (there is an `open-release/nutmeg.3` in `edx-platform` repo available). 

https://github.com/overhangio/tutor/blob/3772bda4380a0a990e53170b51bfa172a468f4e4/tutor/templates/config/defaults.yml#L55

is there anything wrong with the `nutmeg.3`, or that was left out?
if so, can we add it as version 14.2.4?

**Comment by regisb** [comment]
Nutmeg.3 only introduces a minor Django upgrade. It's too much work to also upgrade the i18n strings (Tutor depends on openedx-i18n) so I'd rather not bump the OPENEDX_COMMON_VERSION. Instead, I opted to cherry-pick the Django upgrade in edx-platform. This does not take care of other IDAs but I feel like it's the right compromise. The fix will be v14.2.4, to be released in a few minutes.

**Comment by CodeWithEmad** [comment]
Yes, I got it @regisb 
Because Tutor is so awesome and so complete, I was surprised that you did not have Nutmeg.3 in the latest version 14.
btw. thanks for the quick response and v14.2.4 :)
