### ISSUE TITLE
How to run tutor outside docker?

### ISSUE THREAD

**Issue by cursedgrape** [overhangio/tutor#789]
I want to run tutor outside docker using `manage.py runserver`, what would be the best way to approach this / documentation I should check?

**Comment by erickhgm** [comment]
@cursedgrape 
What was your conclusion about it?

**Comment by cursedgrape** [comment]
I failed to modify openedx code to be compatible with `manage.py runserver` and I'm no longer interested in doing so since the code proved to be nearly impossible to work with.
