### ISSUE TITLE
Recommended hardware and custom template of Tutor

### ISSUE THREAD

**Issue by nguyenthanhtien** [overhangio/tutor#796]
1-With Recommended configuration: "8 GB RAM, 4 CPU, 25 GB disk space", how many concurrent user it can handle.
2-With Open Edx, do we have any store can buy template? Or we should custom template. If need custom template, how can we can custom that, any guide for this?

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
