### ISSUE TITLE
Enable a better way to extend the uwsgi command

### ISSUE THREAD

**Issue by jfavellar90** [overhangio/tutor#807]
**Is your feature request related to a problem? Please describe.**

We would like to extend the options offered by the [uwsgi command](https://github.com/overhangio/tutor/blob/master/tutor/templates/build/openedx/Dockerfile#L251) in the OpenedX Dockerfile to satisfy different use cases. Right now the only way to do so is to create an [override](https://github.com/overhangio/tutor/blob/master/tutor/templates/k8s/override.yml) that allows patching the command the OpenedX pods run, as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  template:
    spec:
      containers:
        - name: cms
          args:
            - |
              uwsgi \
              --static-map /static=/openedx/staticfiles/ \
              --static-map /media=/openedx/media/ \
              --http 0.0.0.0:8000 --thunder-lock \
              --single-interpreter --enable-threads \
              --processes=${UWSGI_WORKERS:-2} \
              --buffer-size=8192 \
              --wsgi-file $SERVICE_VARIANT/wsgi.py \
              --extra-arg1 \
              --extra-arg2
          command: ["/bin/bash", "-c"]
```
We have to rewrite the whole command and add the extra arguments.

**Describe the solution you'd like**

My teammate @MoisesGSalas is working on a [PR](https://github.com/overhangio/tutor/compare/master...eduNEXT:tutor:mgs/configurable-uwsgi) that allows configuring the uwsgi process via a mounted file in the container. This file is added to the templates and exposes a patch to enable adding custom uwsgi settings. We think this is a smoother approach to modify the behavior of a critical process of the platform operation and keep track of those changes.

**Comment by regisb** [comment]
> My teammate @MoisesGSalas is working on a [PR](https://github.com/overhangio/tutor/compare/master...eduNEXT:tutor:mgs/configurable-uwsgi) that allows configuring the uwsgi process via a mounted file in the container. This file is added to the templates and exposes a patch to enable adding custom uwsgi settings. We think this is a smoother approach to modify the behavior of a critical process of the platform operation and keep track of those changes.

I agree. Let's discuss on the PR.

**Comment by regisb** [comment]
Closed by https://github.com/overhangio/tutor/pull/808.
Thanks!
