### ISSUE TITLE
OPENEDX_EXTRA_PIP_REQUIREMENTS not used in tutor local launch

### ISSUE THREAD

**Issue by bmtcril** [overhangio/tutor#818]
**Bug description**
In a fresh nightly environment (tutor dirs removed, `docker system prune` all), running `tutor local launch` with the "not production" setting seems to be running in a prod container and not picking up a plugin's `OPENEDX_EXTRA_PIP_REQUIREMENTS` in the `CONFIG_DEFAULTS` section.

Similar to the issue fixed [here](https://github.com/overhangio/tutor/commit/732e0c43be5b801b7c62892bdc9b44bc74b7263f), running `tutor images build openedx` installs the dependency so that subsequent `tutor local launch` commands find it, but in this case does it did not run migrations for that requirement. I had to run them by hand in the container.

**How to reproduce**
- Set up a fresh tutor nightly build
- Install the OARS plugins (currently only through github editable installs):
  - https://github.com/openedx/tutor-contrib-clickhouse
  - https://github.com/openedx/tutor-contrib-superset
  - https://github.com/openedx/tutor-contrib-oars
  - https://github.com/openedx/tutor-contrib-ralph
- Enable the above plugins
- `tutor config save`
- `tutor local launch`, select "No" for configuring a production platform
- Eventually you should see the error `LookupError: No installed app with label 'event_routing_backends'.`
- `tutor images build openedx` should install event_routing_backends
- `tutor local launch` again, still select "No" for configuring a production platform
- Eventually you should see the error `django.db.utils.ProgrammingError: (1146, "Table 'openedx.event_routing_backends_routerconfiguration' doesn't exist")`
- Get a terminal on the running LMS container and run `./manage.py lms runmigrations`, you should see the event_routing_backends table get created
- `tutor local stop`
- `tutor local launch` (again not a production platform)
- Startup should succeed

**Environment**
Mac OS, `tutor, version 15.3.2-nightly`

Plugins:
```
NAME      	STATUS   	VERSION
android   	installed	15.0.0
arm64     	enabled  	0.1.0
clickhouse	enabled  	0.1.0
discovery 	installed	15.0.0
ecommerce 	installed	15.0.2
forum     	installed	15.1.0
license   	installed	15.0.0
mfe       	enabled  	15.0.5
minio     	installed	15.1.0
notes     	installed	15.0.2
oars      	enabled  	0.1.0
ralph     	enabled  	0.1.0
superset  	enabled  	0.1.0
webui     	installed	15.0.0
xqueue    	installed	15.0.0
```

**Additional context**
After the committed fix above, I no longer run into this issue in `tutor dev launch`, and I don't believe that ever had the problem with the migrations. 

You may see `AssertionError: openedx.None table doesn't exist yet?` in the output, this is a known issue in one of the plugins and shouldn't be related.

**Comment by regisb** [comment]
> In a fresh nightly environment (tutor dirs removed, docker system prune all), running tutor local launch with the "not production" setting seems to be running in a prod container and not picking up a plugin's OPENEDX_EXTRA_PIP_REQUIREMENTS in the CONFIG_DEFAULTS section.

 Right. Modifying this setting requires re-building the "openedx" Docker image. The docs do not make this clear at all.

> Eventually you should see the error django.db.utils.ProgrammingError: (1146, "Table 'openedx.event_routing_backends_routerconfiguration' doesn't exist")

At what point of the app life cycle does this error occur, and what is the full stacktrace? I'm a little surprised that it happens at all and that a simple `runmigrations` command resolves it. `tutor local launch` does trigger app initialization, including applying migrations. So if the error occurs it means that the LMS app is trying to reach the MySQL database before the migrations are applied -- and I do not understand how this could be happening.

>  After the committed fix above, I no longer run into this issue in tutor dev launch, and I don't believe that ever had the problem with the migrations.

You mean that you are facing the issue with `tutor local launch` but not with `tutor dev launch`?

**Comment by bmtcril** [comment]
Hey Regis, thanks for taking a look. I think this is all my misunderstanding of which things are happening at what time. I had installed all of my plugins before ever running `launch` so had an expectation that I wouldn't need to rebuild the image, and I somehow always landed on the definition of `OPENEDX_EXTRA_PIP_REQUIREMENTS` in the docs, which doesn't mention the rebuild, and didn't finish reading down the doc where it is totally covered. Then rebuilding the image didn't run the migrations, which is obvious in retrospect.

I'll close this out, but if you'd like I can contribute a doc pr to cover the need to rebuild the image and run migrations if you change `OPENEDX_EXTRA_PIP_REQUIREMENTS` in the params section.

**Comment by regisb** [comment]
> I'll close this out, but if you'd like I can contribute a doc pr to cover the need to rebuild the image and run migrations if you change OPENEDX_EXTRA_PIP_REQUIREMENTS in the params section.

Yes, that would be great, thanks! To be clear, changing this setting requires:

1. building the Docker image
2. Running migrations, either via `tutor local launch` or `tutor local do init`.
