### ISSUE TITLE
k8s Caddy error

### ISSUE THREAD

**Issue by vunguyen-dmt** [overhangio/tutor#820]
I usually get this error when many users access LMS, I'm using HPA and AWS Auto scaling group.
My HPA implementation is similar to [this one](https://github.com/eduNEXT/tutor-contrib-pod-autoscaling).
The node that caddy pod  was initially created was still running.
I don't know why caddy pod get reschedule and why It could not be  scheduled.

Here is the log from EKS.
`"Unable to schedule pod; no fit; waiting" pod="openedx/caddy-5fb779f45c-tg2wt" err="0/5 nodes are available: 2 node(s) had taint {node.kubernetes.io/memory-pressure: }, that the pod didn't tolerate, 3 node(s) had volume node affinity conflict."`

Here is the log from server
```
 kubectl describe pod caddy-5fb779f45c-tq7rh -n openedx
Name:           caddy-5fb779f45c-tq7rh
Namespace:      openedx
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/instance=openedx-plgptrNC3o7G6spZEFp2SVx1
                app.kubernetes.io/managed-by=tutor
                app.kubernetes.io/name=caddy
                app.kubernetes.io/part-of=openedx
                pod-template-hash=5fb779f45c
Annotations:    app.kubernetes.io/version: 15.2.0
                kubernetes.io/psp: eks.privileged
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/caddy-5fb779f45c
Containers:
  caddy:
    Image:       docker.io/caddy:2.4.6
    Ports:       80/TCP, 443/TCP
    Host Ports:  0/TCP, 0/TCP
    Environment:
      default_site_port:
    Mounts:
      /data/ from data (rw)
      /etc/caddy/ from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zlgnf (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      caddy-config-ck599h2cg8
    Optional:  false
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  caddy
    ReadOnly:   false
  kube-api-access-zlgnf:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  36s   default-scheduler  0/5 nodes are available: 2 node(s) had taint {node.kubernetes.io/memory-pressure: }, that the pod didn't tolerate, 3 node(s) had volume node affinity conflict.
```

**Comment by vunguyen-dmt** [comment]
My guress is caddy pv, pvc were created on *-1b availability zone (az) and available nodes were created on *-1a az.
If it is true then will making caddy pvc and nodes in the same az fix the problem?
If I want to use multiple az for my nodes, how can I fix this?

**Comment by regisb** [comment]
Hi! I believe that this issue is related to your use of either HPA or AWS Auto scaling group. I strongly recommend you do not auto-scale the caddy container.

Unfortunately this is not really the place to investigate such issue. GitHub issues are not for troubleshooting users. Please open a topic in the Open edX community forum: https://discuss.openedx.org/
