### ISSUE TITLE
tutor database

### ISSUE THREAD

**Issue by zonair302** [overhangio/tutor#825]
https://docs.tutor.overhang.io/tutorials/datamigration.html#making-backups-and-migrating-data
Hi everyone 
i'm install the tutor and create admin and multiple user  in it now i'm trying to take a backup of the tutor service but i can't find the database services of mysql and mongodb 
can anyone tell me where the services is runing?

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
