### ISSUE TITLE
Ability to modify the order in which plugins are loaded

### ISSUE THREAD

**Issue by kaustavb12** [overhangio/tutor#835]
**Is your feature request related to a problem? Please describe.**

Currently in tutor, plugins are [loaded in alphabetical order](https://github.com/overhangio/tutor/blob/2e276cbb09c47e177bca6c0bcd44aee53bb5a0b6/tutor/plugins/__init__.py#L73). There is no way to modify this order for a tutor based installation.

This is problemetic in scenarios where a patch setting from one plugin overrides(or might want to override) the same patch setting from another plugin. (Example, we might want to configure a custom plugin to override some settings from tutor-mfe)

**Describe the solution you'd like**

A possible soultion could be to load the plugins in order in which it is present in `config.yml`. This way we would be able to manually alter the config file to change the order.

OR perhaps we could optionally assign priority to the plugins similar to the priority of actions, with some defaults.

**Describe alternatives you've considered**

A way to hack around this currently, is to use the [PLUGINS_LOADED Action](https://github.com/overhangio/tutor/blob/master/tutor/hooks/catalog.py#L110) to load our patches from a custom plugin after all other plugins have been loaded.

**Additional context**

**Comment by regisb** [comment]
It is already possible to do the following:

```
hooks.Filters.ENV_PATCHES.add_items([
   ...
], priority=hooks.priorities.LOW)
```

With this low priority, your patches will be applied last. Does this resolve your issue?

**Comment by kaustavb12** [comment]
@regisb Yes this is exactly what I was looking for. It seems it was introduced with v15, while I am currently working with v14 and so missed it.

Thanks a lot for the response. Closing the issue now.
