### ISSUE TITLE
`uwsgi.ini` should not be copied to bind-mounted edx-platform

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#846]
**Is your feature request related to a problem? Please describe.**

When we bind-mount edx-platform in the lms/cms container, uwsgi.ini is copied to the host directory. As a consequence, `git status` reports some modified contents.

@bradenmacdonald helpfully reported this issue [here](https://github.com/openedx/edx-platform/pull/32268) and suggested to fix it by git-ignoring uwsgi.ini in edx-platform. But I think that the issue should be resolved in Tutor.

**Describe the solution you'd like**

Tutor tries to avoid putting extra files in edx-platform. We should follow this rule of thumb and move uwsgi.ini outside of edx-platform. The problem is that `/openedx` has become quite a mess in the lms/cms containers:

```
$ tutor local run --no-deps lms ls /openedx
bin     data          locale  nodeenv       requirements  themes
config  edx-platform  media   node_modules  staticfiles   venv
```

We should take the chance to reorganize this directory.

**Comment by DawoudSheraz** [comment]
For now, let's move uwsgi.ini one step out i.e. to openedx directory. The re-org of openedx directory itself should be done separately as I suspect it will involve some discussion. I will create an issue for that.

**Comment by DawoudSheraz** [comment]
WIP PR https://github.com/overhangio/tutor/pull/1036
