### ISSUE TITLE
"General"  Discussion template not visible in course tabs of a brand new course

### ISSUE THREAD

**Issue by cleary** [overhangio/tutor#850]
**Bug description**

No "Discussion" tab is visible on a newly created course - it's enabled, but doesn't appear anywhere I expect
 
![Screenshot_20230607_063208](https://github.com/overhangio/tutor/assets/2577966/2be9a10c-690b-4416-b34b-4999c96d715c)

![Screenshot_20230607_062914](https://github.com/overhangio/tutor/assets/2577966/80d91402-e51a-40d6-aa4e-1ac9826a7b86)/

![Screenshot_20230607_063014](https://github.com/overhangio/tutor/assets/2577966/406f96a8-cbee-44b7-8695-eb2651ca236e)

**How to reproduce**

```
tutor local launch
```
Log into StudioX and create a new course - according to all my reading, there should be a default "General" discussion tab alongside the  Course, Progress, Dates, Instructor tabs

**Environment**

Ubuntu 22.04
tutor, version 15.3.6

**Additional context**

Possibly related to #847 ?

**Comment by regisb** [comment]
For this issue and #847, did you install and enable the [forum plugin](https://github.com/overhangio/tutor-forum/)?

As a rule of thumb, please open a discussion topic on the Open edX forum prior to opening an issue here. (see the [troubleshooting](https://docs.tutor.overhang.io/troubleshooting.html) section from the docs)

**Comment by cleary** [comment]
> For this issue and #847, did you install and enable the [forum plugin](https://github.com/overhangio/tutor-forum/)?
> 
Aha, my apologies that was exactly it (although it looked for all intents and purposes that it was already installed/enabled as per the screenshots) 


> As a rule of thumb, please open a discussion topic on the Open edX forum prior to opening an issue here. (see the [troubleshooting](https://docs.tutor.overhang.io/troubleshooting.html) section from the docs)

Got it, thankyou - I did not know to do so, but will in future.

(It might be useful to mention that in the issue template comments?)

Thankyou for the swift and informative response

**Comment by regisb** [comment]
> (It might be useful to mention that in the issue template comments?)

Isn't that already the case? https://github.com/overhangio/tutor/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by cleary** [comment]
> > (It might be useful to mention that in the issue template comments?)
> 
> Isn't that already the case? https://github.com/overhangio/tutor/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Hi,
You are correct, the forums are mentioned:
> Is this a bug in Tutor, or in Open edX? Open edX bugs should not be reported here, but in the Open edX bug tracker: https://openedx.atlassian.net/

But in this context, based on 
 - info from the course I'm doing saying that Discussions are standard components of edx,
 - the threads I found with matching error messages 
 - no mention of the error in the troubleshooting section

then I resolved that the issue *must* have been with the tutor deployment - therefore I went straight to github.

I was proposing that you could explicitly request asking any question on the forums first - 

I did my best to do the right thing based on the instructions given, but without knowledge of Discussions existing in tutor as a discrete module, and no other information on the topic I was able to find (asides from a `bundle rake` call that was unclear on *where* it should be run), posting an issue here was what I understood to be the correct action.

Apologies, and thanks again for the assistance :)
