### ISSUE TITLE
Default MongoDB release is 4.2.17; this is no longer recommended for production use

### ISSUE THREAD

**Issue by fghaas** [overhangio/tutor#854]
**Bug description**

`DOCKER_IMAGE_MONGODB`, as set in `tutor/templates/config/defaults.yml`, defaults to `docker.io/mongo:4.2.17`.

The latest available MongoDB release in the 4.2 release series is 4.2.24. The MongoDB [release notes](https://www.mongodb.com/docs/manual/release-notes/4.2/) for that series

* list all versions from 4.2.0 to 4.2.23 as having a critical issue ([WT-10461](https://jira.mongodb.org/browse/WT-10461)), 
* identifies them as "not recommended for production use",
* recommends to use "the latest available patch release version instead."

As a result, it's probably a good idea to bump the default.

**How to reproduce**

```console
$ yq e .DOCKER_IMAGE_MONGODB tutor/templates/config/defaults.yml
docker.io/mongo:4.2.17
```

**Environment**

```console
$ tutor --version
tutor, version 15.3.6
```

**Additional context**

The fix for this *should* only amount to bumping the `DOCKER_IMAGE_MONGODB` default, and updating `docs/configuration.rst`. But of course, testing is of rather paramount importance. :)

**Comment by regisb** [comment]
Thanks for the heads-up Florian! We are only ~48h from the Palm release, which will run mongodb 4.4, but we still want to get that 4.2.23 upgrade while we are in Olive, such that users who remain on v15 still get the upgrade.

Would you like to open a PR? It should be sufficient to replace all instances of 4.2.17 by 4.2.23 in the source code, as you noticed.

**Comment by fghaas** [comment]
@regisb I've opened #855 but I've deliberately made it a draft because I can't guarantee that we'll be able to test this within the next 48 hours. If you can run a test and you're confident that everything works fine with 4.2.24, then please let me know and I'll mark the PR as ready for review after adding a `Co-authored-by` tag for you. Does that work?

**Comment by regisb** [comment]
I've tested the PR and it works for me. I can switch it to "ready for review" and merge it -- as far as I'm concerned it's not necessary to add me as a co-author.
