### ISSUE TITLE
Adding E-Commerce module

### ISSUE THREAD

**Issue by jetatomic** [overhangio/tutor#86]
As per [README.md ](https://github.com/regisb/openedx-docker#known-missing-features-discovery-service-ecommerce-analytics), I'd like to put in a vote for adding the **ecommerce** feature.
> ## Known missing features: discovery service, ecommerce, analytics
> 
> Those extra services were considered low priority while developing this project. However, most of them should not be too hard to add to a standard install. If you need one or more of these services, feel free to let me know by opening an issue.

I saw in issue #58 that **analytics** is particularly difficult, and I'm hoping **ecommerce** is somewhat simpler.

@dangtrinhnt has a good post on [adding the ecommerce module to the Bitnami Open edX docker stack](https://www.dangtrinh.com/2018/07/how-to-install-e-commerce-module-in.html). And @lpm0073 has a helpful post for [setting up ecommerce in the Native Open edX Ubuntu 16.04 64 install](https://blog.lawrencemcdaniel.com/open-edx-ecommerce/). But I haven't been successful integrating that information into non-Bitnami Docker.

**Comment by regisb** [comment]
Duly noted :) which payment platform would you be most interested in? And would you accept to pay a yearly fee to get this feature, among others, in a commercial edition?

**Comment by jetatomic** [comment]
Probably Stripe.

Open edX has been such a hassle to set up that I haven't fully evaluated it, so I can't even guesstimate pricing structures. It would be a big leap to adopt a platform that doesn't officially support Docker images. It's awesome that you've assembled this, but I'm not sure I could commit to edX until they transitioned more than Devstack to containers.

Just my personal preference, but most of the platforms I choose are free to install, then have paid options for customization and support.

**Comment by kevin-og** [comment]
I'd like to see Tutor include the e-commerce module pre-configured as well.  Thanks for all you do, @regisb

**Comment by AhmadiEhsan** [comment]
it will be fantastic to add ecommerce and discovery service as well

**Comment by regisb** [comment]
Would anyone be willing to sponsor the development of discovery and ecommerce plugins?

**Comment by regisb** [comment]
These features now exist as plugins:
https://github.com/overhangio/tutor-discovery
https://github.com/overhangio/tutor-ecommerce
