### ISSUE TITLE
Kubernetes config.load_incluster_config() doesn't work when called from inside a job created from Github Actions runner

### ISSUE THREAD

**Issue by lpm0073** [overhangio/tutor#860]
**Bug description**
This problem surfaces in tutor v15 and later, due to this [commit](https://github.com/overhangio/tutor/commit/86f846aba35caa4fde7536200e4b9bd42fcc8531), which breaks when tutor is running from inside of a Github Actions runner node.  Specifically, config.load_incluster_config() is unable to find the local cert and token for the k8s api.

For reference, here's the [v14.2.3 code](https://github.com/overhangio/tutor/blob/v14.2.3/tutor/commands/k8s.py) code, which works perfectly.

Oddly, this error only surfaces from Github Actions runners, but not on any other environment I tried. Prior to this exception being raised, my deployment workflow along with tutor itself make more than a dozen successful requests to the k8s api, albeit using config.load_kube_config().

This is the problematic code block. 
```
        if os.path.exists(config.kube_config.KUBE_CONFIG_DEFAULT_LOCATION):
            # found the kubeconfig file, let's load it!
            config.load_kube_config()
        elif (
            config.incluster_config.SERVICE_HOST_ENV_NAME in os.environ
            and config.incluster_config.SERVICE_PORT_ENV_NAME in os.environ
        ):
            # We are running inside a cluster, let's load the in-cluster configuration.
            config.load_incluster_config()
        else:
            raise exceptions.TutorError(
                f"there is no Kubernetes configuration file located in {config.kube_config.KUBE_CONFIG_DEFAULT_LOCATION}, and the service environment variables {config.incluster_config.SERVICE_HOST_ENV_NAME} and {config.incluster_config.SERVICE_PORT_ENV_NAME} have not been defined. To connect to a cluster, please configure your host appropriately."
            )
```

I traced the code back to the [kubernetes.config repository](https://github.com/kubernetes-client/python/blob/master/kubernetes/base/config/kube_config.py#L48), and based on that code I can see that when authenticating in_cluster it relies on these two environment variables:
```
KUBERNETES_SERVICE_HOST=kubernetes.default.svc
KUBERNETES_SERVICE_PORT=443
```

Note that I can see both of these environment variables inside of any deployed pod. KUBERNETES_SERVICE_HOST generally contains the public IP address for the Kubernetes service. But the name I provided above should also work.

<img width="1471" alt="Screenshot 2023-06-15 at 14 51 16" src="https://github.com/overhangio/tutor/assets/1178819/eefe1e2d-cd64-42a4-a82b-aacbc72e42f1">

**How to reproduce**
execute `Run tutor k8s start` from a Github Actions runner node after having installed and configured kubectl

```
Initialising all services...
Running init task in lms
Error: there is no Kubernetes configuration file located in ~/.kube/config, and the service environment variables KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT have not been defined. To connect to a cluster, please configure your host appropriately.
```

**Environment**
TUTOR_OPENEDX_COMMON_VERSION=open-release/nutmeg.3"
ubuntu-latest
aws-cli/2.11.27 Python/3.11.3 Linux/5.15.0-1039-azure exe/x86_64.ubuntu.22 prompt/off
kubectl: {
  "major": "1",
  "minor": "27+",
  "gitVersion": "v1.27.2-eks-c12679a",
  "gitCommit": "002c6bc4e142b1f48b9405140e559194a094dcff",
  "gitTreeState": "clean",
  "buildDate": "2023-05-22T20:23:13Z",
  "goVersion": "go1.20.4",
  "compiler": "gc",
  "platform": "linux/amd64"
}
Kustomize Version: v5.0.1
Server Version: v1.27.2-eks-c12679a
Hosted on AWS Elastic Kubernetes Service in ca-central-1 data center
tutor                          15.3.7              
tutor-contrib-k8s-deploy-tasks 15.0.0              
tutor-contrib-s3               14.0.2              
tutor-discovery                15.0.0              
tutor-mfe                      15.0.7              
tutor-notes                    15.0.4

**Comment by regisb** [comment]
@CodeWithEmad FYI.

@lpm0073 please help me get to the bottom of this. If I understand correctly, your "happy path" would be calling `config.load_kube_config()`, just like in v14, right?

I think I may have a clue about what's going wrong. The default kube config path includes a tilde "~": `KUBE_CONFIG_DEFAULT_LOCATION = os.environ.get('KUBECONFIG', '~/.kube/config')`

This tilde is later expanded in the kubernetes module, but when we check for the file presence it fails if we don't expand it:

```
$ python -c "import os; print(os.path.exists('~'))"
False
```

Thus, to resolve the issue we need to check `if os.path.exists(os.path.expanduser(config.kube_config.KUBE_CONFIG_DEFAULT_LOCATION))` instead of just `if os.path.exists(config.kube_config.KUBE_CONFIG_DEFAULT_LOCATION)`.

I'll push a fix to v16 and v15 right now.

**Comment by regisb** [comment]
Side note: you should really, _really_ not run nutmeg with tutor v15. Instead, you should run v14.

**Comment by lpm0073** [comment]
Thanks! 
Re the side note: this was related to my work to refactor the Cookiecutter build-deploy workflows for Olive. Nutmeg never really saw the light of day.
