### ISSUE TITLE
Render nested list variables

### ISSUE THREAD

**Issue by Ian2012** [overhangio/tutor#867]
**Is your feature request related to a problem? Please describe.**

In a tutor plugin, when trying to render something similar to this:

```python
        (
            "SUPERSET_BASE_ROW_LEVEL_SECURITY_FILTERS",
            [
                {
                    "schema": "{{ ASPECTS_XAPI_DATABASE }}",
                    "table_name": "{{ ASPECTS_XAPI_TABLE }}",
                    "role_name": "{{ SUPERSET_OPENEDX_ROLE_NAME }}",
                    "group_key": "{{ SUPERSET_ROW_LEVEL_SECURITY_XAPI_GROUP_KEY }}",
                    "clause": "{{can_view_courses(current_username(),"
                    "\"splitByChar(\"/\", course_id)[-1]\")}}",
                    "filter_type": "Regular",
                },
            ],
        ),
```

Those are rendered as a raw string and are not interpolated:
`x = [{'schema': '{{ ASPECTS_XAPI_DATABASE }}', 'table_name': '{{ ASPECTS_XAPI_TABLE }}', 'role_name': '{{ SUPERSET_OPENEDX_ROLE_NAME }}', 'group_key': '{{ SUPERSET_ROW_LEVEL_SECURITY_XAPI_GROUP_KEY }}', 'clause': '{{can_view_courses(current_username(),"splitByChar("/", course_id)[-1]")}}', 'filter_type': 'Regular'}]
`

**Describe the solution you'd like**
The variables are interpolated inside list and tuples

**Describe alternatives you've considered**
Is there another way to handle this?

A patch doesn't seem like a good idea to cover those cases

**Additional context**

**Comment by Ian2012** [comment]
Thanks, that's the approach I come up with: https://github.com/openedx/tutor-contrib-aspects/pull/107/files#diff-6d40bfd019739946f0dd4c07c198277f703115a439cbbe5c8212e43ef9f5ef19

**Comment by regisb** [comment]
I would use a different approach:

1. Move the contents from superset-row-level-security to `create_row_level_security.py`
2. Rewrite the `create_row_level_security.py` file as follows:

```
SECURITY_FILTERS = [
    {
        ...
    }
]

def bootstrap_security_filters():
    for security_filter in SECURITY_FILTERS:
        ...

{{ patch("aspects-create-row-level-security") }}

bootstrap_security_filters()
```

3. Document the "aspects-create-row-level-security" patch in the readme.

**Comment by Ian2012** [comment]
It would allow modifying and adding existing security filters but that can be accomplished by providing the same table_name, group_key, and role, but it's a good extensibility point 🤔.

@bmtcril what do you think?
