### ISSUE TITLE
Feature request: Don't suggest adding the user to `docker` group for security reasons

### ISSUE THREAD

**Issue by ghost** [overhangio/tutor#874]
**Is your feature request related to a problem? Please describe.**
Adding the Linux user e.g. `whoami > omar` to the `docker` group is discouraged by docker these days -- for good reasons. It is the equivalent of providing passwordless sudo to all running applications and their plugins. 

MacOS or even Linux Docker Desktop users don't have this issue because Docker runs in its own Virtual Machine, therefore there's no need to adding the user to the `docker` group.

> The docker group grants root-level privileges to the user [and all running applications, which makes desktop users very vulnerable]. For details on how this impacts security in your system, see [Docker Daemon Attack Surface](https://docs.docker.com/engine/security/#docker-daemon-attack-surface). -- [Docker docs](https://docs.docker.com/engine/install/linux-postinstall/) in addition to my explanation between brackets.

Tutor gives this advice -- which I think it shouldn't:

https://github.com/overhangio/tutor/blob/faf43bd3b0adafc0f71b129fe71e82ab9c6a0e7d/tutor/commands/cli.py#L115-L119

**Describe the solution you'd like**

Use rootless docker. I recently started using rootless docker which is -- surprisingly -- compatible with the Open edX devstack. Last time I tested it with Tutor I had problems. I plan to test again in two weeks or so.

**Describe alternatives you've considered**
Enforce sudo prefix to all docker calls.

I usually solve this by creating two scripts in the `~/bin` directory, which is a non-standard solution that I came up with:

```sh
# ~/bin/docker
sudo /usr/bin/docker "$@"
```

```sh
# ~/bin/docker-compose
sudo /user/bin/docker-compose "$@"
```

Which works 99% of the cases, but sometimes fails if Docker-compose or `devstack` tries to do something "too smart"/complicated.

It's annoying since it requires entering a password for every new Terminal instance for even the simplest commands like `docker ps`.

**Additional context**

 - Deamon attack surfact: https://docs.docker.com/engine/security/#docker-daemon-attack-surface

**Comment by OmarMeetInc** [comment]
Apparently, I've posted from another GitHub account -- @OmarIthawi.

**Comment by OmarIthawi** [comment]
Please close this in favor of the other issue so I can follow up with it: https://github.com/overhangio/tutor/issues/875
