### ISSUE TITLE
Docs: No Wizard TPI

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#882]
Hi @regisb 
I was reading the documentation on plugins and noticed that running `tutor plugins index add wizard` will return 404. 
is this something for a premium version of tutor or it simply doesn't exist?

**Comment by regisb** [comment]
These instructions refer to the "wizard" index, which used to contained premium plugins, including [Cairn](https://github.com/overhangio/tutor-cairn). But now that these plugins are [free for everyone](https://discuss.openedx.org/t/cairn-scalable-real-time-analytics-for-open-edx-now-free-for-everyone/10150) the indexes were removed from the TPI repo: https://github.com/overhangio/tpi

Thus, we would need to update the docs. Would you like to open a PR?
