### ISSUE TITLE
Documentation about docker compose is wrong

### ISSUE THREAD

**Issue by ChristianVerhoeven** [overhangio/tutor#891]
The documentation says that docker-compose is the default but it is not, docker compose is used as can be seen in the error. How do I set docker-compose?

**Bug description**
On a new clean Ubuntu VM after installing tutor using pip and installing docker and docker-compose the following command fails: 
```bash
tutor local launch
```

The following error is given:
```bash
Command failed with status 125: docker compose -f /root/.local/share/tutor/env/local/docker-compose.yml -f /root/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local
```
**How to reproduce**
1. Clean install of Ubuntu Server 20.04
2. Install pip
3. Install tutor using pip
4. Install docker and docker-compose (not docker.io)
5. run tutor local launch

**Environment**
OS: Ubuntu Server 20.04, Tutor version: 16.0.5

**Comment by GoZippy** [comment]
same issue

**Comment by ChristianVerhoeven** [comment]
> @ChristianVerhoeven I'm not sure I understand. Which part of the docs is incorrect? Also, will your issue be resolved by #868?

@regisb The documentation says that docker-compose is the default unless you specify otherwise but the default used when running tutor local launch is docker compose and not docker-compose. 

So it breaks with the error specified in the initial post, and I cannot get it to work.

**Comment by regisb** [comment]
> The documentation says

1. Where exactly? Please post a link. 
2. Will #868 resolve the documentation error?

**Comment by regisb** [comment]
Closed by https://github.com/overhangio/tutor/commit/97b999b51927f11869b686f1257a58927009c9e1

**Comment by DagimAsnake** [comment]
Am also getting same error did you guys solved it or what???
