### ISSUE TITLE
Email testing tools for dev environment

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#894]
Hi there
instead of configuring an SMTP server on the Local environment and sending real emails or having the content print on the terminal, isn't it better to have some mail testing tools baked into the system only for dev?
of course, there are a lot of tools out there, but I used [MailHog](https://github.com/mailhog/MailHog) in my projects, which never failed me.

**Comment by regisb** [comment]
I think that the default should still be to send emails using the default smtp server, to make sure that the development and production environments are similar.

Can I suggest you implement a plugin to redirect emails to mailhog?

If you agree please close this issue.
