### ISSUE TITLE
Open EDX Development, mount lms edx-platform code on host machine bug

### ISSUE THREAD

**Issue by Silidrone** [overhangio/tutor#895]
I first run:
`tutor dev copyfrom lms /openedx/edx-platform /home/silidrone/.local/share/tutor/edx-platform`

then:
`tutor mounts add lms:/home/silidrone/.local/share/tutor/edx-platform:/openedx/edx-platform`

and then (I need this to apply new themes):
`tutor images build openedx`

After which I get:

> ERROR: failed to get build context edx-platform: stat lms,cms,lms-worker,cms-worker:/home/silidrone/.local/share/tutor/edx_platform:/openedx/edx-platform: no such file or directory

I tried adding build mounts too, but that didn't work either.

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
