### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by calvincaniSA** [overhangio/tutor#899]
Hello I am new to this and trying to learn the system. I read in the docs and on several pages it talks about running the command 'tutor local launch' to get a  open edx platform going. But running that command gives me an error Error: No such command 'launch'.

So are the docs outdated? I started with this today so I installed what I presume to be the latest version of Tutor so it cannot be I'm running an outdated version of Tutor is it?

If you run tutor local  then there is no command 'launch' listed in the commands list.

Am I doing something wrong?

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
