### ISSUE TITLE
Is there an option to deploy Tutor with Helm?

### ISSUE THREAD

**Issue by liyaka** [overhangio/tutor#904]
If yes, where can I find its helm chart?

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
