### ISSUE TITLE
Django 4.2 upgrade for Quince

### ISSUE THREAD

**Issue by cmltaWt0** [overhangio/tutor#930]
As part of Django 4.2 upgrade work for Quince we have to update tutor core and plugins.

BTR issue: https://github.com/openedx/wg-build-test-release/issues/315

Changes so far:
- https://github.com/overhangio/tutor/pull/929
- https://github.com/overhangio/tutor-mfe/pull/159

Additional plugins to update:
- TODO

**Comment by regisb** [comment]
Max, can we close this issue and centralize all information on the [upstream BTR issue](https://github.com/openedx/wg-build-test-release/issues/315)?
