### ISSUE TITLE
Login, redirection and access courses have been broken

### ISSUE THREAD

**Issue by inassistsoft** [overhangio/tutor#931]
We are developing a Django app that connects with the API of an AWS Tutor instance. Without applying any change (as far as we know), the Tutor instance started to fail.

**Bug description**

We have the next issues:

1. Users can login, but next message appears:

![image](https://github.com/overhangio/tutor/assets/150026798/3daa7ac9-654b-4e10-b3ab-9b7fd4d29734)

The redirection is done to "apps." domain, we think this is not correct.

In the lms container appears the next:

![Screenshot from 2023-11-06 12-34-49_crop](https://github.com/overhangio/tutor/assets/150026798/84b9c775-18bd-4af5-a25f-949ec072d548)

Even though, going to the main LMS or CMS pages, the login is done correctly (due to cookies token) and user can access those pages. But the redirection is not done correctly and final users cannot see these kind of errors.

2. The detail page of a course is not accessible, same happens to the Account page of a user. For some reason, any URL includes the subdomain "apps.". We think that before this error occurs, the domain was the original without any subdomain.

We tried to restart and reboot tutor but the problems persist.
We can share privately the URLs and credentials if tutor developers need them.

**Environment**
Ubuntu 22.04. Tutor 15.0.0 using AWS.

**Comment by regisb** [comment]
I don't understand. You are saying that no change were applied, but that you are developing a Django app to connect to the API. Did you make any change to the Open edX instance to get that Django app to work? In particular, did you create an authentication client?

**Comment by inassistsoft** [comment]
We are working with an external Django app that calls the API of a Tutor instance. The Tutor instance is completely fresh.
Some weeks ago we created an Application to use the API in our external app and worked fine.
But the problem is that the normal login for users is currently broken. Independently of the use of this Application, that also is not working.

The most annoying fact is that some URLs uses the subdomain "apps.". When we enter to the detail page of a course, the page becomes empty and the console shows the next:

![image](https://github.com/overhangio/tutor/assets/150026798/b7a0bcfd-a3da-471d-b2a9-5348be38259f)

**Comment by regisb** [comment]
The issue you are facing is not directly related to Tutor, but to your specific environment. I suggest you open a new topic on the official Open edX forum: https://discuss.openedx.org/
