### ISSUE TITLE
Hostname migration: local.overhang.io -> local.edly.io & docs.tutor.overhang.io -> docs.tutor.edly.io

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#945]
We are going to change two important domain names associated to Tutor:

1. The Tutor documentation will be moved to docs.tutor.edly.io.
    * [x] Create DNS records
    * [x] Move the documentation to docs.tutor.edly.io
    * [x] Preserve existing links with a 301 (permanent) redirect
    * [x] Replace all instances of docs.tutor.overhang.io in all plugins
2. When running Open edX locally, the hostnames will change from `*.local.overhang.io` to `*.local.edly.io`.
    * [x] Create DNS records ([local.edly.io](https://dnschecker.org/#A/local.edly.io) and [*.local.edly.io](https://dnschecker.org/#CNAME/foobar.local.edly.io))
    * [x] Replace all instances of *.local.overhang.io in all plugins in nightly
    * [x] Rebase Quince branches on top of nightly

Item 1. should be fairly transparent for all users. Item 2. is non-backward compatible, so we are taking the opportunity of the Quince release to make that change.

Both changes should be as simple as a search-and-replace in all plugin repositories, and I'm OK to implement the changes myself. But I'm curious to hear from @overhangio/tutor-maintainers if there is any question whatsoever about this issue?

**Comment by kdmccormick** [comment]
Hey @regisb , we'd talked about the dev domain [before](https://github.com/openedx/wg-devops/issues/18) and I said I'd set up a new domain before Quince, which I never did. Oops.

I'm interested in having something that we could use as a default in Open edX repos, so ideally that'd be something that doesn't mention Tutor or Edly. But I know the Quince release is coming up quickly. Give me 24 hours to come up with an alternative proposal, and if I don't have anything, then feel free to go ahead with local.edly.io.
