### ISSUE TITLE
Your terminal doesn't support cursor position requests (CPR).

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#949]
How to reproduce:

run `tutor dev start` (without `-d`) and logs will be printed in the terminal
add a breakpoint to your code and call that part:
```
tutor_dev-lms-1            | > /openedx/requirements/edspirit/console/views.py(1234)some_func()
tutor_dev-lms-1            |      923             breakpoint()
tutor_dev-lms-1            | -->  924             course_key = CourseKey.from_string(course_key_string)
tutor_dev-lms-1            |      925             course_details = CourseDetails.fetch(course_key)
tutor_dev-lms-1            | WARNING: your terminal doesn't support cursor position requests (CPR).
```

OS: Ubuntu 2022.04
tutor 16.1.7
I'm using ZShell, but tested it on Bash.

**Comment by regisb** [comment]
Yes, that's normal behaviour. You should run `tutor dev start -d && tutor dev start lms` to attach to the lms container: https://docs.tutor.edly.io/dev.html#debugging-with-breakpoints

**Comment by CodeWithEmad** [comment]
You're absolutely right! I used the `breakpoint` with `tutor` before but forgot about it. 
Do you think having something like: "You have to run in detached mode `tutor dev start -d` and then start your service with `tutor dev start`" in the debugging section will clarify that part?

**Comment by regisb** [comment]
If you think the documentation could be clarified, then by all means please open a PR :)
