### ISSUE TITLE
Include and enable the Indigo theme in the default Open edX image

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#953]
Out of the box, the Open edX default theme is close to unusable. An Open edX platform could not be deployed in production with the default theme: there are usability issues, broken links and the landing page is... not great.

We propose to install and enable the Indigo theme by default for all new Open edX platforms. In practice, this will mean the following:

- "indigo" will be added to the default "PLUGINS" settings, similar to the "mfe" plugin.
- The indigo plugin will _not_ be enabled for existing platforms which have already modified the PLUGINS setting.
- The indigo theme will be automatically set for platforms that have not already defined a custom theme.

The Indigo theme is [currently undergoing an upgrade](https://discuss.openedx.org/t/indigo-theme-upgrades/11445) which will result in a thorough overhaul. In other words, it will look much better than it does now.

Please comment on this issue if you have any question or comment.

**Comment by kdmccormick** [comment]
@regisb Why make Indigo the Tutor-level default, rather then fixing edx-platform's default to be more like Indigo?

**Comment by regisb** [comment]
That's a fair question. In a nutshell: it's much easier and faster to assemble an internal Edly team of UX/UI/frontend engineers to improve the 3rd-party Indigo theme than to address the issues of the default theme upstream. That being said, I agree that the "right" solution would be to fix the default theme. We would be thrilled if Indigo could eventually become the starting point for the new default theme, and we would like to work to that end. We would also like to take this opportunity to propose a better mechanism to extend MFE themes. I think we could achieve that in time for Redwood. How does that sound?

**Comment by brian-smith-tcril** [comment]
> We would also like to take this opportunity to propose a better mechanism to extend MFE themes.

What did you have in mind? I'm curious as to how that would fit in with the design tokens work ([ADR](https://github.com/openedx/paragon/blob/master/docs/decisions/0019-scaling-styles-with-design-tokens.rst))

**Comment by arbrandes** [comment]
@regisb

> I'm guessing join the frontend working group meetings?

It sounds to me like this would be a very productive start.  There are efforts under way (in different stages, to be sure) to improve not only theming but pluggability - both related efforts.  I'd be very interested in learning in more detail what you envision this system to be like, so we can avoid duplicating work.

**Comment by regisb** [comment]
This will be closed by the upgrade to Quince #920.
