### ISSUE TITLE
Tutor tag v13.3.2 is only available in PyPI

### ISSUE THREAD

**Issue by OmarIthawi** [overhangio/tutor#961]
Could you please add a tag in GitHub for the `v13.3.2` release to reflect what's on PyPi https://pypi.org/project/tutor/13.3.2/?

This is useful for [TVM](https://github.com/eduNEXT/tvm) because it relies on GitHub:

 - https://github.com/eduNEXT/tvm/blob/2b5e5b1e39e262b54f28aa4d939ff75900e4676f/tvm/version_manager/infrastructure/version_manager_git_repository.py#L108-L116

Otherwise `$ tvm install v13.3.2` will fail with the following error:

```
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (5.2.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Usage: tvm install [OPTIONS] VERSION
Try 'tvm install --help' for help.

Error: Could not find target: v13.3.2
```

**Comment by OmarIthawi** [comment]
It appears to be [previously discussed](https://discuss.openedx.org/t/missing-py2neo-package-causing-build-issues-in-all-edx-platform-releases/11371/14) and the answer is "no"


> Felipe: This is a sensible answer, but if you don’t mind could you share the reason? We use a build CI that uses [TVM 1](https://github.com/eduNEXT/tvm) and can only take tagged versions of tutor as input. So I’d like to understand how this could come up in the future to update our CI scripts.

> Regis: If we published the tags on GitHub, then we would also have to publish the release branches. There is nothing confidential there, but it would be leading us down a slippery road, where we would have to maintain branches of past releases.
> I understand this is inconvenient, and I’m prepared to change my mind on this. But it’s an important change of direction, and thus we are not going to make that change overnight.

Please feel free to close this.

**Comment by regisb** [comment]
Yes, we still haven't decided how to proceed. Maybe we could maintain long-lived release branches, but make it clear that we are not backporting anything except for build-breaking fixes. I'm still torn on this.
