### ISSUE TITLE
Error: Missing configuration value: 'Crypto.PublicKey.RSA.RsaKey object' has no attribute 'dq'

### ISSUE THREAD

**Issue by vunguyen-dmt** [overhangio/tutor#962]
I upgraded tutor from 16.1.8 to 17.0.0
Tried to run tutor config save and get this error
![image](https://github.com/overhangio/tutor/assets/34919039/ffb751cc-6fae-432b-bbe4-50867fc8704a)

**Comment by regisb** [comment]
What's your version of pycryptodome?

```
pip freeze | grep pycryptodome
```

**Comment by vunguyen-dmt** [comment]
The output of  **pip freeze | grep pycryptodome** in my server is
pycryptodome==3.14.1

**Comment by regisb** [comment]
Can you try to upgrade? `pip install pycryptodome==3.19.0`

**Comment by vunguyen-dmt** [comment]
Running `pip install pycryptodome==3.19.0` fixed the problem. I can run tutor config save now.

**Comment by regisb** [comment]
FYI @vunguyen-dmt https://github.com/overhangio/tutor/pull/963
