### ISSUE TITLE
Tutor local launch and docker compose error

### ISSUE THREAD

**Issue by DagimAsnake** [overhangio/tutor#972]
**Bug description**

Failed to enable plugin 'indigo': plugin 'indigo' is not installed.
docker compose -f /home/gobeze/.local/share/tutor/env/local/docker-compose.yml -f /home/gobeze/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local logs
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Common Commands:
  run         Create and run a new container from an image
  exec        Execute a command in a running container
  ps          List containers
  build       Build an image from a Dockerfile
  pull        Download an image from a registry
  push        Upload an image to a registry
  images      List images
  login       Log in to a registry
  logout      Log out from a registry
  search      Search Docker Hub for images
  version     Show the Docker version information
  info        Display system-wide information

Management Commands:
  builder     Manage builds
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  plugin      Manage plugins
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Swarm Commands:
  config      Manage Swarm configs
  node        Manage Swarm nodes
  secret      Manage Swarm secrets
  service     Manage Swarm services
  stack       Manage Swarm stacks
  swarm       Manage Swarm

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  import      Import the contents from a tarball to create a filesystem image
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  wait        Block until one or more containers stop, then print their exit codes

Global Options:
      --config string      Location of client config files (default
                           "/home/gobeze/.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket to connect to
  -l, --log-level string   Set the logging level ("debug", "info",
                           "warn", "error", "fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "/home/gobeze/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default"/home/gobeze/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default
                           "/home/gobeze/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Run 'docker COMMAND --help' for more information on a command.

For more help on how to use Docker, head to https://docs.docker.com/go/guides/

Error: Command failed with status 125: docker compose -f /home/gobeze/.local/share/tutor/env/local/docker-compose.yml -f /home/gobeze/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local logs

**How to reproduce**

sudo apt install python3 python3-pip libyaml-dev
sudo curl -L "https://github.com/overhangio/tutor/releases/download/v17.0.0/tutor-$(uname -s)_$(uname -m)" -o /usr/local/bin/tutor
sudo chmod 0755 /usr/local/bin/tutor
tutor local launch

**Environment**
Ubuntu 20.04.6 LTS
Python 3.8.10
Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1
Docker Compose version v2.23.3
tutor, version 17.0.0

**Additional context**

![photo1703937189](https://github.com/overhangio/tutor/assets/101408330/8b370358-4312-45a0-bc35-57fc79e81032)
![photo1703937189](https://github.com/overhangio/tutor/assets/101408330/57cc2d03-98e6-4c01-8463-c49f4cd6b837)

**Comment by rajpipaliya048** [comment]
i got the same issue and i solved it can you tell me more about the error? what command did you pass?

**Comment by DagimAsnake** [comment]
> i got the same issue and i solved it can you tell me more about the error? what command did you pass?

i install docker, docker-compose and also tutor

To install tutor i followed the steps below:-
1) sudo apt install python3 python3-pip libyaml-dev
2) sudo curl -L "https://github.com/overhangio/tutor/releases/download/v17.0.0/tutor-$(uname -s)_$(uname -m)" -o /usr/local/bin/tutor
3) sudo chmod 0755 /usr/local/bin/tutor


Then when i write the command "tutor local launch" am getting the above error that the docker compose is not correct it should be write like this "docker-compose"

**Comment by rajpipaliya048** [comment]
try these two commands first then use tutor local launch
1. tutor plugins install indigo
2. tutor plugins enable indigo

**Comment by DagimAsnake** [comment]
> try these two commands first then use tutor local launch
> 
> 1. tutor plugins install indigo
> 2. tutor plugins enable indigo

![photo1704262178](https://github.com/overhangio/tutor/assets/101408330/3ae11aac-b7bc-4246-a61c-8a105164451d)


it isn't even letting me install the indigo

**Comment by satovarr** [comment]
Did you try with `tutor plugins update`?
If so, could you please send what it shows.

**Comment by satovarr** [comment]
Yes! That's what your log says. Try that and then `tutor plugins install indigo` and  `tutor plugins install indigo`

**Comment by DagimAsnake** [comment]
> Yes! That's what your log says. Try that and then `tutor plugins install indigo` and  `tutor plugins install indigo`

It's the latest version of tutor (17).... there is no way to update that and also I have tried to install indigo....
![IMG_20240104_173937_565.jpg](https://github.com/overhangio/tutor/assets/101408330/5b2943b4-f4d7-4fd6-b270-297bb8302e47)

**Comment by satovarr** [comment]
`tutor plugins update` is to update the plugins cache, not the tutor version. You can try the commands in this order.

1. `tutor plugins update`
2. `tutor plugins install indigo`
3. `tutor plugins enable indigo`

I had the same issue and that's how I solved it

**Comment by DagimAsnake** [comment]
> `tutor plugins update` is to update the plugins cache, not the tutor version. You can try the commands in this order.
> 
> 1. `tutor plugins update`
> 2. `tutor plugins install indigo`
> 3. `tutor plugins enable indigo`
> 
> I had the same issue and that's how I solved it

I did those three commands and i think it isn't allowing me to enable indigo and am getting this response 

![photo1704429964](https://github.com/overhangio/tutor/assets/101408330/1e099d4c-f66b-4af5-b1e4-b1bda8815bb6)

![photo1704429975](https://github.com/overhangio/tutor/assets/101408330/c1acae46-dfe7-4253-885c-8f33b82c5f76)

**Comment by rajpipaliya048** [comment]
try these steps
uninstall tutor and all it's plugints too 
thn install it again and run

tutor local launch

**Comment by satovarr** [comment]
If you installed tutor with pip and source code or binary, then you will have dependencies conflicts. 
It is possible that indigo is installing in pip but not in tutor config. I solve it like this:

```shell
# stop tutor
$ tutor local stop
$ tutor dev stop

# remove tutor and related data
$ sudo rm -rf "$(tutor config printroot)"
$ pip uninstall tutor-openedx tutor-indigo
$ sudo rm -rf /usr/local/bin/tutor

# reinstall clean
$ pip install "tutor[full]"
$ tutor plugins update
$ tutor plugins install indigo
$ tutor plugins enable indigo
```

Hope this helps! If you know another part that can have tutor code, delete it before reinstalling.

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing

Your issue is not related to the missing indigo plugin, but to an old version of docker compose. You should upgrade it: https://docs.tutor.edly.io/install.html#requirements
