### ISSUE TITLE
mysql initialization error

### ISSUE THREAD

**Issue by DagimAsnake** [overhangio/tutor#974]
![photo1704370323](https://github.com/overhangio/tutor/assets/101408330/4dca98a2-b115-4fb6-a47f-41cae9393255)

**Bug description**
Creating 1/0
 ✔ Container tutor_local-mysql-1  Running                                                                                                        0.0s 

Initialising MySQL...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [1/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [2/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [3/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [4/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [5/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [6/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [7/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [8/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [9/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [10/10] Waiting for MySQL service (this may take a while)...
MySQL initialisation error
Error: Command failed with status 1: docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml -f /root/.local/share/tutor/env/local/docker-compose.prod.yml -f /root/.local/share/tutor/env/local/docker-compose.tmp.yml --project-name tutor_local -f /root/.local/share/tutor/env/local/docker-compose.jobs.yml -f /root/.local/share/tutor/env/local/docker-compose.jobs.tmp.yml run --rm mysql-job sh -e -c echo "Initialising MySQL..."
mysql_connection_max_attempts=10
mysql_connection_attempt=0
until mysql -u root --password="LdKt6jl8" --host "mysql" --port 3306 -e 'exit'
do
    mysql_connection_attempt=$(expr $mysql_connection_attempt + 1)
    echo "    [$mysql_connection_attempt/$mysql_connection_max_attempts] Waiting for MySQL service (this may take a while)..."
    if [ $mysql_connection_attempt -eq $mysql_connection_max_attempts ]
    then
      echo "MySQL initialisation error" 1>&2
      exit 1
    fi
    sleep 10
done
echo "MySQL is up and running"

# edx-platform database
mysql -u root --password="LdKt6jl8" --host "mysql" --port 3306 -e "CREATE DATABASE IF NOT EXISTS openedx;"
mysql -u root --password="LdKt6jl8" --host "mysql" --port 3306 -e "CREATE USER IF NOT EXISTS 'openedx';"
mysql -u root --password="LdKt6jl8" --host "mysql" --port 3306 -e "ALTER USER 'openedx'@'%' IDENTIFIED BY 'I8HjtMy5';"
mysql -u root --password="LdKt6jl8" --host "mysql" --port 3306 -e "GRANT ALL ON openedx.* TO 'openedx'@'%';"

![photo1704370304](https://github.com/overhangio/tutor/assets/101408330/99ebf984-0548-48d8-a6bc-31133ba61736)

**How to reproduce**
sudo curl -L "https://github.com/overhangio/tutor/releases/download/v15.3.2/tutor-$(uname -s)_$(uname -m)" -o /usr/local/bin/tutor
sudo chmod 0755 /usr/local/bin/tutor
tutor local launch

**Environment**
Ubuntu 20.04.6 LTS
Python 3.8.10
Docker version 24.0.5, build 20.0.5-0ubuntu1~20.04.1
docker-compose version 2.23.3
tutor, version 15.3.2

**Additional context**
this is the docker running containers
![photo1704370511](https://github.com/overhangio/tutor/assets/101408330/757d3516-ed58-418a-aa1d-7ff7ce982fcf)

this is the tutor local logs mysql
![photo1704370542](https://github.com/overhangio/tutor/assets/101408330/3d2b13fd-d6b8-4e4b-bc3b-4fad0381841f)

![photo1704370572](https://github.com/overhangio/tutor/assets/101408330/2c7f8ded-98a9-43c6-8139-7319f219ecb0)

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
