### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by UbuntuEvangelist** [overhangio/tutor#995]
After setup openedx i see this 

This site can’t be reached demo.philaai.com took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_TIMED_OUT

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
